# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demande_modification_parametres.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DemandeModificationParametrages(object):
    def setupUi(self, DemandeModificationParametrages):
        DemandeModificationParametrages.setObjectName(_fromUtf8("DemandeModificationParametrages"))
        DemandeModificationParametrages.resize(903, 1063)
        self.centralwidget = QtGui.QWidget(DemandeModificationParametrages)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBoxNatDemande = QtGui.QGroupBox(self.frame)
        self.groupBoxNatDemande.setObjectName(_fromUtf8("groupBoxNatDemande"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBoxNatDemande)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButtonCorrectionVal = QtGui.QRadioButton(self.groupBoxNatDemande)
        self.radioButtonCorrectionVal.setChecked(True)
        self.radioButtonCorrectionVal.setObjectName(_fromUtf8("radioButtonCorrectionVal"))
        self.verticalLayout_3.addWidget(self.radioButtonCorrectionVal)
        self.radioButtonPriseEnCompteNewVal = QtGui.QRadioButton(self.groupBoxNatDemande)
        self.radioButtonPriseEnCompteNewVal.setObjectName(_fromUtf8("radioButtonPriseEnCompteNewVal"))
        self.verticalLayout_3.addWidget(self.radioButtonPriseEnCompteNewVal)
        self.verticalLayout_8.addWidget(self.groupBoxNatDemande)
        self.groupBoxDomaineIntervention = QtGui.QGroupBox(self.frame)
        self.groupBoxDomaineIntervention.setObjectName(_fromUtf8("groupBoxDomaineIntervention"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxDomaineIntervention)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioButtonGeneralite = QtGui.QRadioButton(self.groupBoxDomaineIntervention)
        self.radioButtonGeneralite.setObjectName(_fromUtf8("radioButtonGeneralite"))
        self.verticalLayout_4.addWidget(self.radioButtonGeneralite)
        self.radioButtonProduction = QtGui.QRadioButton(self.groupBoxDomaineIntervention)
        self.radioButtonProduction.setObjectName(_fromUtf8("radioButtonProduction"))
        self.verticalLayout_4.addWidget(self.radioButtonProduction)
        self.radioButtonSinistre = QtGui.QRadioButton(self.groupBoxDomaineIntervention)
        self.radioButtonSinistre.setObjectName(_fromUtf8("radioButtonSinistre"))
        self.verticalLayout_4.addWidget(self.radioButtonSinistre)
        self.verticalLayout_8.addWidget(self.groupBoxDomaineIntervention)
        self.groupBoxEntiteGeneralite = QtGui.QGroupBox(self.frame)
        self.groupBoxEntiteGeneralite.setEnabled(True)
        self.groupBoxEntiteGeneralite.setObjectName(_fromUtf8("groupBoxEntiteGeneralite"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBoxEntiteGeneralite)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radioButtonPays = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.radioButtonPays.setObjectName(_fromUtf8("radioButtonPays"))
        self.verticalLayout_5.addWidget(self.radioButtonPays)
        self.radioButtonVilles = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.radioButtonVilles.setObjectName(_fromUtf8("radioButtonVilles"))
        self.verticalLayout_5.addWidget(self.radioButtonVilles)
        self.radioButtonMarqueVehicule = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.radioButtonMarqueVehicule.setObjectName(_fromUtf8("radioButtonMarqueVehicule"))
        self.verticalLayout_5.addWidget(self.radioButtonMarqueVehicule)
        self.radioButtonSourceEnergie = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.radioButtonSourceEnergie.setObjectName(_fromUtf8("radioButtonSourceEnergie"))
        self.verticalLayout_5.addWidget(self.radioButtonSourceEnergie)
        self.radioButtonPuissance = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.radioButtonPuissance.setObjectName(_fromUtf8("radioButtonPuissance"))
        self.verticalLayout_5.addWidget(self.radioButtonPuissance)
        self.radioButtonCarrosserie = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.radioButtonCarrosserie.setObjectName(_fromUtf8("radioButtonCarrosserie"))
        self.verticalLayout_5.addWidget(self.radioButtonCarrosserie)
        self.radioButtonClassesSociopro = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.radioButtonClassesSociopro.setObjectName(_fromUtf8("radioButtonClassesSociopro"))
        self.verticalLayout_5.addWidget(self.radioButtonClassesSociopro)
        self.radioButtonProfession = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.radioButtonProfession.setObjectName(_fromUtf8("radioButtonProfession"))
        self.verticalLayout_5.addWidget(self.radioButtonProfession)
        self.radioButtonTypePermis = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.radioButtonTypePermis.setObjectName(_fromUtf8("radioButtonTypePermis"))
        self.verticalLayout_5.addWidget(self.radioButtonTypePermis)
        self.radioButtonTitreCivilite = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.radioButtonTitreCivilite.setObjectName(_fromUtf8("radioButtonTitreCivilite"))
        self.verticalLayout_5.addWidget(self.radioButtonTitreCivilite)
        self.verticalLayout_8.addWidget(self.groupBoxEntiteGeneralite)
        self.groupBoxEntiteProduction = QtGui.QGroupBox(self.frame)
        self.groupBoxEntiteProduction.setObjectName(_fromUtf8("groupBoxEntiteProduction"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBoxEntiteProduction)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.radioButtonCompagnie = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.radioButtonCompagnie.setObjectName(_fromUtf8("radioButtonCompagnie"))
        self.verticalLayout_6.addWidget(self.radioButtonCompagnie)
        self.radioButtonReseau = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.radioButtonReseau.setObjectName(_fromUtf8("radioButtonReseau"))
        self.verticalLayout_6.addWidget(self.radioButtonReseau)
        self.radioButtonGestionnaire = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.radioButtonGestionnaire.setObjectName(_fromUtf8("radioButtonGestionnaire"))
        self.verticalLayout_6.addWidget(self.radioButtonGestionnaire)
        self.radioButtonClient = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.radioButtonClient.setObjectName(_fromUtf8("radioButtonClient"))
        self.verticalLayout_6.addWidget(self.radioButtonClient)
        self.radioButtonPolice = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.radioButtonPolice.setObjectName(_fromUtf8("radioButtonPolice"))
        self.verticalLayout_6.addWidget(self.radioButtonPolice)
        self.radioButtonMouvement = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.radioButtonMouvement.setObjectName(_fromUtf8("radioButtonMouvement"))
        self.verticalLayout_6.addWidget(self.radioButtonMouvement)
        self.radioButtonRisques = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.radioButtonRisques.setObjectName(_fromUtf8("radioButtonRisques"))
        self.verticalLayout_6.addWidget(self.radioButtonRisques)
        self.radioButtonGaranties = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.radioButtonGaranties.setObjectName(_fromUtf8("radioButtonGaranties"))
        self.verticalLayout_6.addWidget(self.radioButtonGaranties)
        self.radioButtonZoneTarification = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.radioButtonZoneTarification.setObjectName(_fromUtf8("radioButtonZoneTarification"))
        self.verticalLayout_6.addWidget(self.radioButtonZoneTarification)
        self.radioButtonTarifs = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.radioButtonTarifs.setObjectName(_fromUtf8("radioButtonTarifs"))
        self.verticalLayout_6.addWidget(self.radioButtonTarifs)
        self.radioButtonAutres = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.radioButtonAutres.setObjectName(_fromUtf8("radioButtonAutres"))
        self.verticalLayout_6.addWidget(self.radioButtonAutres)
        self.verticalLayout_8.addWidget(self.groupBoxEntiteProduction)
        self.groupBoxEntiteSinistre = QtGui.QGroupBox(self.frame)
        self.groupBoxEntiteSinistre.setEnabled(True)
        self.groupBoxEntiteSinistre.setObjectName(_fromUtf8("groupBoxEntiteSinistre"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBoxEntiteSinistre)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.radioButtonCompagniesAdverses = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonCompagniesAdverses.setObjectName(_fromUtf8("radioButtonCompagniesAdverses"))
        self.verticalLayout_7.addWidget(self.radioButtonCompagniesAdverses)
        self.radioButtonExpertOuIntervenant = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonExpertOuIntervenant.setObjectName(_fromUtf8("radioButtonExpertOuIntervenant"))
        self.verticalLayout_7.addWidget(self.radioButtonExpertOuIntervenant)
        self.radioButtonNatSinistre = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonNatSinistre.setObjectName(_fromUtf8("radioButtonNatSinistre"))
        self.verticalLayout_7.addWidget(self.radioButtonNatSinistre)
        self.radioButtonStatutsFourniturePieces = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonStatutsFourniturePieces.setObjectName(_fromUtf8("radioButtonStatutsFourniturePieces"))
        self.verticalLayout_7.addWidget(self.radioButtonStatutsFourniturePieces)
        self.radioButtonEtatsEvolutionDossiers = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonEtatsEvolutionDossiers.setObjectName(_fromUtf8("radioButtonEtatsEvolutionDossiers"))
        self.verticalLayout_7.addWidget(self.radioButtonEtatsEvolutionDossiers)
        self.radioButtonListePiecesAFournir = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonListePiecesAFournir.setObjectName(_fromUtf8("radioButtonListePiecesAFournir"))
        self.verticalLayout_7.addWidget(self.radioButtonListePiecesAFournir)
        self.radioButtonNatEvaluations = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonNatEvaluations.setObjectName(_fromUtf8("radioButtonNatEvaluations"))
        self.verticalLayout_7.addWidget(self.radioButtonNatEvaluations)
        self.radioButtonTypeRecours = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonTypeRecours.setObjectName(_fromUtf8("radioButtonTypeRecours"))
        self.verticalLayout_7.addWidget(self.radioButtonTypeRecours)
        self.radioButtonObjetMissionsExp = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonObjetMissionsExp.setObjectName(_fromUtf8("radioButtonObjetMissionsExp"))
        self.verticalLayout_7.addWidget(self.radioButtonObjetMissionsExp)
        self.radioButtonEtapesEvoExp = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonEtapesEvoExp.setObjectName(_fromUtf8("radioButtonEtapesEvoExp"))
        self.verticalLayout_7.addWidget(self.radioButtonEtapesEvoExp)
        self.radioButtonPostePrejudice = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonPostePrejudice.setObjectName(_fromUtf8("radioButtonPostePrejudice"))
        self.verticalLayout_7.addWidget(self.radioButtonPostePrejudice)
        self.radioButtonObjetsContentieux = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonObjetsContentieux.setObjectName(_fromUtf8("radioButtonObjetsContentieux"))
        self.verticalLayout_7.addWidget(self.radioButtonObjetsContentieux)
        self.radioButtonJuriContentieux = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonJuriContentieux.setObjectName(_fromUtf8("radioButtonJuriContentieux"))
        self.verticalLayout_7.addWidget(self.radioButtonJuriContentieux)
        self.radioButtonObjetsCorrespondances = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonObjetsCorrespondances.setObjectName(_fromUtf8("radioButtonObjetsCorrespondances"))
        self.verticalLayout_7.addWidget(self.radioButtonObjetsCorrespondances)
        self.radioButtonNatRelances = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonNatRelances.setObjectName(_fromUtf8("radioButtonNatRelances"))
        self.verticalLayout_7.addWidget(self.radioButtonNatRelances)
        self.radioButtonQualifVictimes = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.radioButtonQualifVictimes.setObjectName(_fromUtf8("radioButtonQualifVictimes"))
        self.verticalLayout_7.addWidget(self.radioButtonQualifVictimes)
        self.verticalLayout_8.addWidget(self.groupBoxEntiteSinistre)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelValAModifier = QtGui.QLabel(self.frame_2)
        self.labelValAModifier.setObjectName(_fromUtf8("labelValAModifier"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelValAModifier)
        self.lineEditValAModifier = QtGui.QLineEdit(self.frame_2)
        self.lineEditValAModifier.setObjectName(_fromUtf8("lineEditValAModifier"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditValAModifier)
        self.labelValAPrendreEnCompte = QtGui.QLabel(self.frame_2)
        self.labelValAPrendreEnCompte.setObjectName(_fromUtf8("labelValAPrendreEnCompte"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelValAPrendreEnCompte)
        self.lineEditValAPrendreEnCompte = QtGui.QLineEdit(self.frame_2)
        self.lineEditValAPrendreEnCompte.setObjectName(_fromUtf8("lineEditValAPrendreEnCompte"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditValAPrendreEnCompte)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.groupBox = QtGui.QGroupBox(self.frame_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textBrowserListeValeursActuelles = QtGui.QTextBrowser(self.groupBox)
        self.textBrowserListeValeursActuelles.setObjectName(_fromUtf8("textBrowserListeValeursActuelles"))
        self.verticalLayout.addWidget(self.textBrowserListeValeursActuelles)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        DemandeModificationParametrages.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DemandeModificationParametrages)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Fichier = QtGui.QMenu(self.menubar)
        self.menu_Fichier.setObjectName(_fromUtf8("menu_Fichier"))
        self.menu_Edition = QtGui.QMenu(self.menubar)
        self.menu_Edition.setObjectName(_fromUtf8("menu_Edition"))
        DemandeModificationParametrages.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DemandeModificationParametrages)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DemandeModificationParametrages.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(DemandeModificationParametrages)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        DemandeModificationParametrages.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNouveau = QtGui.QAction(DemandeModificationParametrages)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-new.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNouveau.setIcon(icon)
        self.actionNouveau.setObjectName(_fromUtf8("actionNouveau"))
        self.actionEnregistrer = QtGui.QAction(DemandeModificationParametrages)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-save.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnregistrer.setIcon(icon1)
        self.actionEnregistrer.setObjectName(_fromUtf8("actionEnregistrer"))
        self.actionImprimer_Fiche_Modification_Parametrages = QtGui.QAction(DemandeModificationParametrages)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Imprimer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImprimer_Fiche_Modification_Parametrages.setIcon(icon2)
        self.actionImprimer_Fiche_Modification_Parametrages.setObjectName(_fromUtf8("actionImprimer_Fiche_Modification_Parametrages"))
        self.actionFermer = QtGui.QAction(DemandeModificationParametrages)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/system-log-out.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFermer.setIcon(icon3)
        self.actionFermer.setObjectName(_fromUtf8("actionFermer"))
        self.actionAnnuler = QtGui.QAction(DemandeModificationParametrages)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-undo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnnuler.setIcon(icon4)
        self.actionAnnuler.setObjectName(_fromUtf8("actionAnnuler"))
        self.actionRefaire = QtGui.QAction(DemandeModificationParametrages)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-redo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefaire.setIcon(icon5)
        self.actionRefaire.setObjectName(_fromUtf8("actionRefaire"))
        self.actionPremier = QtGui.QAction(DemandeModificationParametrages)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-first.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPremier.setIcon(icon6)
        self.actionPremier.setObjectName(_fromUtf8("actionPremier"))
        self.actionPrecedent = QtGui.QAction(DemandeModificationParametrages)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-previous.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrecedent.setIcon(icon7)
        self.actionPrecedent.setObjectName(_fromUtf8("actionPrecedent"))
        self.actionSuivant = QtGui.QAction(DemandeModificationParametrages)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-next.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSuivant.setIcon(icon8)
        self.actionSuivant.setObjectName(_fromUtf8("actionSuivant"))
        self.actionDernier = QtGui.QAction(DemandeModificationParametrages)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-last.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDernier.setIcon(icon9)
        self.actionDernier.setObjectName(_fromUtf8("actionDernier"))
        self.menu_Fichier.addAction(self.actionNouveau)
        self.menu_Fichier.addAction(self.actionEnregistrer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.actionImprimer_Fiche_Modification_Parametrages)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.actionFermer)
        self.menu_Edition.addAction(self.actionAnnuler)
        self.menu_Edition.addAction(self.actionRefaire)
        self.menu_Edition.addSeparator()
        self.menu_Edition.addAction(self.actionPremier)
        self.menu_Edition.addAction(self.actionPrecedent)
        self.menu_Edition.addAction(self.actionSuivant)
        self.menu_Edition.addAction(self.actionDernier)
        self.menubar.addAction(self.menu_Fichier.menuAction())
        self.menubar.addAction(self.menu_Edition.menuAction())
        self.toolBar.addAction(self.actionNouveau)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPremier)
        self.toolBar.addAction(self.actionPrecedent)
        self.toolBar.addAction(self.actionSuivant)
        self.toolBar.addAction(self.actionDernier)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRefaire)
        self.toolBar.addAction(self.actionAnnuler)
        self.toolBar.addAction(self.actionEnregistrer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionImprimer_Fiche_Modification_Parametrages)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFermer)

        self.retranslateUi(DemandeModificationParametrages)
        QtCore.QObject.connect(self.radioButtonGeneralite, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBoxEntiteGeneralite.setVisible)
        QtCore.QObject.connect(self.radioButtonProduction, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBoxEntiteProduction.setVisible)
        QtCore.QObject.connect(self.radioButtonSinistre, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBoxEntiteSinistre.setVisible)
        QtCore.QObject.connect(self.radioButtonGeneralite, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteProduction.hide)
        QtCore.QObject.connect(self.radioButtonGeneralite, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteSinistre.hide)
        QtCore.QObject.connect(self.radioButtonProduction, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteGeneralite.hide)
        QtCore.QObject.connect(self.radioButtonProduction, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteSinistre.hide)
        QtCore.QObject.connect(self.radioButtonSinistre, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteGeneralite.hide)
        QtCore.QObject.connect(self.radioButtonSinistre, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteProduction.hide)
        QtCore.QMetaObject.connectSlotsByName(DemandeModificationParametrages)

    def retranslateUi(self, DemandeModificationParametrages):
        DemandeModificationParametrages.setWindowTitle(_translate("DemandeModificationParametrages", "Demande De Modification De Parametrages", None))
        self.groupBoxNatDemande.setTitle(_translate("DemandeModificationParametrages", "Nature de la Demande", None))
        self.radioButtonCorrectionVal.setText(_translate("DemandeModificationParametrages", "Correction d\'une valeur erronee", None))
        self.radioButtonPriseEnCompteNewVal.setText(_translate("DemandeModificationParametrages", "Prise en compte d\'une Nouvelle Valeur", None))
        self.groupBoxDomaineIntervention.setTitle(_translate("DemandeModificationParametrages", "Domaine d\'Intervention", None))
        self.radioButtonGeneralite.setText(_translate("DemandeModificationParametrages", "Generalite", None))
        self.radioButtonProduction.setText(_translate("DemandeModificationParametrages", "Production", None))
        self.radioButtonSinistre.setText(_translate("DemandeModificationParametrages", "Sinistre", None))
        self.groupBoxEntiteGeneralite.setTitle(_translate("DemandeModificationParametrages", "Entite des Generalites a Modifier", None))
        self.radioButtonPays.setText(_translate("DemandeModificationParametrages", "Pays", None))
        self.radioButtonVilles.setText(_translate("DemandeModificationParametrages", "Villes", None))
        self.radioButtonMarqueVehicule.setText(_translate("DemandeModificationParametrages", "Marques de Vehicule", None))
        self.radioButtonSourceEnergie.setText(_translate("DemandeModificationParametrages", "Source d\'energie", None))
        self.radioButtonPuissance.setText(_translate("DemandeModificationParametrages", "Puissance", None))
        self.radioButtonCarrosserie.setText(_translate("DemandeModificationParametrages", "Carrosserie", None))
        self.radioButtonClassesSociopro.setText(_translate("DemandeModificationParametrages", "Classes Socioprofessionnelles", None))
        self.radioButtonProfession.setText(_translate("DemandeModificationParametrages", "Professions", None))
        self.radioButtonTypePermis.setText(_translate("DemandeModificationParametrages", "Types de Permis de Conduire", None))
        self.radioButtonTitreCivilite.setText(_translate("DemandeModificationParametrages", "Titres de Civilite", None))
        self.groupBoxEntiteProduction.setTitle(_translate("DemandeModificationParametrages", "Entite de la Production a Modifier", None))
        self.radioButtonCompagnie.setText(_translate("DemandeModificationParametrages", "Compagnie", None))
        self.radioButtonReseau.setText(_translate("DemandeModificationParametrages", "Reseau", None))
        self.radioButtonGestionnaire.setText(_translate("DemandeModificationParametrages", "Gestionnaire", None))
        self.radioButtonClient.setText(_translate("DemandeModificationParametrages", "Client", None))
        self.radioButtonPolice.setText(_translate("DemandeModificationParametrages", "Police", None))
        self.radioButtonMouvement.setText(_translate("DemandeModificationParametrages", "Mouvement", None))
        self.radioButtonRisques.setText(_translate("DemandeModificationParametrages", "Risques", None))
        self.radioButtonGaranties.setText(_translate("DemandeModificationParametrages", "Garanties", None))
        self.radioButtonZoneTarification.setText(_translate("DemandeModificationParametrages", "Zone de Tarification", None))
        self.radioButtonTarifs.setText(_translate("DemandeModificationParametrages", "Tarifs", None))
        self.radioButtonAutres.setText(_translate("DemandeModificationParametrages", "Autres", None))
        self.groupBoxEntiteSinistre.setTitle(_translate("DemandeModificationParametrages", "Entite des Sinistres a Modifier", None))
        self.radioButtonCompagniesAdverses.setText(_translate("DemandeModificationParametrages", "Compagnies Adverses", None))
        self.radioButtonExpertOuIntervenant.setText(_translate("DemandeModificationParametrages", "Expert ou Intervenant", None))
        self.radioButtonNatSinistre.setText(_translate("DemandeModificationParametrages", "Nature du Sinistre", None))
        self.radioButtonStatutsFourniturePieces.setText(_translate("DemandeModificationParametrages", "Statuts fourniture Pieces", None))
        self.radioButtonEtatsEvolutionDossiers.setText(_translate("DemandeModificationParametrages", "Etats d\'Evolution des Dossiers", None))
        self.radioButtonListePiecesAFournir.setText(_translate("DemandeModificationParametrages", "Liste des Pieces a fournir", None))
        self.radioButtonNatEvaluations.setText(_translate("DemandeModificationParametrages", "Natures des Evaluations", None))
        self.radioButtonTypeRecours.setText(_translate("DemandeModificationParametrages", "Type de Recours", None))
        self.radioButtonObjetMissionsExp.setText(_translate("DemandeModificationParametrages", "Objet des Missions d\'Expertise", None))
        self.radioButtonEtapesEvoExp.setText(_translate("DemandeModificationParametrages", "Etapes d\'Evolution des Expertises", None))
        self.radioButtonPostePrejudice.setText(_translate("DemandeModificationParametrages", "Postes de Prejudice", None))
        self.radioButtonObjetsContentieux.setText(_translate("DemandeModificationParametrages", "Objets de Contentieux", None))
        self.radioButtonJuriContentieux.setText(_translate("DemandeModificationParametrages", "Juridictions Contentieux", None))
        self.radioButtonObjetsCorrespondances.setText(_translate("DemandeModificationParametrages", "Objets des Correspondances", None))
        self.radioButtonNatRelances.setText(_translate("DemandeModificationParametrages", "Nature des Relances", None))
        self.radioButtonQualifVictimes.setText(_translate("DemandeModificationParametrages", "Qualification des Victimes", None))
        self.labelValAModifier.setText(_translate("DemandeModificationParametrages", "Ancienne Valeur a Modifier", None))
        self.labelValAPrendreEnCompte.setText(_translate("DemandeModificationParametrages", "Nouvelle Valeur a prendre en compte", None))
        self.groupBox.setTitle(_translate("DemandeModificationParametrages", "Liste des Valeurs Actuelles avant Modifications", None))
        self.menu_Fichier.setTitle(_translate("DemandeModificationParametrages", "&Fichier", None))
        self.menu_Edition.setTitle(_translate("DemandeModificationParametrages", "&Edition", None))
        self.toolBar.setWindowTitle(_translate("DemandeModificationParametrages", "toolBar", None))
        self.actionNouveau.setText(_translate("DemandeModificationParametrages", "Nouveau", None))
        self.actionEnregistrer.setText(_translate("DemandeModificationParametrages", "Enregistrer", None))
        self.actionImprimer_Fiche_Modification_Parametrages.setText(_translate("DemandeModificationParametrages", "Imprimer Fiche Modification Parametrages", None))
        self.actionFermer.setText(_translate("DemandeModificationParametrages", "Fermer", None))
        self.actionAnnuler.setText(_translate("DemandeModificationParametrages", "Annuler", None))
        self.actionRefaire.setText(_translate("DemandeModificationParametrages", "Refaire", None))
        self.actionPremier.setText(_translate("DemandeModificationParametrages", "Premier", None))
        self.actionPrecedent.setText(_translate("DemandeModificationParametrages", "Precedent", None))
        self.actionSuivant.setText(_translate("DemandeModificationParametrages", "Suivant", None))
        self.actionDernier.setText(_translate("DemandeModificationParametrages", "Dernier", None))

import ressources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DemandeModificationParametrages = QtGui.QMainWindow()
    ui = Ui_DemandeModificationParametrages()
    ui.setupUi(DemandeModificationParametrages)
    DemandeModificationParametrages.show()
    sys.exit(app.exec_())

