# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emissions.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Emissions(object):
    def setupUi(self, Emissions):
        Emissions.setObjectName(_fromUtf8("Emissions"))
        Emissions.resize(1375, 946)
        self.centralwidget = QtGui.QWidget(Emissions)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame_7 = QtGui.QFrame(self.centralwidget)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelNumClient = QtGui.QLabel(self.frame_7)
        self.labelNumClient.setObjectName(_fromUtf8("labelNumClient"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelNumClient)
        self.comboBoxNumClient = QtGui.QComboBox(self.frame_7)
        self.comboBoxNumClient.setObjectName(_fromUtf8("comboBoxNumClient"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxNumClient)
        self.labelPrenom = QtGui.QLabel(self.frame_7)
        self.labelPrenom.setObjectName(_fromUtf8("labelPrenom"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelPrenom)
        self.comboBoxPrenom = QtGui.QComboBox(self.frame_7)
        self.comboBoxPrenom.setObjectName(_fromUtf8("comboBoxPrenom"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxPrenom)
        self.labelNom = QtGui.QLabel(self.frame_7)
        self.labelNom.setObjectName(_fromUtf8("labelNom"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelNom)
        self.comboBoxNom = QtGui.QComboBox(self.frame_7)
        self.comboBoxNom.setObjectName(_fromUtf8("comboBoxNom"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBoxNom)
        self.labelProfession = QtGui.QLabel(self.frame_7)
        self.labelProfession.setObjectName(_fromUtf8("labelProfession"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelProfession)
        self.labelCivilite = QtGui.QLabel(self.frame_7)
        self.labelCivilite.setObjectName(_fromUtf8("labelCivilite"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelCivilite)
        self.labelLocalisation = QtGui.QLabel(self.frame_7)
        self.labelLocalisation.setObjectName(_fromUtf8("labelLocalisation"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.labelLocalisation)
        self.labelBP = QtGui.QLabel(self.frame_7)
        self.labelBP.setObjectName(_fromUtf8("labelBP"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.labelBP)
        self.lineEditBP = QtGui.QLineEdit(self.frame_7)
        self.lineEditBP.setObjectName(_fromUtf8("lineEditBP"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEditBP)
        self.labelVille = QtGui.QLabel(self.frame_7)
        self.labelVille.setObjectName(_fromUtf8("labelVille"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.labelVille)
        self.labelAdresse = QtGui.QLabel(self.frame_7)
        self.labelAdresse.setObjectName(_fromUtf8("labelAdresse"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.labelAdresse)
        self.lineEditAdresse = QtGui.QLineEdit(self.frame_7)
        self.lineEditAdresse.setObjectName(_fromUtf8("lineEditAdresse"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEditAdresse)
        self.labelSociete = QtGui.QLabel(self.frame_7)
        self.labelSociete.setObjectName(_fromUtf8("labelSociete"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.labelSociete)
        self.lineEditSociete = QtGui.QLineEdit(self.frame_7)
        self.lineEditSociete.setObjectName(_fromUtf8("lineEditSociete"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEditSociete)
        self.labelPosteOccupe = QtGui.QLabel(self.frame_7)
        self.labelPosteOccupe.setObjectName(_fromUtf8("labelPosteOccupe"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.LabelRole, self.labelPosteOccupe)
        self.lineEditPosteOccupe = QtGui.QLineEdit(self.frame_7)
        self.lineEditPosteOccupe.setObjectName(_fromUtf8("lineEditPosteOccupe"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineEditPosteOccupe)
        self.labelDepartement = QtGui.QLabel(self.frame_7)
        self.labelDepartement.setObjectName(_fromUtf8("labelDepartement"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.LabelRole, self.labelDepartement)
        self.labelZoneTarif = QtGui.QLabel(self.frame_7)
        self.labelZoneTarif.setObjectName(_fromUtf8("labelZoneTarif"))
        self.formLayout_2.setWidget(13, QtGui.QFormLayout.LabelRole, self.labelZoneTarif)
        self.labelTelBureau = QtGui.QLabel(self.frame_7)
        self.labelTelBureau.setObjectName(_fromUtf8("labelTelBureau"))
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.LabelRole, self.labelTelBureau)
        self.lineEditTelBureau = QtGui.QLineEdit(self.frame_7)
        self.lineEditTelBureau.setObjectName(_fromUtf8("lineEditTelBureau"))
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.FieldRole, self.lineEditTelBureau)
        self.labelTelPortable = QtGui.QLabel(self.frame_7)
        self.labelTelPortable.setObjectName(_fromUtf8("labelTelPortable"))
        self.formLayout_2.setWidget(15, QtGui.QFormLayout.LabelRole, self.labelTelPortable)
        self.lineEditTelPortable = QtGui.QLineEdit(self.frame_7)
        self.lineEditTelPortable.setObjectName(_fromUtf8("lineEditTelPortable"))
        self.formLayout_2.setWidget(15, QtGui.QFormLayout.FieldRole, self.lineEditTelPortable)
        self.labelFax = QtGui.QLabel(self.frame_7)
        self.labelFax.setObjectName(_fromUtf8("labelFax"))
        self.formLayout_2.setWidget(16, QtGui.QFormLayout.LabelRole, self.labelFax)
        self.lineEditFax = QtGui.QLineEdit(self.frame_7)
        self.lineEditFax.setObjectName(_fromUtf8("lineEditFax"))
        self.formLayout_2.setWidget(16, QtGui.QFormLayout.FieldRole, self.lineEditFax)
        self.labelMail = QtGui.QLabel(self.frame_7)
        self.labelMail.setObjectName(_fromUtf8("labelMail"))
        self.formLayout_2.setWidget(17, QtGui.QFormLayout.LabelRole, self.labelMail)
        self.lineEditMail = QtGui.QLineEdit(self.frame_7)
        self.lineEditMail.setObjectName(_fromUtf8("lineEditMail"))
        self.formLayout_2.setWidget(17, QtGui.QFormLayout.FieldRole, self.lineEditMail)
        self.labelEntreePortefeuille = QtGui.QLabel(self.frame_7)
        self.labelEntreePortefeuille.setObjectName(_fromUtf8("labelEntreePortefeuille"))
        self.formLayout_2.setWidget(18, QtGui.QFormLayout.LabelRole, self.labelEntreePortefeuille)
        self.comboBoxProfession = QtGui.QComboBox(self.frame_7)
        self.comboBoxProfession.setObjectName(_fromUtf8("comboBoxProfession"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBoxProfession)
        self.comboBoxCivilite = QtGui.QComboBox(self.frame_7)
        self.comboBoxCivilite.setObjectName(_fromUtf8("comboBoxCivilite"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBoxCivilite)
        self.comboBoxLocalisation = QtGui.QComboBox(self.frame_7)
        self.comboBoxLocalisation.setObjectName(_fromUtf8("comboBoxLocalisation"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.comboBoxLocalisation)
        self.comboBoxVille = QtGui.QComboBox(self.frame_7)
        self.comboBoxVille.setObjectName(_fromUtf8("comboBoxVille"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.comboBoxVille)
        self.comboBoxDepartement = QtGui.QComboBox(self.frame_7)
        self.comboBoxDepartement.setObjectName(_fromUtf8("comboBoxDepartement"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.FieldRole, self.comboBoxDepartement)
        self.comboBoxZoneTarif = QtGui.QComboBox(self.frame_7)
        self.comboBoxZoneTarif.setObjectName(_fromUtf8("comboBoxZoneTarif"))
        self.formLayout_2.setWidget(13, QtGui.QFormLayout.FieldRole, self.comboBoxZoneTarif)
        self.dateEditEntreePortefeuille = QtGui.QDateEdit(self.frame_7)
        self.dateEditEntreePortefeuille.setObjectName(_fromUtf8("dateEditEntreePortefeuille"))
        self.formLayout_2.setWidget(18, QtGui.QFormLayout.FieldRole, self.dateEditEntreePortefeuille)
        self.gridLayout_8.addLayout(self.formLayout_2, 0, 0, 1, 2)
        self.frame_8 = QtGui.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelPaiement = QtGui.QLabel(self.frame_8)
        self.labelPaiement.setObjectName(_fromUtf8("labelPaiement"))
        self.gridLayout.addWidget(self.labelPaiement, 0, 1, 1, 1)
        self.labelSolde = QtGui.QLabel(self.frame_8)
        self.labelSolde.setObjectName(_fromUtf8("labelSolde"))
        self.gridLayout.addWidget(self.labelSolde, 0, 2, 1, 1)
        self.labelEmission = QtGui.QLabel(self.frame_8)
        self.labelEmission.setObjectName(_fromUtf8("labelEmission"))
        self.gridLayout.addWidget(self.labelEmission, 0, 0, 1, 1)
        self.lineEditEmission = QtGui.QLineEdit(self.frame_8)
        self.lineEditEmission.setObjectName(_fromUtf8("lineEditEmission"))
        self.gridLayout.addWidget(self.lineEditEmission, 1, 0, 1, 1)
        self.lineEditPaiement = QtGui.QLineEdit(self.frame_8)
        self.lineEditPaiement.setObjectName(_fromUtf8("lineEditPaiement"))
        self.gridLayout.addWidget(self.lineEditPaiement, 1, 1, 1, 1)
        self.lineEditSolde = QtGui.QLineEdit(self.frame_8)
        self.lineEditSolde.setObjectName(_fromUtf8("lineEditSolde"))
        self.gridLayout.addWidget(self.lineEditSolde, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_8, 1, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBox_4 = QtGui.QComboBox(self.frame_7)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.horizontalLayout_2.addWidget(self.comboBox_4)
        self.comboBox_5 = QtGui.QComboBox(self.frame_7)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.horizontalLayout_2.addWidget(self.comboBox_5)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.toolButtonConditionsParticulieres = QtGui.QToolButton(self.frame_7)
        self.toolButtonConditionsParticulieres.setObjectName(_fromUtf8("toolButtonConditionsParticulieres"))
        self.gridLayout_8.addWidget(self.toolButtonConditionsParticulieres, 3, 0, 1, 1)
        self.toolButtonAttestationAssurance = QtGui.QToolButton(self.frame_7)
        self.toolButtonAttestationAssurance.setObjectName(_fromUtf8("toolButtonAttestationAssurance"))
        self.gridLayout_8.addWidget(self.toolButtonAttestationAssurance, 3, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_7, 0, 0, 2, 1)
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.frame = QtGui.QFrame(self.frame_4)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.labelCie = QtGui.QLabel(self.frame)
        self.labelCie.setObjectName(_fromUtf8("labelCie"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelCie)
        self.labelPoliceAgence = QtGui.QLabel(self.frame)
        self.labelPoliceAgence.setObjectName(_fromUtf8("labelPoliceAgence"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelPoliceAgence)
        self.labelResAgence = QtGui.QLabel(self.frame)
        self.labelResAgence.setObjectName(_fromUtf8("labelResAgence"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelResAgence)
        self.labelGestionnaire = QtGui.QLabel(self.frame)
        self.labelGestionnaire.setObjectName(_fromUtf8("labelGestionnaire"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelGestionnaire)
        self.comboBoxPoliceAgence = QtGui.QComboBox(self.frame)
        self.comboBoxPoliceAgence.setObjectName(_fromUtf8("comboBoxPoliceAgence"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxPoliceAgence)
        self.comboBoxCie = QtGui.QComboBox(self.frame)
        self.comboBoxCie.setObjectName(_fromUtf8("comboBoxCie"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxCie)
        self.comboBoxResAgence = QtGui.QComboBox(self.frame)
        self.comboBoxResAgence.setObjectName(_fromUtf8("comboBoxResAgence"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxResAgence)
        self.comboBoxGestionnaire = QtGui.QComboBox(self.frame)
        self.comboBoxGestionnaire.setObjectName(_fromUtf8("comboBoxGestionnaire"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBoxGestionnaire)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.labelBranche = QtGui.QLabel(self.frame)
        self.labelBranche.setObjectName(_fromUtf8("labelBranche"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelBranche)
        self.labelPoliceCie = QtGui.QLabel(self.frame)
        self.labelPoliceCie.setObjectName(_fromUtf8("labelPoliceCie"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelPoliceCie)
        self.lineEditPoliceCie = QtGui.QLineEdit(self.frame)
        self.lineEditPoliceCie.setObjectName(_fromUtf8("lineEditPoliceCie"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditPoliceCie)
        self.comboBoxBranche = QtGui.QComboBox(self.frame)
        self.comboBoxBranche.setObjectName(_fromUtf8("comboBoxBranche"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxBranche)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.textEdit = QtGui.QTextEdit(self.frame)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.labelFlotte = QtGui.QLabel(self.frame_2)
        self.labelFlotte.setObjectName(_fromUtf8("labelFlotte"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelFlotte)
        self.labelCreeeLe = QtGui.QLabel(self.frame_2)
        self.labelCreeeLe.setObjectName(_fromUtf8("labelCreeeLe"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelCreeeLe)
        self.labelDebutAnnuel = QtGui.QLabel(self.frame_2)
        self.labelDebutAnnuel.setObjectName(_fromUtf8("labelDebutAnnuel"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelDebutAnnuel)
        self.labelTermeAnnuel = QtGui.QLabel(self.frame_2)
        self.labelTermeAnnuel.setObjectName(_fromUtf8("labelTermeAnnuel"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelTermeAnnuel)
        self.dateEditCreeeLe = QtGui.QDateEdit(self.frame_2)
        self.dateEditCreeeLe.setObjectName(_fromUtf8("dateEditCreeeLe"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.dateEditCreeeLe)
        self.dateEditDebutAnnuel = QtGui.QDateEdit(self.frame_2)
        self.dateEditDebutAnnuel.setObjectName(_fromUtf8("dateEditDebutAnnuel"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.dateEditDebutAnnuel)
        self.dateEditTermeAnnuel = QtGui.QDateEdit(self.frame_2)
        self.dateEditTermeAnnuel.setObjectName(_fromUtf8("dateEditTermeAnnuel"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.dateEditTermeAnnuel)
        self.comboBoxFlotte = QtGui.QComboBox(self.frame_2)
        self.comboBoxFlotte.setObjectName(_fromUtf8("comboBoxFlotte"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxFlotte)
        self.horizontalLayout_4.addLayout(self.formLayout_5)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.labelValide = QtGui.QLabel(self.frame_2)
        self.labelValide.setObjectName(_fromUtf8("labelValide"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelValide)
        self.labelBonusMalus = QtGui.QLabel(self.frame_2)
        self.labelBonusMalus.setObjectName(_fromUtf8("labelBonusMalus"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelBonusMalus)
        self.labelReduction = QtGui.QLabel(self.frame_2)
        self.labelReduction.setObjectName(_fromUtf8("labelReduction"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelReduction)
        self.labelValAnnuelle = QtGui.QLabel(self.frame_2)
        self.labelValAnnuelle.setObjectName(_fromUtf8("labelValAnnuelle"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelValAnnuelle)
        self.lineEditBonusMalus = QtGui.QLineEdit(self.frame_2)
        self.lineEditBonusMalus.setObjectName(_fromUtf8("lineEditBonusMalus"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditBonusMalus)
        self.lineEditReduction = QtGui.QLineEdit(self.frame_2)
        self.lineEditReduction.setObjectName(_fromUtf8("lineEditReduction"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditReduction)
        self.lineEditValAnnuelle = QtGui.QLineEdit(self.frame_2)
        self.lineEditValAnnuelle.setObjectName(_fromUtf8("lineEditValAnnuelle"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditValAnnuelle)
        self.comboBoxValide = QtGui.QComboBox(self.frame_2)
        self.comboBoxValide.setObjectName(_fromUtf8("comboBoxValide"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxValide)
        self.horizontalLayout_4.addLayout(self.formLayout_6)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.gridLayout_7.addWidget(self.frame_4, 0, 1, 1, 2)
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.textBrowser = QtGui.QTextBrowser(self.frame_5)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_4.addWidget(self.textBrowser, 0, 0, 5, 1)
        self.formLayout_9 = QtGui.QFormLayout()
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.labelNomAssure = QtGui.QLabel(self.frame_5)
        self.labelNomAssure.setObjectName(_fromUtf8("labelNomAssure"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelNomAssure)
        self.lineEditNomAssure = QtGui.QLineEdit(self.frame_5)
        self.lineEditNomAssure.setObjectName(_fromUtf8("lineEditNomAssure"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditNomAssure)
        self.labelAdresseAssure = QtGui.QLabel(self.frame_5)
        self.labelAdresseAssure.setObjectName(_fromUtf8("labelAdresseAssure"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelAdresseAssure)
        self.lineEditAdresseAssure = QtGui.QLineEdit(self.frame_5)
        self.lineEditAdresseAssure.setObjectName(_fromUtf8("lineEditAdresseAssure"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditAdresseAssure)
        self.labelNomConducteur = QtGui.QLabel(self.frame_5)
        self.labelNomConducteur.setObjectName(_fromUtf8("labelNomConducteur"))
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelNomConducteur)
        self.lineEditNomConducteur = QtGui.QLineEdit(self.frame_5)
        self.lineEditNomConducteur.setObjectName(_fromUtf8("lineEditNomConducteur"))
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditNomConducteur)
        self.gridLayout_4.addLayout(self.formLayout_9, 1, 1, 1, 2)
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.labelNumChassi = QtGui.QLabel(self.frame_5)
        self.labelNumChassi.setObjectName(_fromUtf8("labelNumChassi"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelNumChassi)
        self.lineEditValVenale = QtGui.QLineEdit(self.frame_5)
        self.lineEditValVenale.setObjectName(_fromUtf8("lineEditValVenale"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditValVenale)
        self.labelImmatriculation_2 = QtGui.QLabel(self.frame_5)
        self.labelImmatriculation_2.setObjectName(_fromUtf8("labelImmatriculation_2"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelImmatriculation_2)
        self.lineEditImmatriculation = QtGui.QLineEdit(self.frame_5)
        self.lineEditImmatriculation.setObjectName(_fromUtf8("lineEditImmatriculation"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditImmatriculation)
        self.labelDatePremMC = QtGui.QLabel(self.frame_5)
        self.labelDatePremMC.setObjectName(_fromUtf8("labelDatePremMC"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelDatePremMC)
        self.dateEditDatePremMC = QtGui.QDateEdit(self.frame_5)
        self.dateEditDatePremMC.setObjectName(_fromUtf8("dateEditDatePremMC"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.dateEditDatePremMC)
        self.labelValNeuve = QtGui.QLabel(self.frame_5)
        self.labelValNeuve.setObjectName(_fromUtf8("labelValNeuve"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelValNeuve)
        self.lineEdit_28 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_28)
        self.labelValVenale = QtGui.QLabel(self.frame_5)
        self.labelValVenale.setObjectName(_fromUtf8("labelValVenale"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelValVenale)
        self.lineEdit_29 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_29)
        self.labelValAccessoire = QtGui.QLabel(self.frame_5)
        self.labelValAccessoire.setObjectName(_fromUtf8("labelValAccessoire"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelValAccessoire)
        self.lineEditValAccessoire = QtGui.QLineEdit(self.frame_5)
        self.lineEditValAccessoire.setObjectName(_fromUtf8("lineEditValAccessoire"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEditValAccessoire)
        self.gridLayout_4.addLayout(self.formLayout_7, 0, 1, 1, 1)
        self.formLayout_11 = QtGui.QFormLayout()
        self.formLayout_11.setObjectName(_fromUtf8("formLayout_11"))
        self.labelNumPermis = QtGui.QLabel(self.frame_5)
        self.labelNumPermis.setObjectName(_fromUtf8("labelNumPermis"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelNumPermis)
        self.labelCatPermis = QtGui.QLabel(self.frame_5)
        self.labelCatPermis.setObjectName(_fromUtf8("labelCatPermis"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelCatPermis)
        self.labelDateObtPermis = QtGui.QLabel(self.frame_5)
        self.labelDateObtPermis.setObjectName(_fromUtf8("labelDateObtPermis"))
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelDateObtPermis)
        self.labelValiditePermis = QtGui.QLabel(self.frame_5)
        self.labelValiditePermis.setObjectName(_fromUtf8("labelValiditePermis"))
        self.formLayout_11.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelValiditePermis)
        self.labelNumCapa = QtGui.QLabel(self.frame_5)
        self.labelNumCapa.setObjectName(_fromUtf8("labelNumCapa"))
        self.formLayout_11.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelNumCapa)
        self.labelValiditeCapa = QtGui.QLabel(self.frame_5)
        self.labelValiditeCapa.setObjectName(_fromUtf8("labelValiditeCapa"))
        self.formLayout_11.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelValiditeCapa)
        self.lineEditNumPermis = QtGui.QLineEdit(self.frame_5)
        self.lineEditNumPermis.setObjectName(_fromUtf8("lineEditNumPermis"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditNumPermis)
        self.comboBoxCatPermis = QtGui.QComboBox(self.frame_5)
        self.comboBoxCatPermis.setObjectName(_fromUtf8("comboBoxCatPermis"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxCatPermis)
        self.dateEditDateObtPermis = QtGui.QDateEdit(self.frame_5)
        self.dateEditDateObtPermis.setObjectName(_fromUtf8("dateEditDateObtPermis"))
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.FieldRole, self.dateEditDateObtPermis)
        self.dateEditValiditePermis = QtGui.QDateEdit(self.frame_5)
        self.dateEditValiditePermis.setObjectName(_fromUtf8("dateEditValiditePermis"))
        self.formLayout_11.setWidget(3, QtGui.QFormLayout.FieldRole, self.dateEditValiditePermis)
        self.lineEditNumCapa = QtGui.QLineEdit(self.frame_5)
        self.lineEditNumCapa.setObjectName(_fromUtf8("lineEditNumCapa"))
        self.formLayout_11.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditNumCapa)
        self.dateEditValiditeCapa = QtGui.QDateEdit(self.frame_5)
        self.dateEditValiditeCapa.setObjectName(_fromUtf8("dateEditValiditeCapa"))
        self.formLayout_11.setWidget(5, QtGui.QFormLayout.FieldRole, self.dateEditValiditeCapa)
        self.gridLayout_4.addLayout(self.formLayout_11, 2, 2, 2, 1)
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.labelMarque = QtGui.QLabel(self.frame_5)
        self.labelMarque.setObjectName(_fromUtf8("labelMarque"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelMarque)
        self.labelModelType = QtGui.QLabel(self.frame_5)
        self.labelModelType.setObjectName(_fromUtf8("labelModelType"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelModelType)
        self.labelGenre = QtGui.QLabel(self.frame_5)
        self.labelGenre.setObjectName(_fromUtf8("labelGenre"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelGenre)
        self.labelNbPlaces = QtGui.QLabel(self.frame_5)
        self.labelNbPlaces.setObjectName(_fromUtf8("labelNbPlaces"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelNbPlaces)
        self.labelPuissance = QtGui.QLabel(self.frame_5)
        self.labelPuissance.setObjectName(_fromUtf8("labelPuissance"))
        self.formLayout_8.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelPuissance)
        self.labelEnergie = QtGui.QLabel(self.frame_5)
        self.labelEnergie.setObjectName(_fromUtf8("labelEnergie"))
        self.formLayout_8.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelEnergie)
        self.comboBoxMarque = QtGui.QComboBox(self.frame_5)
        self.comboBoxMarque.setObjectName(_fromUtf8("comboBoxMarque"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxMarque)
        self.comboBoxModelType = QtGui.QComboBox(self.frame_5)
        self.comboBoxModelType.setObjectName(_fromUtf8("comboBoxModelType"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxModelType)
        self.comboBoxGenre = QtGui.QComboBox(self.frame_5)
        self.comboBoxGenre.setObjectName(_fromUtf8("comboBoxGenre"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxGenre)
        self.spinBoxNbPlaces = QtGui.QSpinBox(self.frame_5)
        self.spinBoxNbPlaces.setObjectName(_fromUtf8("spinBoxNbPlaces"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBoxNbPlaces)
        self.comboBoxPuissance = QtGui.QComboBox(self.frame_5)
        self.comboBoxPuissance.setObjectName(_fromUtf8("comboBoxPuissance"))
        self.formLayout_8.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBoxPuissance)
        self.comboBoxEnergie = QtGui.QComboBox(self.frame_5)
        self.comboBoxEnergie.setObjectName(_fromUtf8("comboBoxEnergie"))
        self.formLayout_8.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBoxEnergie)
        self.gridLayout_4.addLayout(self.formLayout_8, 0, 2, 1, 1)
        self.formLayout_10 = QtGui.QFormLayout()
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.labelZoneTarification = QtGui.QLabel(self.frame_5)
        self.labelZoneTarification.setObjectName(_fromUtf8("labelZoneTarification"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelZoneTarification)
        self.labelClassifPermis = QtGui.QLabel(self.frame_5)
        self.labelClassifPermis.setObjectName(_fromUtf8("labelClassifPermis"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelClassifPermis)
        self.labelCatSocioPro = QtGui.QLabel(self.frame_5)
        self.labelCatSocioPro.setObjectName(_fromUtf8("labelCatSocioPro"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelCatSocioPro)
        self.comboBoxZoneTarification = QtGui.QComboBox(self.frame_5)
        self.comboBoxZoneTarification.setObjectName(_fromUtf8("comboBoxZoneTarification"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxZoneTarification)
        self.comboBoxClassifPermis = QtGui.QComboBox(self.frame_5)
        self.comboBoxClassifPermis.setObjectName(_fromUtf8("comboBoxClassifPermis"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxClassifPermis)
        self.comboBoxCatSocioPro = QtGui.QComboBox(self.frame_5)
        self.comboBoxCatSocioPro.setObjectName(_fromUtf8("comboBoxCatSocioPro"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxCatSocioPro)
        self.gridLayout_4.addLayout(self.formLayout_10, 2, 1, 1, 1)
        self.frame_3 = QtGui.QFrame(self.frame_5)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBoxAttelageRemorque = QtGui.QCheckBox(self.frame_3)
        self.checkBoxAttelageRemorque.setObjectName(_fromUtf8("checkBoxAttelageRemorque"))
        self.gridLayout_3.addWidget(self.checkBoxAttelageRemorque, 0, 0, 1, 1)
        self.formLayout_12 = QtGui.QFormLayout()
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.labelMarqueAtRem = QtGui.QLabel(self.frame_3)
        self.labelMarqueAtRem.setObjectName(_fromUtf8("labelMarqueAtRem"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelMarqueAtRem)
        self.labelTypeAtRem = QtGui.QLabel(self.frame_3)
        self.labelTypeAtRem.setObjectName(_fromUtf8("labelTypeAtRem"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelTypeAtRem)
        self.comboBoxMarqueAtRem = QtGui.QComboBox(self.frame_3)
        self.comboBoxMarqueAtRem.setObjectName(_fromUtf8("comboBoxMarqueAtRem"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxMarqueAtRem)
        self.comboBoxTypeAtRem = QtGui.QComboBox(self.frame_3)
        self.comboBoxTypeAtRem.setObjectName(_fromUtf8("comboBoxTypeAtRem"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxTypeAtRem)
        self.gridLayout_3.addLayout(self.formLayout_12, 1, 0, 1, 1)
        self.formLayout_13 = QtGui.QFormLayout()
        self.formLayout_13.setObjectName(_fromUtf8("formLayout_13"))
        self.labelImmatriculation = QtGui.QLabel(self.frame_3)
        self.labelImmatriculation.setObjectName(_fromUtf8("labelImmatriculation"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelImmatriculation)
        self.lineEditimmatriculation = QtGui.QLineEdit(self.frame_3)
        self.lineEditimmatriculation.setObjectName(_fromUtf8("lineEditimmatriculation"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditimmatriculation)
        self.labelValRemorque = QtGui.QLabel(self.frame_3)
        self.labelValRemorque.setObjectName(_fromUtf8("labelValRemorque"))
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelValRemorque)
        self.lineEditValRemorque = QtGui.QLineEdit(self.frame_3)
        self.lineEditValRemorque.setObjectName(_fromUtf8("lineEditValRemorque"))
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditValRemorque)
        self.gridLayout_3.addLayout(self.formLayout_13, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 4, 1, 1, 2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBoxInflammable = QtGui.QCheckBox(self.frame_5)
        self.checkBoxInflammable.setTristate(False)
        self.checkBoxInflammable.setObjectName(_fromUtf8("checkBoxInflammable"))
        self.verticalLayout_3.addWidget(self.checkBoxInflammable)
        self.checkBoxCarteRose = QtGui.QCheckBox(self.frame_5)
        self.checkBoxCarteRose.setObjectName(_fromUtf8("checkBoxCarteRose"))
        self.verticalLayout_3.addWidget(self.checkBoxCarteRose)
        self.checkBoxVehiculeActif = QtGui.QCheckBox(self.frame_5)
        self.checkBoxVehiculeActif.setObjectName(_fromUtf8("checkBoxVehiculeActif"))
        self.verticalLayout_3.addWidget(self.checkBoxVehiculeActif)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 3, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.gridLayout_7.addWidget(self.frame_5, 1, 1, 1, 1)
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.comboBox_8 = QtGui.QComboBox(self.frame_6)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.gridLayout_6.addWidget(self.comboBox_8, 0, 0, 1, 1)
        self.formLayout_14 = QtGui.QFormLayout()
        self.formLayout_14.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_14.setObjectName(_fromUtf8("formLayout_14"))
        self.labelNatMouv = QtGui.QLabel(self.frame_6)
        self.labelNatMouv.setObjectName(_fromUtf8("labelNatMouv"))
        self.formLayout_14.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelNatMouv)
        self.comboBoxNatMouv = QtGui.QComboBox(self.frame_6)
        self.comboBoxNatMouv.setObjectName(_fromUtf8("comboBoxNatMouv"))
        self.formLayout_14.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxNatMouv)
        self.gridLayout_6.addLayout(self.formLayout_14, 0, 1, 1, 2)
        self.formLayout_15 = QtGui.QFormLayout()
        self.formLayout_15.setObjectName(_fromUtf8("formLayout_15"))
        self.labelRedacteur = QtGui.QLabel(self.frame_6)
        self.labelRedacteur.setObjectName(_fromUtf8("labelRedacteur"))
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelRedacteur)
        self.labelBareme = QtGui.QLabel(self.frame_6)
        self.labelBareme.setObjectName(_fromUtf8("labelBareme"))
        self.formLayout_15.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelBareme)
        self.comboBoxRedacteur = QtGui.QComboBox(self.frame_6)
        self.comboBoxRedacteur.setObjectName(_fromUtf8("comboBoxRedacteur"))
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxRedacteur)
        self.comboBoxBareme = QtGui.QComboBox(self.frame_6)
        self.comboBoxBareme.setObjectName(_fromUtf8("comboBoxBareme"))
        self.formLayout_15.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxBareme)
        self.gridLayout_6.addLayout(self.formLayout_15, 1, 0, 1, 2)
        self.formLayout_16 = QtGui.QFormLayout()
        self.formLayout_16.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_16.setObjectName(_fromUtf8("formLayout_16"))
        self.labelDateEmission = QtGui.QLabel(self.frame_6)
        self.labelDateEmission.setObjectName(_fromUtf8("labelDateEmission"))
        self.formLayout_16.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelDateEmission)
        self.dateEdit_8 = QtGui.QDateEdit(self.frame_6)
        self.dateEdit_8.setObjectName(_fromUtf8("dateEdit_8"))
        self.formLayout_16.setWidget(0, QtGui.QFormLayout.FieldRole, self.dateEdit_8)
        self.labelDateEffet = QtGui.QLabel(self.frame_6)
        self.labelDateEffet.setObjectName(_fromUtf8("labelDateEffet"))
        self.formLayout_16.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelDateEffet)
        self.dateEdit_9 = QtGui.QDateEdit(self.frame_6)
        self.dateEdit_9.setObjectName(_fromUtf8("dateEdit_9"))
        self.formLayout_16.setWidget(1, QtGui.QFormLayout.FieldRole, self.dateEdit_9)
        self.labelDateExpiration = QtGui.QLabel(self.frame_6)
        self.labelDateExpiration.setObjectName(_fromUtf8("labelDateExpiration"))
        self.formLayout_16.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelDateExpiration)
        self.dateEdit_10 = QtGui.QDateEdit(self.frame_6)
        self.dateEdit_10.setObjectName(_fromUtf8("dateEdit_10"))
        self.formLayout_16.setWidget(2, QtGui.QFormLayout.FieldRole, self.dateEdit_10)
        self.labelDuree = QtGui.QLabel(self.frame_6)
        self.labelDuree.setObjectName(_fromUtf8("labelDuree"))
        self.formLayout_16.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelDuree)
        self.lineEditDuree = QtGui.QLineEdit(self.frame_6)
        self.lineEditDuree.setObjectName(_fromUtf8("lineEditDuree"))
        self.formLayout_16.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditDuree)
        self.labelTauxPeriode = QtGui.QLabel(self.frame_6)
        self.labelTauxPeriode.setObjectName(_fromUtf8("labelTauxPeriode"))
        self.formLayout_16.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelTauxPeriode)
        self.lineEditTauxPeriode = QtGui.QLineEdit(self.frame_6)
        self.lineEditTauxPeriode.setObjectName(_fromUtf8("lineEditTauxPeriode"))
        self.formLayout_16.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditTauxPeriode)
        self.labelPrimeAnnuelle = QtGui.QLabel(self.frame_6)
        self.labelPrimeAnnuelle.setObjectName(_fromUtf8("labelPrimeAnnuelle"))
        self.formLayout_16.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelPrimeAnnuelle)
        self.lineEditPrimeAnnuelle = QtGui.QLineEdit(self.frame_6)
        self.lineEditPrimeAnnuelle.setObjectName(_fromUtf8("lineEditPrimeAnnuelle"))
        self.formLayout_16.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEditPrimeAnnuelle)
        self.labelPrimePeriode = QtGui.QLabel(self.frame_6)
        self.labelPrimePeriode.setObjectName(_fromUtf8("labelPrimePeriode"))
        self.formLayout_16.setWidget(6, QtGui.QFormLayout.LabelRole, self.labelPrimePeriode)
        self.lineEditPrimePeriode = QtGui.QLineEdit(self.frame_6)
        self.lineEditPrimePeriode.setObjectName(_fromUtf8("lineEditPrimePeriode"))
        self.formLayout_16.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEditPrimePeriode)
        self.labelRemise = QtGui.QLabel(self.frame_6)
        self.labelRemise.setObjectName(_fromUtf8("labelRemise"))
        self.formLayout_16.setWidget(7, QtGui.QFormLayout.LabelRole, self.labelRemise)
        self.lineEditRemise = QtGui.QLineEdit(self.frame_6)
        self.lineEditRemise.setObjectName(_fromUtf8("lineEditRemise"))
        self.formLayout_16.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEditRemise)
        self.labelPrimeNette = QtGui.QLabel(self.frame_6)
        self.labelPrimeNette.setObjectName(_fromUtf8("labelPrimeNette"))
        self.formLayout_16.setWidget(8, QtGui.QFormLayout.LabelRole, self.labelPrimeNette)
        self.lineEditPrimeNette = QtGui.QLineEdit(self.frame_6)
        self.lineEditPrimeNette.setObjectName(_fromUtf8("lineEditPrimeNette"))
        self.formLayout_16.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEditPrimeNette)
        self.labelRistourne = QtGui.QLabel(self.frame_6)
        self.labelRistourne.setObjectName(_fromUtf8("labelRistourne"))
        self.formLayout_16.setWidget(9, QtGui.QFormLayout.LabelRole, self.labelRistourne)
        self.lineEditRistourne = QtGui.QLineEdit(self.frame_6)
        self.lineEditRistourne.setObjectName(_fromUtf8("lineEditRistourne"))
        self.formLayout_16.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEditRistourne)
        self.labelAccessoires = QtGui.QLabel(self.frame_6)
        self.labelAccessoires.setObjectName(_fromUtf8("labelAccessoires"))
        self.formLayout_16.setWidget(10, QtGui.QFormLayout.LabelRole, self.labelAccessoires)
        self.lineEditAccessoires = QtGui.QLineEdit(self.frame_6)
        self.lineEditAccessoires.setObjectName(_fromUtf8("lineEditAccessoires"))
        self.formLayout_16.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEditAccessoires)
        self.labelFichierCentral = QtGui.QLabel(self.frame_6)
        self.labelFichierCentral.setObjectName(_fromUtf8("labelFichierCentral"))
        self.formLayout_16.setWidget(11, QtGui.QFormLayout.LabelRole, self.labelFichierCentral)
        self.lineEditFichierCentral = QtGui.QLineEdit(self.frame_6)
        self.lineEditFichierCentral.setObjectName(_fromUtf8("lineEditFichierCentral"))
        self.formLayout_16.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineEditFichierCentral)
        self.labelTVA = QtGui.QLabel(self.frame_6)
        self.labelTVA.setObjectName(_fromUtf8("labelTVA"))
        self.formLayout_16.setWidget(12, QtGui.QFormLayout.LabelRole, self.labelTVA)
        self.lineEditTVA = QtGui.QLineEdit(self.frame_6)
        self.lineEditTVA.setObjectName(_fromUtf8("lineEditTVA"))
        self.formLayout_16.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineEditTVA)
        self.labelCartesRoses = QtGui.QLabel(self.frame_6)
        self.labelCartesRoses.setObjectName(_fromUtf8("labelCartesRoses"))
        self.formLayout_16.setWidget(13, QtGui.QFormLayout.LabelRole, self.labelCartesRoses)
        self.lineEditCartesRoses = QtGui.QLineEdit(self.frame_6)
        self.lineEditCartesRoses.setObjectName(_fromUtf8("lineEditCartesRoses"))
        self.formLayout_16.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineEditCartesRoses)
        self.labelAutresTaxes = QtGui.QLabel(self.frame_6)
        self.labelAutresTaxes.setObjectName(_fromUtf8("labelAutresTaxes"))
        self.formLayout_16.setWidget(14, QtGui.QFormLayout.LabelRole, self.labelAutresTaxes)
        self.lineEditAutresTaxes = QtGui.QLineEdit(self.frame_6)
        self.lineEditAutresTaxes.setObjectName(_fromUtf8("lineEditAutresTaxes"))
        self.formLayout_16.setWidget(14, QtGui.QFormLayout.FieldRole, self.lineEditAutresTaxes)
        self.labelAutresFrais = QtGui.QLabel(self.frame_6)
        self.labelAutresFrais.setObjectName(_fromUtf8("labelAutresFrais"))
        self.formLayout_16.setWidget(15, QtGui.QFormLayout.LabelRole, self.labelAutresFrais)
        self.lineEditAutresFrais = QtGui.QLineEdit(self.frame_6)
        self.lineEditAutresFrais.setObjectName(_fromUtf8("lineEditAutresFrais"))
        self.formLayout_16.setWidget(15, QtGui.QFormLayout.FieldRole, self.lineEditAutresFrais)
        self.labelPrimeTTC = QtGui.QLabel(self.frame_6)
        self.labelPrimeTTC.setObjectName(_fromUtf8("labelPrimeTTC"))
        self.formLayout_16.setWidget(16, QtGui.QFormLayout.LabelRole, self.labelPrimeTTC)
        self.lineEditPrimeTTC = QtGui.QLineEdit(self.frame_6)
        self.lineEditPrimeTTC.setObjectName(_fromUtf8("lineEditPrimeTTC"))
        self.formLayout_16.setWidget(16, QtGui.QFormLayout.FieldRole, self.lineEditPrimeTTC)
        self.gridLayout_6.addLayout(self.formLayout_16, 1, 2, 5, 1)
        self.groupBox = QtGui.QGroupBox(self.frame_6)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_17 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_17.setObjectName(_fromUtf8("formLayout_17"))
        self.checkBoxG01 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG01.setObjectName(_fromUtf8("checkBoxG01"))
        self.formLayout_17.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBoxG01)
        self.checkBoxG02 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG02.setObjectName(_fromUtf8("checkBoxG02"))
        self.formLayout_17.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBoxG02)
        self.checkBoxG03 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG03.setObjectName(_fromUtf8("checkBoxG03"))
        self.formLayout_17.setWidget(2, QtGui.QFormLayout.LabelRole, self.checkBoxG03)
        self.checkBoxG04 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG04.setObjectName(_fromUtf8("checkBoxG04"))
        self.formLayout_17.setWidget(3, QtGui.QFormLayout.LabelRole, self.checkBoxG04)
        self.checkBoxG05 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG05.setObjectName(_fromUtf8("checkBoxG05"))
        self.formLayout_17.setWidget(4, QtGui.QFormLayout.LabelRole, self.checkBoxG05)
        self.checkBoxG06 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG06.setObjectName(_fromUtf8("checkBoxG06"))
        self.formLayout_17.setWidget(5, QtGui.QFormLayout.LabelRole, self.checkBoxG06)
        self.checkBoxG07 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG07.setObjectName(_fromUtf8("checkBoxG07"))
        self.formLayout_17.setWidget(6, QtGui.QFormLayout.LabelRole, self.checkBoxG07)
        self.checkBoxG08 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG08.setObjectName(_fromUtf8("checkBoxG08"))
        self.formLayout_17.setWidget(7, QtGui.QFormLayout.LabelRole, self.checkBoxG08)
        self.checkBoxG09 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG09.setObjectName(_fromUtf8("checkBoxG09"))
        self.formLayout_17.setWidget(8, QtGui.QFormLayout.LabelRole, self.checkBoxG09)
        self.checkBoxG10 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG10.setObjectName(_fromUtf8("checkBoxG10"))
        self.formLayout_17.setWidget(9, QtGui.QFormLayout.LabelRole, self.checkBoxG10)
        self.checkBoxG11 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG11.setObjectName(_fromUtf8("checkBoxG11"))
        self.formLayout_17.setWidget(10, QtGui.QFormLayout.LabelRole, self.checkBoxG11)
        self.checkBoxG12 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG12.setObjectName(_fromUtf8("checkBoxG12"))
        self.formLayout_17.setWidget(11, QtGui.QFormLayout.LabelRole, self.checkBoxG12)
        self.checkBoxG13 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG13.setObjectName(_fromUtf8("checkBoxG13"))
        self.formLayout_17.setWidget(0, QtGui.QFormLayout.FieldRole, self.checkBoxG13)
        self.checkBoxG14 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG14.setObjectName(_fromUtf8("checkBoxG14"))
        self.formLayout_17.setWidget(1, QtGui.QFormLayout.FieldRole, self.checkBoxG14)
        self.checkBoxG15 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG15.setObjectName(_fromUtf8("checkBoxG15"))
        self.formLayout_17.setWidget(2, QtGui.QFormLayout.FieldRole, self.checkBoxG15)
        self.checkBoxG16 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG16.setObjectName(_fromUtf8("checkBoxG16"))
        self.formLayout_17.setWidget(3, QtGui.QFormLayout.FieldRole, self.checkBoxG16)
        self.checkBoxG17 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG17.setObjectName(_fromUtf8("checkBoxG17"))
        self.formLayout_17.setWidget(4, QtGui.QFormLayout.FieldRole, self.checkBoxG17)
        self.checkBoxG18 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG18.setObjectName(_fromUtf8("checkBoxG18"))
        self.formLayout_17.setWidget(5, QtGui.QFormLayout.FieldRole, self.checkBoxG18)
        self.checkBoxG19 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG19.setObjectName(_fromUtf8("checkBoxG19"))
        self.formLayout_17.setWidget(6, QtGui.QFormLayout.FieldRole, self.checkBoxG19)
        self.checkBoxG20 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG20.setObjectName(_fromUtf8("checkBoxG20"))
        self.formLayout_17.setWidget(7, QtGui.QFormLayout.FieldRole, self.checkBoxG20)
        self.checkBoxG21 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG21.setObjectName(_fromUtf8("checkBoxG21"))
        self.formLayout_17.setWidget(8, QtGui.QFormLayout.FieldRole, self.checkBoxG21)
        self.checkBoxG22 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG22.setObjectName(_fromUtf8("checkBoxG22"))
        self.formLayout_17.setWidget(9, QtGui.QFormLayout.FieldRole, self.checkBoxG22)
        self.checkBoxG23 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG23.setObjectName(_fromUtf8("checkBoxG23"))
        self.formLayout_17.setWidget(10, QtGui.QFormLayout.FieldRole, self.checkBoxG23)
        self.checkBoxG24 = QtGui.QCheckBox(self.groupBox)
        self.checkBoxG24.setObjectName(_fromUtf8("checkBoxG24"))
        self.formLayout_17.setWidget(11, QtGui.QFormLayout.FieldRole, self.checkBoxG24)
        self.gridLayout_6.addWidget(self.groupBox, 2, 0, 1, 2)
        self.toolButtonGarantiesDetaillees = QtGui.QToolButton(self.frame_6)
        self.toolButtonGarantiesDetaillees.setObjectName(_fromUtf8("toolButtonGarantiesDetaillees"))
        self.gridLayout_6.addWidget(self.toolButtonGarantiesDetaillees, 3, 0, 1, 2)
        self.toolButtonPaiementsDetailles = QtGui.QToolButton(self.frame_6)
        self.toolButtonPaiementsDetailles.setObjectName(_fromUtf8("toolButtonPaiementsDetailles"))
        self.gridLayout_6.addWidget(self.toolButtonPaiementsDetailles, 4, 0, 1, 2)
        self.frame_9 = QtGui.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.labelDebits = QtGui.QLabel(self.frame_9)
        self.labelDebits.setObjectName(_fromUtf8("labelDebits"))
        self.gridLayout_5.addWidget(self.labelDebits, 0, 0, 1, 1)
        self.labelRistournes = QtGui.QLabel(self.frame_9)
        self.labelRistournes.setObjectName(_fromUtf8("labelRistournes"))
        self.gridLayout_5.addWidget(self.labelRistournes, 0, 1, 1, 1)
        self.labelComptant = QtGui.QLabel(self.frame_9)
        self.labelComptant.setObjectName(_fromUtf8("labelComptant"))
        self.gridLayout_5.addWidget(self.labelComptant, 0, 2, 1, 1)
        self.lineEditDebits = QtGui.QLineEdit(self.frame_9)
        self.lineEditDebits.setObjectName(_fromUtf8("lineEditDebits"))
        self.gridLayout_5.addWidget(self.lineEditDebits, 1, 0, 1, 1)
        self.lineEditRistournes = QtGui.QLineEdit(self.frame_9)
        self.lineEditRistournes.setObjectName(_fromUtf8("lineEditRistournes"))
        self.gridLayout_5.addWidget(self.lineEditRistournes, 1, 1, 1, 1)
        self.lineEditComptant = QtGui.QLineEdit(self.frame_9)
        self.lineEditComptant.setObjectName(_fromUtf8("lineEditComptant"))
        self.gridLayout_5.addWidget(self.lineEditComptant, 1, 2, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_5)
        self.gridLayout_6.addWidget(self.frame_9, 5, 0, 1, 2)
        self.groupBox.raise_()
        self.toolButtonGarantiesDetaillees.raise_()
        self.toolButtonPaiementsDetailles.raise_()
        self.comboBox_8.raise_()
        self.frame_9.raise_()
        self.gridLayout_7.addWidget(self.frame_6, 1, 2, 1, 1)
        Emissions.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Emissions)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Emissions.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(Emissions)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1375, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_Fichier = QtGui.QMenu(self.menuBar)
        self.menu_Fichier.setObjectName(_fromUtf8("menu_Fichier"))
        self.menu_Edition = QtGui.QMenu(self.menuBar)
        self.menu_Edition.setObjectName(_fromUtf8("menu_Edition"))
        self.menu_Traitements = QtGui.QMenu(self.menuBar)
        self.menu_Traitements.setObjectName(_fromUtf8("menu_Traitements"))
        Emissions.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(Emissions)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        Emissions.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionImporter_les_Donnees = QtGui.QAction(Emissions)
        self.actionImporter_les_Donnees.setObjectName(_fromUtf8("actionImporter_les_Donnees"))
        self.actionExporter_les_Donnees = QtGui.QAction(Emissions)
        self.actionExporter_les_Donnees.setObjectName(_fromUtf8("actionExporter_les_Donnees"))
        self.actionDemande_modification_Parametrage = QtGui.QAction(Emissions)
        self.actionDemande_modification_Parametrage.setObjectName(_fromUtf8("actionDemande_modification_Parametrage"))
        self.actionQuitter = QtGui.QAction(Emissions)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.actionGestionnaire_Portefeuille = QtGui.QAction(Emissions)
        self.actionGestionnaire_Portefeuille.setObjectName(_fromUtf8("actionGestionnaire_Portefeuille"))
        self.actionMouvement_Emission = QtGui.QAction(Emissions)
        self.actionMouvement_Emission.setObjectName(_fromUtf8("actionMouvement_Emission"))
        self.actionDeclaration_Sinistre = QtGui.QAction(Emissions)
        self.actionDeclaration_Sinistre.setObjectName(_fromUtf8("actionDeclaration_Sinistre"))
        self.actionNouveau_2 = QtGui.QAction(Emissions)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-new.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNouveau_2.setIcon(icon)
        self.actionNouveau_2.setObjectName(_fromUtf8("actionNouveau_2"))
        self.actionEnregistrer = QtGui.QAction(Emissions)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-save.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnregistrer.setIcon(icon1)
        self.actionEnregistrer.setObjectName(_fromUtf8("actionEnregistrer"))
        self.actionImprimer_les_pieces_du_Contrat = QtGui.QAction(Emissions)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Imprimer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImprimer_les_pieces_du_Contrat.setIcon(icon2)
        self.actionImprimer_les_pieces_du_Contrat.setObjectName(_fromUtf8("actionImprimer_les_pieces_du_Contrat"))
        self.actionImprimer_les_Attestations = QtGui.QAction(Emissions)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/ImprimerAttestationsAssurance.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImprimer_les_Attestations.setIcon(icon3)
        self.actionImprimer_les_Attestations.setObjectName(_fromUtf8("actionImprimer_les_Attestations"))
        self.actionFermer = QtGui.QAction(Emissions)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/system-log-out.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFermer.setIcon(icon4)
        self.actionFermer.setObjectName(_fromUtf8("actionFermer"))
        self.actionAnnuler = QtGui.QAction(Emissions)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-undo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnnuler.setIcon(icon5)
        self.actionAnnuler.setObjectName(_fromUtf8("actionAnnuler"))
        self.actionRefaire = QtGui.QAction(Emissions)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-redo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefaire.setIcon(icon6)
        self.actionRefaire.setObjectName(_fromUtf8("actionRefaire"))
        self.actionPremier = QtGui.QAction(Emissions)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-first.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPremier.setIcon(icon7)
        self.actionPremier.setObjectName(_fromUtf8("actionPremier"))
        self.actionPrecedent = QtGui.QAction(Emissions)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-previous.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrecedent.setIcon(icon8)
        self.actionPrecedent.setObjectName(_fromUtf8("actionPrecedent"))
        self.actionSuivant = QtGui.QAction(Emissions)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-next.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSuivant.setIcon(icon9)
        self.actionSuivant.setObjectName(_fromUtf8("actionSuivant"))
        self.actionDernier = QtGui.QAction(Emissions)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-last.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDernier.setIcon(icon10)
        self.actionDernier.setObjectName(_fromUtf8("actionDernier"))
        self.actionDetails_Garanties_souscrites = QtGui.QAction(Emissions)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/PannierGaranties.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDetails_Garanties_souscrites.setIcon(icon11)
        self.actionDetails_Garanties_souscrites.setObjectName(_fromUtf8("actionDetails_Garanties_souscrites"))
        self.actionDetails_Paiements = QtGui.QAction(Emissions)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/EncaissementPrimes.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDetails_Paiements.setIcon(icon12)
        self.actionDetails_Paiements.setObjectName(_fromUtf8("actionDetails_Paiements"))
        self.menu_Fichier.addAction(self.actionNouveau_2)
        self.menu_Fichier.addAction(self.actionEnregistrer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.actionImprimer_les_pieces_du_Contrat)
        self.menu_Fichier.addAction(self.actionImprimer_les_Attestations)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.actionFermer)
        self.menu_Edition.addAction(self.actionAnnuler)
        self.menu_Edition.addAction(self.actionRefaire)
        self.menu_Edition.addSeparator()
        self.menu_Edition.addAction(self.actionPremier)
        self.menu_Edition.addAction(self.actionPrecedent)
        self.menu_Edition.addAction(self.actionSuivant)
        self.menu_Edition.addAction(self.actionDernier)
        self.menu_Traitements.addAction(self.actionDetails_Garanties_souscrites)
        self.menu_Traitements.addAction(self.actionDetails_Paiements)
        self.menuBar.addAction(self.menu_Fichier.menuAction())
        self.menuBar.addAction(self.menu_Edition.menuAction())
        self.menuBar.addAction(self.menu_Traitements.menuAction())
        self.toolBar.addAction(self.actionNouveau_2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPremier)
        self.toolBar.addAction(self.actionPrecedent)
        self.toolBar.addAction(self.actionSuivant)
        self.toolBar.addAction(self.actionDernier)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRefaire)
        self.toolBar.addAction(self.actionAnnuler)
        self.toolBar.addAction(self.actionEnregistrer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDetails_Garanties_souscrites)
        self.toolBar.addAction(self.actionDetails_Paiements)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionImprimer_les_pieces_du_Contrat)
        self.toolBar.addAction(self.actionImprimer_les_Attestations)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFermer)

        self.retranslateUi(Emissions)
        QtCore.QMetaObject.connectSlotsByName(Emissions)

    def retranslateUi(self, Emissions):
        Emissions.setWindowTitle(_translate("Emissions", "Emissions", None))
        self.labelNumClient.setText(_translate("Emissions", "Numero Client", None))
        self.labelPrenom.setText(_translate("Emissions", "Prenom", None))
        self.labelNom.setText(_translate("Emissions", "Nom", None))
        self.labelProfession.setText(_translate("Emissions", "Profession", None))
        self.labelCivilite.setText(_translate("Emissions", "Civilite", None))
        self.labelLocalisation.setText(_translate("Emissions", "Localisation", None))
        self.labelBP.setText(_translate("Emissions", "Boite Postale", None))
        self.labelVille.setText(_translate("Emissions", "Ville", None))
        self.labelAdresse.setText(_translate("Emissions", "Adresse", None))
        self.labelSociete.setText(_translate("Emissions", "Societe", None))
        self.labelPosteOccupe.setText(_translate("Emissions", "Poste occupe", None))
        self.labelDepartement.setText(_translate("Emissions", "Departement", None))
        self.labelZoneTarif.setText(_translate("Emissions", "Zone Tarification", None))
        self.labelTelBureau.setText(_translate("Emissions", "Telephone Bureau", None))
        self.labelTelPortable.setText(_translate("Emissions", "Telephone Portable", None))
        self.labelFax.setText(_translate("Emissions", "N. Fax", None))
        self.labelMail.setText(_translate("Emissions", "E-mail", None))
        self.labelEntreePortefeuille.setText(_translate("Emissions", "Entree Portefeuille", None))
        self.labelPaiement.setText(_translate("Emissions", "Paiements", None))
        self.labelSolde.setText(_translate("Emissions", "Solde", None))
        self.labelEmission.setText(_translate("Emissions", "Emissions", None))
        self.toolButtonConditionsParticulieres.setText(_translate("Emissions", "Conditions Particulieres", None))
        self.toolButtonAttestationAssurance.setText(_translate("Emissions", "Attestations d\'Assurance", None))
        self.labelCie.setText(_translate("Emissions", "Compagnie", None))
        self.labelPoliceAgence.setText(_translate("Emissions", "Police Agence", None))
        self.labelResAgence.setText(_translate("Emissions", "Reseau/Agence", None))
        self.labelGestionnaire.setText(_translate("Emissions", "Gestionnaire", None))
        self.labelBranche.setText(_translate("Emissions", "Branche", None))
        self.labelPoliceCie.setText(_translate("Emissions", "Police Cie", None))
        self.textEdit.setHtml(_translate("Emissions", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Commentaires ou Memo</p></body></html>", None))
        self.labelFlotte.setText(_translate("Emissions", "Flotte", None))
        self.labelCreeeLe.setText(_translate("Emissions", "Creee le", None))
        self.labelDebutAnnuel.setText(_translate("Emissions", "Debut Annuel", None))
        self.labelTermeAnnuel.setText(_translate("Emissions", "Terme Annuel", None))
        self.labelValide.setText(_translate("Emissions", "Valide (Oui/Non ?)", None))
        self.labelBonusMalus.setText(_translate("Emissions", "Bonus/Malus", None))
        self.labelReduction.setText(_translate("Emissions", "Reduction", None))
        self.labelValAnnuelle.setText(_translate("Emissions", "Valeur Annuelle", None))
        self.labelNomAssure.setText(_translate("Emissions", "Nom Assure", None))
        self.labelAdresseAssure.setText(_translate("Emissions", "Adresse Assure", None))
        self.labelNomConducteur.setText(_translate("Emissions", "Nom Conducteur", None))
        self.labelNumChassi.setText(_translate("Emissions", "Numero Chassis", None))
        self.labelImmatriculation_2.setText(_translate("Emissions", "Immatriculation", None))
        self.labelDatePremMC.setText(_translate("Emissions", "Date 1ere MC", None))
        self.labelValNeuve.setText(_translate("Emissions", "Valeur Neuve", None))
        self.labelValVenale.setText(_translate("Emissions", "Valeur Venale", None))
        self.labelValAccessoire.setText(_translate("Emissions", "Valeur Accessoire", None))
        self.labelNumPermis.setText(_translate("Emissions", "Numero Permis", None))
        self.labelCatPermis.setText(_translate("Emissions", "Categorie Permis", None))
        self.labelDateObtPermis.setText(_translate("Emissions", "Date obt. Permis", None))
        self.labelValiditePermis.setText(_translate("Emissions", "Validite Permis", None))
        self.labelNumCapa.setText(_translate("Emissions", "Numero Capacite", None))
        self.labelValiditeCapa.setText(_translate("Emissions", "Validite Capacite", None))
        self.labelMarque.setText(_translate("Emissions", "Marque", None))
        self.labelModelType.setText(_translate("Emissions", "Modele/Type", None))
        self.labelGenre.setText(_translate("Emissions", "Genre", None))
        self.labelNbPlaces.setText(_translate("Emissions", "Nombre Places", None))
        self.labelPuissance.setText(_translate("Emissions", "Puissance", None))
        self.labelEnergie.setText(_translate("Emissions", "Energie", None))
        self.labelZoneTarification.setText(_translate("Emissions", "Zone Tarification", None))
        self.labelClassifPermis.setText(_translate("Emissions", "Classif. Permis", None))
        self.labelCatSocioPro.setText(_translate("Emissions", "Cat. SocioProfess", None))
        self.checkBoxAttelageRemorque.setText(_translate("Emissions", "Attelage Remorque ?", None))
        self.labelMarqueAtRem.setText(_translate("Emissions", "Marque", None))
        self.labelTypeAtRem.setText(_translate("Emissions", "Type", None))
        self.labelImmatriculation.setText(_translate("Emissions", "Immatriculation", None))
        self.labelValRemorque.setText(_translate("Emissions", "Valeur Remorque", None))
        self.checkBoxInflammable.setText(_translate("Emissions", "Matiere Inflammable ?", None))
        self.checkBoxCarteRose.setText(_translate("Emissions", "Carte Rose ?", None))
        self.checkBoxVehiculeActif.setText(_translate("Emissions", "Vehicule Actif ?", None))
        self.labelNatMouv.setText(_translate("Emissions", "Nature Mouvement", None))
        self.labelRedacteur.setText(_translate("Emissions", "Redacteur", None))
        self.labelBareme.setText(_translate("Emissions", "Bareme", None))
        self.labelDateEmission.setText(_translate("Emissions", "Date Emission", None))
        self.labelDateEffet.setText(_translate("Emissions", "Date Effet", None))
        self.labelDateExpiration.setText(_translate("Emissions", "Date Expiration", None))
        self.labelDuree.setText(_translate("Emissions", "Duree", None))
        self.labelTauxPeriode.setText(_translate("Emissions", "Taux Periode", None))
        self.labelPrimeAnnuelle.setText(_translate("Emissions", "Prime Annuelle", None))
        self.labelPrimePeriode.setText(_translate("Emissions", "Prime Periode", None))
        self.labelRemise.setText(_translate("Emissions", "Remise", None))
        self.labelPrimeNette.setText(_translate("Emissions", "Prime Nette", None))
        self.labelRistourne.setText(_translate("Emissions", "Ristourne", None))
        self.labelAccessoires.setText(_translate("Emissions", "Accessoires", None))
        self.labelFichierCentral.setText(_translate("Emissions", "Fichier Central", None))
        self.labelTVA.setText(_translate("Emissions", "TVA", None))
        self.labelCartesRoses.setText(_translate("Emissions", "Cartes Roses", None))
        self.labelAutresTaxes.setText(_translate("Emissions", "Autres Taxes", None))
        self.labelAutresFrais.setText(_translate("Emissions", "Autres Frais", None))
        self.labelPrimeTTC.setText(_translate("Emissions", "Prime TTC", None))
        self.groupBox.setTitle(_translate("Emissions", "Garanties", None))
        self.checkBoxG01.setText(_translate("Emissions", "G01", None))
        self.checkBoxG02.setText(_translate("Emissions", "G02", None))
        self.checkBoxG03.setText(_translate("Emissions", "G03", None))
        self.checkBoxG04.setText(_translate("Emissions", "G04", None))
        self.checkBoxG05.setText(_translate("Emissions", "G05", None))
        self.checkBoxG06.setText(_translate("Emissions", "G06", None))
        self.checkBoxG07.setText(_translate("Emissions", "G07", None))
        self.checkBoxG08.setText(_translate("Emissions", "G08", None))
        self.checkBoxG09.setText(_translate("Emissions", "G09", None))
        self.checkBoxG10.setText(_translate("Emissions", "G10", None))
        self.checkBoxG11.setText(_translate("Emissions", "G11", None))
        self.checkBoxG12.setText(_translate("Emissions", "G12", None))
        self.checkBoxG13.setText(_translate("Emissions", "G13", None))
        self.checkBoxG14.setText(_translate("Emissions", "G14", None))
        self.checkBoxG15.setText(_translate("Emissions", "G15", None))
        self.checkBoxG16.setText(_translate("Emissions", "G16", None))
        self.checkBoxG17.setText(_translate("Emissions", "G17", None))
        self.checkBoxG18.setText(_translate("Emissions", "G18", None))
        self.checkBoxG19.setText(_translate("Emissions", "G19", None))
        self.checkBoxG20.setText(_translate("Emissions", "G20", None))
        self.checkBoxG21.setText(_translate("Emissions", "G21", None))
        self.checkBoxG22.setText(_translate("Emissions", "G22", None))
        self.checkBoxG23.setText(_translate("Emissions", "G23", None))
        self.checkBoxG24.setText(_translate("Emissions", "G24", None))
        self.toolButtonGarantiesDetaillees.setText(_translate("Emissions", "Garanties Detaillees", None))
        self.toolButtonPaiementsDetailles.setText(_translate("Emissions", "Paiements Detailles", None))
        self.labelDebits.setText(_translate("Emissions", "Debits", None))
        self.labelRistournes.setText(_translate("Emissions", "Ristournes", None))
        self.labelComptant.setText(_translate("Emissions", "Comptant", None))
        self.menu_Fichier.setTitle(_translate("Emissions", "&Fichier", None))
        self.menu_Edition.setTitle(_translate("Emissions", "&Edition", None))
        self.menu_Traitements.setTitle(_translate("Emissions", "&Traitements", None))
        self.toolBar.setWindowTitle(_translate("Emissions", "toolBar", None))
        self.actionImporter_les_Donnees.setText(_translate("Emissions", "Importer les Donnees", None))
        self.actionExporter_les_Donnees.setText(_translate("Emissions", "Exporter les Donnees", None))
        self.actionDemande_modification_Parametrage.setText(_translate("Emissions", "Demande modification Parametrage", None))
        self.actionQuitter.setText(_translate("Emissions", "Quitter", None))
        self.actionGestionnaire_Portefeuille.setText(_translate("Emissions", "Gestionnaire Portefeuille", None))
        self.actionMouvement_Emission.setText(_translate("Emissions", "Mouvement Emission", None))
        self.actionDeclaration_Sinistre.setText(_translate("Emissions", "Declaration Sinistre", None))
        self.actionNouveau_2.setText(_translate("Emissions", "Nouveau", None))
        self.actionEnregistrer.setText(_translate("Emissions", "Enregistrer", None))
        self.actionImprimer_les_pieces_du_Contrat.setText(_translate("Emissions", "Imprimer les pieces du Contrat", None))
        self.actionImprimer_les_Attestations.setText(_translate("Emissions", "Imprimer les Attestations", None))
        self.actionFermer.setText(_translate("Emissions", "Fermer", None))
        self.actionAnnuler.setText(_translate("Emissions", "Annuler", None))
        self.actionRefaire.setText(_translate("Emissions", "Refaire", None))
        self.actionPremier.setText(_translate("Emissions", "Premier", None))
        self.actionPrecedent.setText(_translate("Emissions", "Precedent", None))
        self.actionSuivant.setText(_translate("Emissions", "Suivant", None))
        self.actionDernier.setText(_translate("Emissions", "Dernier", None))
        self.actionDetails_Garanties_souscrites.setText(_translate("Emissions", "Details Garanties souscrites", None))
        self.actionDetails_Paiements.setText(_translate("Emissions", "Details Paiements", None))

import ressources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Emissions = QtGui.QMainWindow()
    ui = Ui_Emissions()
    ui.setupUi(Emissions)
    Emissions.show()
    sys.exit(app.exec_())

