# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detailgaranties.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DetailGaranties(object):
    def setupUi(self, DetailGaranties):
        DetailGaranties.setObjectName(_fromUtf8("DetailGaranties"))
        DetailGaranties.setWindowModality(QtCore.Qt.ApplicationModal)
        DetailGaranties.resize(978, 608)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        DetailGaranties.setFont(font)
        self.centralwidget = QtGui.QWidget(DetailGaranties)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelDetailsGaranties = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelDetailsGaranties.setFont(font)
        self.labelDetailsGaranties.setObjectName(_fromUtf8("labelDetailsGaranties"))
        self.verticalLayout_2.addWidget(self.labelDetailsGaranties)
        self.detailGarantiesTableView = QtGui.QTableView(self.frame_3)
        self.detailGarantiesTableView.setMinimumSize(QtCore.QSize(400, 0))
        self.detailGarantiesTableView.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.detailGarantiesTableView.setFont(font)
        self.detailGarantiesTableView.setAlternatingRowColors(True)
        self.detailGarantiesTableView.setObjectName(_fromUtf8("detailGarantiesTableView"))
        self.verticalLayout_2.addWidget(self.detailGarantiesTableView)
        self.labelRecapPrimes = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelRecapPrimes.setFont(font)
        self.labelRecapPrimes.setObjectName(_fromUtf8("labelRecapPrimes"))
        self.verticalLayout_2.addWidget(self.labelRecapPrimes)
        self.recapPrimesTableView = QtGui.QTableView(self.frame_3)
        self.recapPrimesTableView.setMinimumSize(QtCore.QSize(400, 50))
        self.recapPrimesTableView.setMaximumSize(QtCore.QSize(500, 80))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.recapPrimesTableView.setFont(font)
        self.recapPrimesTableView.setAlternatingRowColors(True)
        self.recapPrimesTableView.setObjectName(_fromUtf8("recapPrimesTableView"))
        self.verticalLayout_2.addWidget(self.recapPrimesTableView)
        self.gridLayout_3.addWidget(self.frame_3, 0, 3, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(140, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_detail_prime = QtGui.QWidget()
        self.tab_detail_prime.setObjectName(_fromUtf8("tab_detail_prime"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_detail_prime)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame = QtGui.QFrame(self.tab_detail_prime)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.labelRistourne = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelRistourne.setFont(font)
        self.labelRistourne.setObjectName(_fromUtf8("labelRistourne"))
        self.gridLayout_4.addWidget(self.labelRistourne, 5, 0, 1, 1)
        self.remiseLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.remiseLineEdit.setFont(font)
        self.remiseLineEdit.setObjectName(_fromUtf8("remiseLineEdit"))
        self.gridLayout_4.addWidget(self.remiseLineEdit, 3, 1, 1, 1)
        self.tauxPeriodeLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.tauxPeriodeLineEdit.setFont(font)
        self.tauxPeriodeLineEdit.setObjectName(_fromUtf8("tauxPeriodeLineEdit"))
        self.gridLayout_4.addWidget(self.tauxPeriodeLineEdit, 0, 1, 1, 1)
        self.primNetLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.primNetLineEdit.setFont(font)
        self.primNetLineEdit.setObjectName(_fromUtf8("primNetLineEdit"))
        self.gridLayout_4.addWidget(self.primNetLineEdit, 4, 1, 1, 1)
        self.labelTauxPeriode = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelTauxPeriode.setFont(font)
        self.labelTauxPeriode.setObjectName(_fromUtf8("labelTauxPeriode"))
        self.gridLayout_4.addWidget(self.labelTauxPeriode, 0, 0, 1, 1)
        self.labelPrimeNette = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelPrimeNette.setFont(font)
        self.labelPrimeNette.setObjectName(_fromUtf8("labelPrimeNette"))
        self.gridLayout_4.addWidget(self.labelPrimeNette, 4, 0, 1, 1)
        self.primAnnuelLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.primAnnuelLineEdit.setFont(font)
        self.primAnnuelLineEdit.setObjectName(_fromUtf8("primAnnuelLineEdit"))
        self.gridLayout_4.addWidget(self.primAnnuelLineEdit, 1, 1, 1, 1)
        self.accessLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.accessLineEdit.setFont(font)
        self.accessLineEdit.setObjectName(_fromUtf8("accessLineEdit"))
        self.gridLayout_4.addWidget(self.accessLineEdit, 6, 1, 1, 1)
        self.labelAccessoires = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelAccessoires.setFont(font)
        self.labelAccessoires.setObjectName(_fromUtf8("labelAccessoires"))
        self.gridLayout_4.addWidget(self.labelAccessoires, 6, 0, 1, 1)
        self.labelRemise = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelRemise.setFont(font)
        self.labelRemise.setObjectName(_fromUtf8("labelRemise"))
        self.gridLayout_4.addWidget(self.labelRemise, 3, 0, 1, 1)
        self.labelFichierCentral = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelFichierCentral.setFont(font)
        self.labelFichierCentral.setObjectName(_fromUtf8("labelFichierCentral"))
        self.gridLayout_4.addWidget(self.labelFichierCentral, 7, 0, 1, 1)
        self.primttcLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.primttcLineEdit.setFont(font)
        self.primttcLineEdit.setObjectName(_fromUtf8("primttcLineEdit"))
        self.gridLayout_4.addWidget(self.primttcLineEdit, 12, 1, 1, 1)
        self.ristournLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.ristournLineEdit.setFont(font)
        self.ristournLineEdit.setObjectName(_fromUtf8("ristournLineEdit"))
        self.gridLayout_4.addWidget(self.ristournLineEdit, 5, 1, 1, 1)
        self.labelPrimeTTC = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelPrimeTTC.setFont(font)
        self.labelPrimeTTC.setObjectName(_fromUtf8("labelPrimeTTC"))
        self.gridLayout_4.addWidget(self.labelPrimeTTC, 12, 0, 1, 1)
        self.autrTaxLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.autrTaxLineEdit.setFont(font)
        self.autrTaxLineEdit.setObjectName(_fromUtf8("autrTaxLineEdit"))
        self.gridLayout_4.addWidget(self.autrTaxLineEdit, 10, 1, 1, 1)
        self.primPeriodLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.primPeriodLineEdit.setFont(font)
        self.primPeriodLineEdit.setObjectName(_fromUtf8("primPeriodLineEdit"))
        self.gridLayout_4.addWidget(self.primPeriodLineEdit, 2, 1, 1, 1)
        self.labelPrimeAnnuelle = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelPrimeAnnuelle.setFont(font)
        self.labelPrimeAnnuelle.setObjectName(_fromUtf8("labelPrimeAnnuelle"))
        self.gridLayout_4.addWidget(self.labelPrimeAnnuelle, 1, 0, 1, 1)
        self.labelAutresFrais = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelAutresFrais.setFont(font)
        self.labelAutresFrais.setObjectName(_fromUtf8("labelAutresFrais"))
        self.gridLayout_4.addWidget(self.labelAutresFrais, 11, 0, 1, 1)
        self.autrFraisLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.autrFraisLineEdit.setFont(font)
        self.autrFraisLineEdit.setObjectName(_fromUtf8("autrFraisLineEdit"))
        self.gridLayout_4.addWidget(self.autrFraisLineEdit, 11, 1, 1, 1)
        self.labelPrimePeriode = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelPrimePeriode.setFont(font)
        self.labelPrimePeriode.setObjectName(_fromUtf8("labelPrimePeriode"))
        self.gridLayout_4.addWidget(self.labelPrimePeriode, 2, 0, 1, 1)
        self.fichierCentralLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.fichierCentralLineEdit.setFont(font)
        self.fichierCentralLineEdit.setObjectName(_fromUtf8("fichierCentralLineEdit"))
        self.gridLayout_4.addWidget(self.fichierCentralLineEdit, 7, 1, 1, 1)
        self.cartRosLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.cartRosLineEdit.setFont(font)
        self.cartRosLineEdit.setObjectName(_fromUtf8("cartRosLineEdit"))
        self.gridLayout_4.addWidget(self.cartRosLineEdit, 9, 1, 1, 1)
        self.labelCartesRoses = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelCartesRoses.setFont(font)
        self.labelCartesRoses.setObjectName(_fromUtf8("labelCartesRoses"))
        self.gridLayout_4.addWidget(self.labelCartesRoses, 9, 0, 1, 1)
        self.labelTva = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelTva.setFont(font)
        self.labelTva.setObjectName(_fromUtf8("labelTva"))
        self.gridLayout_4.addWidget(self.labelTva, 8, 0, 1, 1)
        self.tvaLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.tvaLineEdit.setFont(font)
        self.tvaLineEdit.setObjectName(_fromUtf8("tvaLineEdit"))
        self.gridLayout_4.addWidget(self.tvaLineEdit, 8, 1, 1, 1)
        self.labelAutresTaxes = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.labelAutresTaxes.setFont(font)
        self.labelAutresTaxes.setObjectName(_fromUtf8("labelAutresTaxes"))
        self.gridLayout_4.addWidget(self.labelAutresTaxes, 10, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 13, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_detail_prime, _fromUtf8(""))
        self.tab_texte_avenant = QtGui.QWidget()
        self.tab_texte_avenant.setObjectName(_fromUtf8("tab_texte_avenant"))
        self.gridLayout = QtGui.QGridLayout(self.tab_texte_avenant)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textAvenantTextEdit = QtGui.QTextEdit(self.tab_texte_avenant)
        font = QtGui.QFont()
        font.setItalic(False)
        self.textAvenantTextEdit.setFont(font)
        self.textAvenantTextEdit.setObjectName(_fromUtf8("textAvenantTextEdit"))
        self.gridLayout.addWidget(self.textAvenantTextEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_texte_avenant, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.G01CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G01CheckBoxDetails.setFont(font)
        self.G01CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G01CheckBoxDetails.setObjectName(_fromUtf8("G01CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G01CheckBoxDetails)
        self.G02CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G02CheckBoxDetails.setFont(font)
        self.G02CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G02CheckBoxDetails.setObjectName(_fromUtf8("G02CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G02CheckBoxDetails)
        self.G03CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G03CheckBoxDetails.setFont(font)
        self.G03CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G03CheckBoxDetails.setObjectName(_fromUtf8("G03CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G03CheckBoxDetails)
        self.G04CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G04CheckBoxDetails.setFont(font)
        self.G04CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G04CheckBoxDetails.setObjectName(_fromUtf8("G04CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G04CheckBoxDetails)
        self.G05CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G05CheckBoxDetails.setFont(font)
        self.G05CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G05CheckBoxDetails.setObjectName(_fromUtf8("G05CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G05CheckBoxDetails)
        self.G06CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G06CheckBoxDetails.setFont(font)
        self.G06CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G06CheckBoxDetails.setObjectName(_fromUtf8("G06CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G06CheckBoxDetails)
        self.G07CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G07CheckBoxDetails.setFont(font)
        self.G07CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G07CheckBoxDetails.setObjectName(_fromUtf8("G07CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G07CheckBoxDetails)
        self.G08CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G08CheckBoxDetails.setFont(font)
        self.G08CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G08CheckBoxDetails.setObjectName(_fromUtf8("G08CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G08CheckBoxDetails)
        self.G09CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G09CheckBoxDetails.setFont(font)
        self.G09CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G09CheckBoxDetails.setObjectName(_fromUtf8("G09CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G09CheckBoxDetails)
        self.G10CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G10CheckBoxDetails.setFont(font)
        self.G10CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G10CheckBoxDetails.setObjectName(_fromUtf8("G10CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G10CheckBoxDetails)
        self.G11CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G11CheckBoxDetails.setFont(font)
        self.G11CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G11CheckBoxDetails.setObjectName(_fromUtf8("G11CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G11CheckBoxDetails)
        self.G12CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G12CheckBoxDetails.setFont(font)
        self.G12CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G12CheckBoxDetails.setObjectName(_fromUtf8("G12CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G12CheckBoxDetails)
        self.G13CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G13CheckBoxDetails.setFont(font)
        self.G13CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G13CheckBoxDetails.setObjectName(_fromUtf8("G13CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G13CheckBoxDetails)
        self.G14CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G14CheckBoxDetails.setFont(font)
        self.G14CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G14CheckBoxDetails.setObjectName(_fromUtf8("G14CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G14CheckBoxDetails)
        self.G15CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G15CheckBoxDetails.setFont(font)
        self.G15CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G15CheckBoxDetails.setObjectName(_fromUtf8("G15CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G15CheckBoxDetails)
        self.G16CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G16CheckBoxDetails.setFont(font)
        self.G16CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G16CheckBoxDetails.setObjectName(_fromUtf8("G16CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G16CheckBoxDetails)
        self.G17CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G17CheckBoxDetails.setFont(font)
        self.G17CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G17CheckBoxDetails.setObjectName(_fromUtf8("G17CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G17CheckBoxDetails)
        self.G18CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G18CheckBoxDetails.setFont(font)
        self.G18CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G18CheckBoxDetails.setObjectName(_fromUtf8("G18CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G18CheckBoxDetails)
        self.G19CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G19CheckBoxDetails.setFont(font)
        self.G19CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G19CheckBoxDetails.setObjectName(_fromUtf8("G19CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G19CheckBoxDetails)
        self.G20CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G20CheckBoxDetails.setFont(font)
        self.G20CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G20CheckBoxDetails.setObjectName(_fromUtf8("G20CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G20CheckBoxDetails)
        self.G21CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G21CheckBoxDetails.setFont(font)
        self.G21CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G21CheckBoxDetails.setObjectName(_fromUtf8("G21CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G21CheckBoxDetails)
        self.G22CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G22CheckBoxDetails.setFont(font)
        self.G22CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G22CheckBoxDetails.setObjectName(_fromUtf8("G22CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G22CheckBoxDetails)
        self.G23CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G23CheckBoxDetails.setFont(font)
        self.G23CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G23CheckBoxDetails.setObjectName(_fromUtf8("G23CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G23CheckBoxDetails)
        self.G24CheckBoxDetails = QtGui.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.G24CheckBoxDetails.setFont(font)
        self.G24CheckBoxDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.G24CheckBoxDetails.setObjectName(_fromUtf8("G24CheckBoxDetails"))
        self.verticalLayout.addWidget(self.G24CheckBoxDetails)
        self.gridLayout_3.addWidget(self.frame_2, 0, 2, 1, 1)
        self.listView = QtGui.QListView(self.centralwidget)
        self.listView.setMinimumSize(QtCore.QSize(60, 450))
        self.listView.setMaximumSize(QtCore.QSize(80, 600))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        self.listView.setFont(font)
        self.listView.setAlternatingRowColors(True)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.gridLayout_3.addWidget(self.listView, 0, 0, 1, 1)
        DetailGaranties.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DetailGaranties)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 978, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Fichier = QtGui.QMenu(self.menubar)
        self.menu_Fichier.setObjectName(_fromUtf8("menu_Fichier"))
        self.menu_Edition = QtGui.QMenu(self.menubar)
        self.menu_Edition.setObjectName(_fromUtf8("menu_Edition"))
        DetailGaranties.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DetailGaranties)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DetailGaranties.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(DetailGaranties)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        DetailGaranties.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fichierNouveau = QtGui.QAction(DetailGaranties)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-new.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierNouveau.setIcon(icon)
        self.fichierNouveau.setObjectName(_fromUtf8("fichierNouveau"))
        self.fichierEnregistrer = QtGui.QAction(DetailGaranties)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-save.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierEnregistrer.setIcon(icon1)
        self.fichierEnregistrer.setObjectName(_fromUtf8("fichierEnregistrer"))
        self.fichierImprimer = QtGui.QAction(DetailGaranties)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Imprimer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierImprimer.setIcon(icon2)
        self.fichierImprimer.setObjectName(_fromUtf8("fichierImprimer"))
        self.fichierFermer = QtGui.QAction(DetailGaranties)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/system-log-out.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierFermer.setIcon(icon3)
        self.fichierFermer.setObjectName(_fromUtf8("fichierFermer"))
        self.editionAnnuler = QtGui.QAction(DetailGaranties)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-undo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionAnnuler.setIcon(icon4)
        self.editionAnnuler.setObjectName(_fromUtf8("editionAnnuler"))
        self.editionRefaire = QtGui.QAction(DetailGaranties)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-redo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionRefaire.setIcon(icon5)
        self.editionRefaire.setObjectName(_fromUtf8("editionRefaire"))
        self.editionPremier = QtGui.QAction(DetailGaranties)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-first.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPremier.setIcon(icon6)
        self.editionPremier.setObjectName(_fromUtf8("editionPremier"))
        self.editionPrecedent = QtGui.QAction(DetailGaranties)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-previous.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPrecedent.setIcon(icon7)
        self.editionPrecedent.setObjectName(_fromUtf8("editionPrecedent"))
        self.editionSuivant = QtGui.QAction(DetailGaranties)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-next.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionSuivant.setIcon(icon8)
        self.editionSuivant.setObjectName(_fromUtf8("editionSuivant"))
        self.editionDernier = QtGui.QAction(DetailGaranties)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-last.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionDernier.setIcon(icon9)
        self.editionDernier.setObjectName(_fromUtf8("editionDernier"))
        self.menu_Fichier.addAction(self.fichierNouveau)
        self.menu_Fichier.addAction(self.fichierEnregistrer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.fichierImprimer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.fichierFermer)
        self.menu_Edition.addAction(self.editionAnnuler)
        self.menu_Edition.addAction(self.editionRefaire)
        self.menu_Edition.addSeparator()
        self.menu_Edition.addAction(self.editionPremier)
        self.menu_Edition.addAction(self.editionPrecedent)
        self.menu_Edition.addAction(self.editionSuivant)
        self.menu_Edition.addAction(self.editionDernier)
        self.menubar.addAction(self.menu_Fichier.menuAction())
        self.menubar.addAction(self.menu_Edition.menuAction())
        self.toolBar.addAction(self.fichierNouveau)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionPremier)
        self.toolBar.addAction(self.editionPrecedent)
        self.toolBar.addAction(self.editionSuivant)
        self.toolBar.addAction(self.editionDernier)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionRefaire)
        self.toolBar.addAction(self.editionAnnuler)
        self.toolBar.addAction(self.fichierEnregistrer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierImprimer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierFermer)

        self.retranslateUi(DetailGaranties)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DetailGaranties)
        DetailGaranties.setTabOrder(self.tauxPeriodeLineEdit, self.primAnnuelLineEdit)
        DetailGaranties.setTabOrder(self.primAnnuelLineEdit, self.primPeriodLineEdit)
        DetailGaranties.setTabOrder(self.primPeriodLineEdit, self.remiseLineEdit)
        DetailGaranties.setTabOrder(self.remiseLineEdit, self.primNetLineEdit)
        DetailGaranties.setTabOrder(self.primNetLineEdit, self.ristournLineEdit)
        DetailGaranties.setTabOrder(self.ristournLineEdit, self.accessLineEdit)
        DetailGaranties.setTabOrder(self.accessLineEdit, self.fichierCentralLineEdit)
        DetailGaranties.setTabOrder(self.fichierCentralLineEdit, self.tvaLineEdit)
        DetailGaranties.setTabOrder(self.tvaLineEdit, self.cartRosLineEdit)
        DetailGaranties.setTabOrder(self.cartRosLineEdit, self.autrTaxLineEdit)
        DetailGaranties.setTabOrder(self.autrTaxLineEdit, self.autrFraisLineEdit)
        DetailGaranties.setTabOrder(self.autrFraisLineEdit, self.primttcLineEdit)
        DetailGaranties.setTabOrder(self.primttcLineEdit, self.G01CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G01CheckBoxDetails, self.G02CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G02CheckBoxDetails, self.G03CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G03CheckBoxDetails, self.G04CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G04CheckBoxDetails, self.G05CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G05CheckBoxDetails, self.G06CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G06CheckBoxDetails, self.G07CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G07CheckBoxDetails, self.G08CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G08CheckBoxDetails, self.G09CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G09CheckBoxDetails, self.G10CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G10CheckBoxDetails, self.G11CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G11CheckBoxDetails, self.G12CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G12CheckBoxDetails, self.G13CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G13CheckBoxDetails, self.G14CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G14CheckBoxDetails, self.G15CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G15CheckBoxDetails, self.G16CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G16CheckBoxDetails, self.G17CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G17CheckBoxDetails, self.G18CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G18CheckBoxDetails, self.G19CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G19CheckBoxDetails, self.G20CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G20CheckBoxDetails, self.G21CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G21CheckBoxDetails, self.G22CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G22CheckBoxDetails, self.G23CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G23CheckBoxDetails, self.G24CheckBoxDetails)
        DetailGaranties.setTabOrder(self.G24CheckBoxDetails, self.detailGarantiesTableView)
        DetailGaranties.setTabOrder(self.detailGarantiesTableView, self.recapPrimesTableView)
        DetailGaranties.setTabOrder(self.recapPrimesTableView, self.tabWidget)
        DetailGaranties.setTabOrder(self.tabWidget, self.textAvenantTextEdit)
        DetailGaranties.setTabOrder(self.textAvenantTextEdit, self.listView)

    def retranslateUi(self, DetailGaranties):
        DetailGaranties.setWindowTitle(_translate("DetailGaranties", "Details Garanties", None))
        self.labelDetailsGaranties.setText(_translate("DetailGaranties", "Details des Garanties Souscrites sur le Vehicule.", None))
        self.detailGarantiesTableView.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Details des Garanties Souscrites sur le Vehicule.</p></body></html>", None))
        self.detailGarantiesTableView.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Details des Garanties Souscrites sur le Vehicule.</p></body></html>", None))
        self.labelRecapPrimes.setText(_translate("DetailGaranties", "Recapitulatifs des Primes Souscrites sur le Vehicule.", None))
        self.recapPrimesTableView.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Recapitulatifs des Primes Souscrites sur le Vehicule.</p></body></html>", None))
        self.recapPrimesTableView.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Recapitulatifs des Primes Souscrites sur le Vehicule.</p></body></html>", None))
        self.labelRistourne.setText(_translate("DetailGaranties", "Ristourne", None))
        self.remiseLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Remise.</p></body></html>", None))
        self.remiseLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Remise.</p></body></html>", None))
        self.tauxPeriodeLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Taux Periode.</p></body></html>", None))
        self.tauxPeriodeLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Taux Periode.</p></body></html>", None))
        self.primNetLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Prime Nette.</p></body></html>", None))
        self.primNetLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Prime Nette.</p></body></html>", None))
        self.labelTauxPeriode.setText(_translate("DetailGaranties", "Taux Periode", None))
        self.labelPrimeNette.setText(_translate("DetailGaranties", "Prime Nette", None))
        self.primAnnuelLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Prime Annuelle.</p></body></html>", None))
        self.primAnnuelLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Prime Annuelle.</p></body></html>", None))
        self.accessLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Accessoires.</p></body></html>", None))
        self.accessLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Accessoires.</p></body></html>", None))
        self.labelAccessoires.setText(_translate("DetailGaranties", "Accessoires", None))
        self.labelRemise.setText(_translate("DetailGaranties", "Remise", None))
        self.labelFichierCentral.setText(_translate("DetailGaranties", "Fichier Central", None))
        self.primttcLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Prime TTC.</p></body></html>", None))
        self.primttcLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Prime TTC.</p></body></html>", None))
        self.ristournLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Ristourne.</p></body></html>", None))
        self.ristournLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Ristourne.</p></body></html>", None))
        self.labelPrimeTTC.setText(_translate("DetailGaranties", "Prime TTC", None))
        self.autrTaxLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Autres Taxes.</p></body></html>", None))
        self.autrTaxLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Autres Taxes.</p></body></html>", None))
        self.primPeriodLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Prime Periode.</p></body></html>", None))
        self.primPeriodLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Prime Periode.</p></body></html>", None))
        self.labelPrimeAnnuelle.setText(_translate("DetailGaranties", "Prime Annuelle", None))
        self.labelAutresFrais.setText(_translate("DetailGaranties", "Autres Frais", None))
        self.autrFraisLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Autres Frais.</p></body></html>", None))
        self.autrFraisLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Autres Frais.</p></body></html>", None))
        self.labelPrimePeriode.setText(_translate("DetailGaranties", "Prime Periode", None))
        self.fichierCentralLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Fichier Central.</p></body></html>", None))
        self.fichierCentralLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Fichier Central.</p></body></html>", None))
        self.cartRosLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Cartes Roses.</p></body></html>", None))
        self.cartRosLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Cartes Roses.</p></body></html>", None))
        self.labelCartesRoses.setText(_translate("DetailGaranties", "Cartes Roses", None))
        self.labelTva.setText(_translate("DetailGaranties", "TVA", None))
        self.tvaLineEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>TVA.</p></body></html>", None))
        self.tvaLineEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>TVA.</p></body></html>", None))
        self.labelAutresTaxes.setText(_translate("DetailGaranties", "Autres Taxes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_detail_prime), _translate("DetailGaranties", "Detail Prime", None))
        self.textAvenantTextEdit.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Texte Avenant.</p></body></html>", None))
        self.textAvenantTextEdit.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Texte Avenant.</p></body></html>", None))
        self.textAvenantTextEdit.setHtml(_translate("DetailGaranties", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Narrow\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Helvetica Neue DeskInterface\';\">Memo1</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_texte_avenant), _translate("DetailGaranties", "Texte Avenant", None))
        self.G01CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G01.</p></body></html>", None))
        self.G01CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G01.</p></body></html>", None))
        self.G01CheckBoxDetails.setText(_translate("DetailGaranties", "G01", None))
        self.G02CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G02.</p></body></html>", None))
        self.G02CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G02.</p></body></html>", None))
        self.G02CheckBoxDetails.setText(_translate("DetailGaranties", "G02", None))
        self.G03CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G03.</p></body></html>", None))
        self.G03CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G03.</p></body></html>", None))
        self.G03CheckBoxDetails.setText(_translate("DetailGaranties", "G03", None))
        self.G04CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G04.</p></body></html>", None))
        self.G04CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G04.</p></body></html>", None))
        self.G04CheckBoxDetails.setText(_translate("DetailGaranties", "G04", None))
        self.G05CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G05.</p></body></html>", None))
        self.G05CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G05.</p></body></html>", None))
        self.G05CheckBoxDetails.setText(_translate("DetailGaranties", "G05", None))
        self.G06CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G06.</p></body></html>", None))
        self.G06CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G06.</p></body></html>", None))
        self.G06CheckBoxDetails.setText(_translate("DetailGaranties", "G06", None))
        self.G07CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G07.</p></body></html>", None))
        self.G07CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G07.</p></body></html>", None))
        self.G07CheckBoxDetails.setText(_translate("DetailGaranties", "G07", None))
        self.G08CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G08.</p></body></html>", None))
        self.G08CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G08.</p></body></html>", None))
        self.G08CheckBoxDetails.setText(_translate("DetailGaranties", "G08", None))
        self.G09CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G09.</p></body></html>", None))
        self.G09CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G09.</p></body></html>", None))
        self.G09CheckBoxDetails.setText(_translate("DetailGaranties", "G09", None))
        self.G10CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G10.</p></body></html>", None))
        self.G10CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G10.</p></body></html>", None))
        self.G10CheckBoxDetails.setText(_translate("DetailGaranties", "G10", None))
        self.G11CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G11.</p></body></html>", None))
        self.G11CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G11.</p></body></html>", None))
        self.G11CheckBoxDetails.setText(_translate("DetailGaranties", "G11", None))
        self.G12CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G12.</p></body></html>", None))
        self.G12CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G12.</p></body></html>", None))
        self.G12CheckBoxDetails.setText(_translate("DetailGaranties", "G12", None))
        self.G13CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G13.</p></body></html>", None))
        self.G13CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G13.</p></body></html>", None))
        self.G13CheckBoxDetails.setText(_translate("DetailGaranties", "G13", None))
        self.G14CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G14.</p></body></html>", None))
        self.G14CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G14.</p></body></html>", None))
        self.G14CheckBoxDetails.setText(_translate("DetailGaranties", "G14", None))
        self.G15CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G15.</p></body></html>", None))
        self.G15CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G15.</p></body></html>", None))
        self.G15CheckBoxDetails.setText(_translate("DetailGaranties", "G15", None))
        self.G16CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G16.</p></body></html>", None))
        self.G16CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G16.</p></body></html>", None))
        self.G16CheckBoxDetails.setText(_translate("DetailGaranties", "G16", None))
        self.G17CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G17.</p></body></html>", None))
        self.G17CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G17.</p></body></html>", None))
        self.G17CheckBoxDetails.setText(_translate("DetailGaranties", "G17", None))
        self.G18CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G18.</p></body></html>", None))
        self.G18CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G18.</p></body></html>", None))
        self.G18CheckBoxDetails.setText(_translate("DetailGaranties", "G18", None))
        self.G19CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G19.</p></body></html>", None))
        self.G19CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G19.</p></body></html>", None))
        self.G19CheckBoxDetails.setText(_translate("DetailGaranties", "G19", None))
        self.G20CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G20.</p></body></html>", None))
        self.G20CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G20.</p></body></html>", None))
        self.G20CheckBoxDetails.setText(_translate("DetailGaranties", "G20", None))
        self.G21CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G21.</p></body></html>", None))
        self.G21CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G21.</p></body></html>", None))
        self.G21CheckBoxDetails.setText(_translate("DetailGaranties", "G21", None))
        self.G22CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G22.</p></body></html>", None))
        self.G22CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G22.</p></body></html>", None))
        self.G22CheckBoxDetails.setText(_translate("DetailGaranties", "G22", None))
        self.G23CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G23.</p></body></html>", None))
        self.G23CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G23.</p></body></html>", None))
        self.G23CheckBoxDetails.setText(_translate("DetailGaranties", "G23", None))
        self.G24CheckBoxDetails.setToolTip(_translate("DetailGaranties", "<html><head/><body><p>Garantie G24.</p></body></html>", None))
        self.G24CheckBoxDetails.setWhatsThis(_translate("DetailGaranties", "<html><head/><body><p>Garantie G24.</p></body></html>", None))
        self.G24CheckBoxDetails.setText(_translate("DetailGaranties", "G24", None))
        self.menu_Fichier.setTitle(_translate("DetailGaranties", "&Fichier", None))
        self.menu_Edition.setTitle(_translate("DetailGaranties", "&Edition", None))
        self.toolBar.setWindowTitle(_translate("DetailGaranties", "toolBar", None))
        self.fichierNouveau.setText(_translate("DetailGaranties", "Nouveau", None))
        self.fichierEnregistrer.setText(_translate("DetailGaranties", "Enregistrer", None))
        self.fichierImprimer.setText(_translate("DetailGaranties", "Imprimer les Details des Garanties souscrites", None))
        self.fichierFermer.setText(_translate("DetailGaranties", "Fermer", None))
        self.editionAnnuler.setText(_translate("DetailGaranties", "Annuler", None))
        self.editionRefaire.setText(_translate("DetailGaranties", "Refaire", None))
        self.editionPremier.setText(_translate("DetailGaranties", "Premier", None))
        self.editionPrecedent.setText(_translate("DetailGaranties", "Precedent", None))
        self.editionSuivant.setText(_translate("DetailGaranties", "Suivant", None))
        self.editionDernier.setText(_translate("DetailGaranties", "Dernier", None))

import ressources_rc
