# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gesiard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Gesiard(object):
    def setupUi(self, Gesiard):
        Gesiard.setObjectName(_fromUtf8("Gesiard"))
        Gesiard.resize(952, 478)
        self.centralwidget = QtGui.QWidget(Gesiard)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.msgLogoLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.msgLogoLabel.setFont(font)
        self.msgLogoLabel.setObjectName(_fromUtf8("msgLogoLabel"))
        self.horizontalLayout.addWidget(self.msgLogoLabel)
        self.logoLabel = QtGui.QLabel(self.centralwidget)
        self.logoLabel.setText(_fromUtf8(""))
        self.logoLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/logo/Logo_Officiel_Alpha_Access.png")))
        self.logoLabel.setObjectName(_fromUtf8("logoLabel"))
        self.horizontalLayout.addWidget(self.logoLabel)
        Gesiard.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Gesiard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menuNouveau = QtGui.QMenu(self.menuFichier)
        self.menuNouveau.setObjectName(_fromUtf8("menuNouveau"))
        self.menuTraitements = QtGui.QMenu(self.menubar)
        self.menuTraitements.setObjectName(_fromUtf8("menuTraitements"))
        self.menuGestionReversements = QtGui.QMenu(self.menuTraitements)
        self.menuGestionReversements.setObjectName(_fromUtf8("menuGestionReversements"))
        self.menuEditionEtats = QtGui.QMenu(self.menubar)
        self.menuEditionEtats.setObjectName(_fromUtf8("menuEditionEtats"))
        self.menuClients = QtGui.QMenu(self.menuEditionEtats)
        self.menuClients.setObjectName(_fromUtf8("menuClients"))
        self.menuBordereauxEmissions = QtGui.QMenu(self.menuEditionEtats)
        self.menuBordereauxEmissions.setObjectName(_fromUtf8("menuBordereauxEmissions"))
        self.menuBordereauxAttestations = QtGui.QMenu(self.menuEditionEtats)
        self.menuBordereauxAttestations.setObjectName(_fromUtf8("menuBordereauxAttestations"))
        self.menuGestionnaires = QtGui.QMenu(self.menuEditionEtats)
        self.menuGestionnaires.setObjectName(_fromUtf8("menuGestionnaires"))
        self.menuProcesVerbaux = QtGui.QMenu(self.menuEditionEtats)
        self.menuProcesVerbaux.setObjectName(_fromUtf8("menuProcesVerbaux"))
        self.menuEcheancier = QtGui.QMenu(self.menuEditionEtats)
        self.menuEcheancier.setObjectName(_fromUtf8("menuEcheancier"))
        self.menuSinistres = QtGui.QMenu(self.menuEditionEtats)
        self.menuSinistres.setObjectName(_fromUtf8("menuSinistres"))
        Gesiard.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Gesiard)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Gesiard.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(Gesiard)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        Gesiard.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fichierImporter = QtGui.QAction(Gesiard)
        self.fichierImporter.setObjectName(_fromUtf8("fichierImporter"))
        self.fichierExporter = QtGui.QAction(Gesiard)
        self.fichierExporter.setObjectName(_fromUtf8("fichierExporter"))
        self.fichierParametrage = QtGui.QAction(Gesiard)
        self.fichierParametrage.setObjectName(_fromUtf8("fichierParametrage"))
        self.fichierQuitter = QtGui.QAction(Gesiard)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/system-log-out.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierQuitter.setIcon(icon)
        self.fichierQuitter.setObjectName(_fromUtf8("fichierQuitter"))
        self.FichierNouvGest = QtGui.QAction(Gesiard)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/contact-new.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FichierNouvGest.setIcon(icon1)
        self.FichierNouvGest.setObjectName(_fromUtf8("FichierNouvGest"))
        self.fichierNouvMouvEmission = QtGui.QAction(Gesiard)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/NouveauContrat.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierNouvMouvEmission.setIcon(icon2)
        self.fichierNouvMouvEmission.setObjectName(_fromUtf8("fichierNouvMouvEmission"))
        self.fichierNouvDecSinistre = QtGui.QAction(Gesiard)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/NouveauSinistre.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierNouvDecSinistre.setIcon(icon3)
        self.fichierNouvDecSinistre.setObjectName(_fromUtf8("fichierNouvDecSinistre"))
        self.traitEnregPaiement = QtGui.QAction(Gesiard)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Encaissements.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.traitEnregPaiement.setIcon(icon4)
        self.traitEnregPaiement.setObjectName(_fromUtf8("traitEnregPaiement"))
        self.traitSuiviSinistr = QtGui.QAction(Gesiard)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/DocumenterSinistre.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.traitSuiviSinistr.setIcon(icon5)
        self.traitSuiviSinistr.setObjectName(_fromUtf8("traitSuiviSinistr"))
        self.traitSuiviVictim = QtGui.QAction(Gesiard)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/SinistreSuiviVictimes.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.traitSuiviVictim.setIcon(icon6)
        self.traitSuiviVictim.setObjectName(_fromUtf8("traitSuiviVictim"))
        self.traitPrepaRev = QtGui.QAction(Gesiard)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/ReversementPreparer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.traitPrepaRev.setIcon(icon7)
        self.traitPrepaRev.setObjectName(_fromUtf8("traitPrepaRev"))
        self.traitValidRev = QtGui.QAction(Gesiard)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/ReversementValider.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.traitValidRev.setIcon(icon8)
        self.traitValidRev.setObjectName(_fromUtf8("traitValidRev"))
        self.editionListingClient = QtGui.QAction(Gesiard)
        self.editionListingClient.setObjectName(_fromUtf8("editionListingClient"))
        self.editionReleveCompteClient = QtGui.QAction(Gesiard)
        self.editionReleveCompteClient.setObjectName(_fromUtf8("editionReleveCompteClient"))
        self.editionEmissionBrut = QtGui.QAction(Gesiard)
        self.editionEmissionBrut.setObjectName(_fromUtf8("editionEmissionBrut"))
        self.editionEmissionAnnulations = QtGui.QAction(Gesiard)
        self.editionEmissionAnnulations.setObjectName(_fromUtf8("editionEmissionAnnulations"))
        self.editionEmissionResiRistournes = QtGui.QAction(Gesiard)
        self.editionEmissionResiRistournes.setObjectName(_fromUtf8("editionEmissionResiRistournes"))
        self.editionEmissionNetAnnulations = QtGui.QAction(Gesiard)
        self.editionEmissionNetAnnulations.setObjectName(_fromUtf8("editionEmissionNetAnnulations"))
        self.editionEmissionNetResiRistournes = QtGui.QAction(Gesiard)
        self.editionEmissionNetResiRistournes.setObjectName(_fromUtf8("editionEmissionNetResiRistournes"))
        self.editionEmissisonNettes = QtGui.QAction(Gesiard)
        self.editionEmissisonNettes.setObjectName(_fromUtf8("editionEmissisonNettes"))
        self.editionAttestationVP = QtGui.QAction(Gesiard)
        self.editionAttestationVP.setObjectName(_fromUtf8("editionAttestationVP"))
        self.editionAttestationTPV = QtGui.QAction(Gesiard)
        self.editionAttestationTPV.setObjectName(_fromUtf8("editionAttestationTPV"))
        self.editionAttestationCartRos = QtGui.QAction(Gesiard)
        self.editionAttestationCartRos.setObjectName(_fromUtf8("editionAttestationCartRos"))
        self.editionGestListingGest = QtGui.QAction(Gesiard)
        self.editionGestListingGest.setObjectName(_fromUtf8("editionGestListingGest"))
        self.editionGestCommis = QtGui.QAction(Gesiard)
        self.editionGestCommis.setObjectName(_fromUtf8("editionGestCommis"))
        self.editionPVCaissEspeces = QtGui.QAction(Gesiard)
        self.editionPVCaissEspeces.setObjectName(_fromUtf8("editionPVCaissEspeces"))
        self.editionPVEffetAutrEncais = QtGui.QAction(Gesiard)
        self.editionPVEffetAutrEncais.setObjectName(_fromUtf8("editionPVEffetAutrEncais"))
        self.editionPVCaissDetail = QtGui.QAction(Gesiard)
        self.editionPVCaissDetail.setObjectName(_fromUtf8("editionPVCaissDetail"))
        self.editionEcheancierListingRenouvel = QtGui.QAction(Gesiard)
        self.editionEcheancierListingRenouvel.setObjectName(_fromUtf8("editionEcheancierListingRenouvel"))
        self.editionSinistrListingDecEnreg = QtGui.QAction(Gesiard)
        self.editionSinistrListingDecEnreg.setObjectName(_fromUtf8("editionSinistrListingDecEnreg"))
        self.editionSinistreSituationPeriodiqSinistres = QtGui.QAction(Gesiard)
        self.editionSinistreSituationPeriodiqSinistres.setObjectName(_fromUtf8("editionSinistreSituationPeriodiqSinistres"))
        self.menuNouveau.addAction(self.FichierNouvGest)
        self.menuNouveau.addSeparator()
        self.menuNouveau.addAction(self.fichierNouvMouvEmission)
        self.menuNouveau.addAction(self.fichierNouvDecSinistre)
        self.menuFichier.addAction(self.menuNouveau.menuAction())
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.fichierImporter)
        self.menuFichier.addAction(self.fichierExporter)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.fichierParametrage)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.fichierQuitter)
        self.menuGestionReversements.addAction(self.traitPrepaRev)
        self.menuGestionReversements.addAction(self.traitValidRev)
        self.menuTraitements.addAction(self.traitEnregPaiement)
        self.menuTraitements.addAction(self.menuGestionReversements.menuAction())
        self.menuTraitements.addSeparator()
        self.menuTraitements.addAction(self.traitSuiviSinistr)
        self.menuTraitements.addAction(self.traitSuiviVictim)
        self.menuClients.addAction(self.editionListingClient)
        self.menuClients.addAction(self.editionReleveCompteClient)
        self.menuBordereauxEmissions.addAction(self.editionEmissionBrut)
        self.menuBordereauxEmissions.addAction(self.editionEmissionAnnulations)
        self.menuBordereauxEmissions.addAction(self.editionEmissionResiRistournes)
        self.menuBordereauxEmissions.addAction(self.editionEmissionNetAnnulations)
        self.menuBordereauxEmissions.addAction(self.editionEmissionNetResiRistournes)
        self.menuBordereauxEmissions.addAction(self.editionEmissisonNettes)
        self.menuBordereauxAttestations.addAction(self.editionAttestationVP)
        self.menuBordereauxAttestations.addAction(self.editionAttestationTPV)
        self.menuBordereauxAttestations.addAction(self.editionAttestationCartRos)
        self.menuGestionnaires.addAction(self.editionGestListingGest)
        self.menuGestionnaires.addAction(self.editionGestCommis)
        self.menuProcesVerbaux.addAction(self.editionPVCaissEspeces)
        self.menuProcesVerbaux.addAction(self.editionPVEffetAutrEncais)
        self.menuProcesVerbaux.addAction(self.editionPVCaissDetail)
        self.menuEcheancier.addAction(self.editionEcheancierListingRenouvel)
        self.menuSinistres.addAction(self.editionSinistrListingDecEnreg)
        self.menuSinistres.addAction(self.editionSinistreSituationPeriodiqSinistres)
        self.menuEditionEtats.addAction(self.menuClients.menuAction())
        self.menuEditionEtats.addSeparator()
        self.menuEditionEtats.addAction(self.menuBordereauxEmissions.menuAction())
        self.menuEditionEtats.addAction(self.menuBordereauxAttestations.menuAction())
        self.menuEditionEtats.addAction(self.menuGestionnaires.menuAction())
        self.menuEditionEtats.addAction(self.menuProcesVerbaux.menuAction())
        self.menuEditionEtats.addAction(self.menuEcheancier.menuAction())
        self.menuEditionEtats.addSeparator()
        self.menuEditionEtats.addAction(self.menuSinistres.menuAction())
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuTraitements.menuAction())
        self.menubar.addAction(self.menuEditionEtats.menuAction())
        self.toolBar.addAction(self.fichierNouvMouvEmission)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.traitEnregPaiement)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierNouvDecSinistre)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.traitSuiviSinistr)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.traitSuiviVictim)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierQuitter)

        self.retranslateUi(Gesiard)
        QtCore.QMetaObject.connectSlotsByName(Gesiard)

    def retranslateUi(self, Gesiard):
        Gesiard.setWindowTitle(_translate("Gesiard", "Gesiard", None))
        self.msgLogoLabel.setText(_translate("Gesiard", "Le Gestionnaire de votre Patrimoine d\'Assurance", None))
        self.menuFichier.setTitle(_translate("Gesiard", "Fichier", None))
        self.menuNouveau.setTitle(_translate("Gesiard", "Nouveau", None))
        self.menuTraitements.setTitle(_translate("Gesiard", "Traitements", None))
        self.menuGestionReversements.setTitle(_translate("Gesiard", "Gestion des Reversements", None))
        self.menuEditionEtats.setTitle(_translate("Gesiard", "Edition etats", None))
        self.menuClients.setTitle(_translate("Gesiard", "Clients", None))
        self.menuBordereauxEmissions.setTitle(_translate("Gesiard", "Bordereaux des Emissions", None))
        self.menuBordereauxAttestations.setTitle(_translate("Gesiard", "Bordereaux des Attestations", None))
        self.menuGestionnaires.setTitle(_translate("Gesiard", "Gestionnaires", None))
        self.menuProcesVerbaux.setTitle(_translate("Gesiard", "Proces Verbaux", None))
        self.menuEcheancier.setTitle(_translate("Gesiard", "Echeancier", None))
        self.menuSinistres.setTitle(_translate("Gesiard", "Sinistres", None))
        self.toolBar.setWindowTitle(_translate("Gesiard", "toolBar", None))
        self.fichierImporter.setText(_translate("Gesiard", "Importer les Donnees", None))
        self.fichierExporter.setText(_translate("Gesiard", "Exporter les Donnees", None))
        self.fichierParametrage.setText(_translate("Gesiard", "Demande modification Parametrage", None))
        self.fichierQuitter.setText(_translate("Gesiard", "Quitter", None))
        self.fichierQuitter.setToolTip(_translate("Gesiard", "Quitter MatAuto", None))
        self.FichierNouvGest.setText(_translate("Gesiard", "Gestionnaire Portefeuille", None))
        self.FichierNouvGest.setToolTip(_translate("Gesiard", "Nouveau Gestionnaire de Portefeuille", None))
        self.fichierNouvMouvEmission.setText(_translate("Gesiard", "Mouvement Emission", None))
        self.fichierNouvMouvEmission.setToolTip(_translate("Gesiard", "Nouveau Mouvement Emission", None))
        self.fichierNouvDecSinistre.setText(_translate("Gesiard", "Declaration Sinistre", None))
        self.fichierNouvDecSinistre.setToolTip(_translate("Gesiard", "Nouvelle Declaration de Sinistre", None))
        self.traitEnregPaiement.setText(_translate("Gesiard", "Enregistrer un Paiement", None))
        self.traitSuiviSinistr.setText(_translate("Gesiard", "Suivi des Sinistres", None))
        self.traitSuiviSinistr.setToolTip(_translate("Gesiard", "Suivit des Sinistres", None))
        self.traitSuiviVictim.setText(_translate("Gesiard", "Suivi des Victimes", None))
        self.traitSuiviVictim.setToolTip(_translate("Gesiard", "Suivit des Victimes", None))
        self.traitPrepaRev.setText(_translate("Gesiard", "Preparation Bordereaux Reversement", None))
        self.traitValidRev.setText(_translate("Gesiard", "Validation Bordereaux Reversement", None))
        self.editionListingClient.setText(_translate("Gesiard", "Listing des Clients", None))
        self.editionReleveCompteClient.setText(_translate("Gesiard", "Releve Compte Client", None))
        self.editionEmissionBrut.setText(_translate("Gesiard", "Brutes", None))
        self.editionEmissionAnnulations.setText(_translate("Gesiard", "Annulations", None))
        self.editionEmissionResiRistournes.setText(_translate("Gesiard", "Resiliation et Ristournes", None))
        self.editionEmissionNetAnnulations.setText(_translate("Gesiard", "Emissions Nettes d\'Annulations", None))
        self.editionEmissionNetResiRistournes.setText(_translate("Gesiard", "Emissions Nettes de Resiliation et de Ristournes", None))
        self.editionEmissisonNettes.setText(_translate("Gesiard", "Nettes (Annulation, Resiliation et de Ristournes)", None))
        self.editionAttestationVP.setText(_translate("Gesiard", "Attestations VP", None))
        self.editionAttestationTPV.setText(_translate("Gesiard", "Attestations TPV", None))
        self.editionAttestationCartRos.setText(_translate("Gesiard", "Cartes Roses", None))
        self.editionGestListingGest.setText(_translate("Gesiard", "Listing des Gestionnaires", None))
        self.editionGestCommis.setText(_translate("Gesiard", "Commissions", None))
        self.editionPVCaissEspeces.setText(_translate("Gesiard", "Proces Verbal de Caisse Especes", None))
        self.editionPVEffetAutrEncais.setText(_translate("Gesiard", "Proces Verbal Effets et autres Encaissements", None))
        self.editionPVCaissDetail.setText(_translate("Gesiard", "Proces Verbal de Caisse Detaille", None))
        self.editionEcheancierListingRenouvel.setText(_translate("Gesiard", "Listing des Renouvellements", None))
        self.editionSinistrListingDecEnreg.setText(_translate("Gesiard", "Listing des Declarations Enregistrees", None))
        self.editionSinistreSituationPeriodiqSinistres.setText(_translate("Gesiard", "Situation Periodique des Sinistres", None))

import ressources_rc
