# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestionnaireportefeuille.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GestionnairePortefeuille(object):
    def setupUi(self, GestionnairePortefeuille):
        GestionnairePortefeuille.setObjectName(_fromUtf8("GestionnairePortefeuille"))
        GestionnairePortefeuille.setWindowModality(QtCore.Qt.ApplicationModal)
        GestionnairePortefeuille.resize(777, 506)
        self.centralwidget = QtGui.QWidget(GestionnairePortefeuille)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frameGestionnaire = QtGui.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.frameGestionnaire.setFont(font)
        self.frameGestionnaire.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameGestionnaire.setFrameShadow(QtGui.QFrame.Raised)
        self.frameGestionnaire.setObjectName(_fromUtf8("frameGestionnaire"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frameGestionnaire)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelNumClient = QtGui.QLabel(self.frameGestionnaire)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.labelNumClient.setFont(font)
        self.labelNumClient.setAutoFillBackground(False)
        self.labelNumClient.setObjectName(_fromUtf8("labelNumClient"))
        self.gridLayout_2.addWidget(self.labelNumClient, 0, 0, 1, 1)
        self.labelPrenom = QtGui.QLabel(self.frameGestionnaire)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.labelPrenom.setFont(font)
        self.labelPrenom.setObjectName(_fromUtf8("labelPrenom"))
        self.gridLayout_2.addWidget(self.labelPrenom, 1, 0, 1, 1)
        self.numGestComboBox = QtGui.QComboBox(self.frameGestionnaire)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numGestComboBox.sizePolicy().hasHeightForWidth())
        self.numGestComboBox.setSizePolicy(sizePolicy)
        self.numGestComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.numGestComboBox.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.numGestComboBox.setFont(font)
        self.numGestComboBox.setEditable(True)
        self.numGestComboBox.setObjectName(_fromUtf8("numGestComboBox"))
        self.gridLayout_2.addWidget(self.numGestComboBox, 0, 1, 1, 1)
        self.labelCivilite = QtGui.QLabel(self.frameGestionnaire)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.labelCivilite.setFont(font)
        self.labelCivilite.setObjectName(_fromUtf8("labelCivilite"))
        self.gridLayout_2.addWidget(self.labelCivilite, 3, 0, 1, 1)
        self.labelAdresse = QtGui.QLabel(self.frameGestionnaire)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.labelAdresse.setFont(font)
        self.labelAdresse.setObjectName(_fromUtf8("labelAdresse"))
        self.gridLayout_2.addWidget(self.labelAdresse, 4, 0, 1, 1)
        self.adressLineEdit = QtGui.QLineEdit(self.frameGestionnaire)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adressLineEdit.sizePolicy().hasHeightForWidth())
        self.adressLineEdit.setSizePolicy(sizePolicy)
        self.adressLineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.adressLineEdit.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.adressLineEdit.setFont(font)
        self.adressLineEdit.setObjectName(_fromUtf8("adressLineEdit"))
        self.gridLayout_2.addWidget(self.adressLineEdit, 4, 1, 1, 1)
        self.labelTypeGestionnaire = QtGui.QLabel(self.frameGestionnaire)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.labelTypeGestionnaire.setFont(font)
        self.labelTypeGestionnaire.setObjectName(_fromUtf8("labelTypeGestionnaire"))
        self.gridLayout_2.addWidget(self.labelTypeGestionnaire, 6, 0, 1, 1)
        self.labelPosteOccupe = QtGui.QLabel(self.frameGestionnaire)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.labelPosteOccupe.setFont(font)
        self.labelPosteOccupe.setObjectName(_fromUtf8("labelPosteOccupe"))
        self.gridLayout_2.addWidget(self.labelPosteOccupe, 5, 0, 1, 1)
        self.civiliteComboBox = QtGui.QComboBox(self.frameGestionnaire)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.civiliteComboBox.sizePolicy().hasHeightForWidth())
        self.civiliteComboBox.setSizePolicy(sizePolicy)
        self.civiliteComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.civiliteComboBox.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.civiliteComboBox.setFont(font)
        self.civiliteComboBox.setEditable(True)
        self.civiliteComboBox.setObjectName(_fromUtf8("civiliteComboBox"))
        self.gridLayout_2.addWidget(self.civiliteComboBox, 3, 1, 1, 1)
        self.prenomComboBox = QtGui.QComboBox(self.frameGestionnaire)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prenomComboBox.sizePolicy().hasHeightForWidth())
        self.prenomComboBox.setSizePolicy(sizePolicy)
        self.prenomComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.prenomComboBox.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.prenomComboBox.setFont(font)
        self.prenomComboBox.setEditable(True)
        self.prenomComboBox.setObjectName(_fromUtf8("prenomComboBox"))
        self.gridLayout_2.addWidget(self.prenomComboBox, 1, 1, 1, 1)
        self.labelNom = QtGui.QLabel(self.frameGestionnaire)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.labelNom.setFont(font)
        self.labelNom.setObjectName(_fromUtf8("labelNom"))
        self.gridLayout_2.addWidget(self.labelNom, 2, 0, 1, 1)
        self.nomComboBox = QtGui.QComboBox(self.frameGestionnaire)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nomComboBox.sizePolicy().hasHeightForWidth())
        self.nomComboBox.setSizePolicy(sizePolicy)
        self.nomComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.nomComboBox.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.nomComboBox.setFont(font)
        self.nomComboBox.setEditable(True)
        self.nomComboBox.setObjectName(_fromUtf8("nomComboBox"))
        self.gridLayout_2.addWidget(self.nomComboBox, 2, 1, 1, 1)
        self.posteOccupeLineEdit = QtGui.QLineEdit(self.frameGestionnaire)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posteOccupeLineEdit.sizePolicy().hasHeightForWidth())
        self.posteOccupeLineEdit.setSizePolicy(sizePolicy)
        self.posteOccupeLineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.posteOccupeLineEdit.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.posteOccupeLineEdit.setFont(font)
        self.posteOccupeLineEdit.setObjectName(_fromUtf8("posteOccupeLineEdit"))
        self.gridLayout_2.addWidget(self.posteOccupeLineEdit, 5, 1, 1, 1)
        self.typeGestComboBox = QtGui.QComboBox(self.frameGestionnaire)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeGestComboBox.sizePolicy().hasHeightForWidth())
        self.typeGestComboBox.setSizePolicy(sizePolicy)
        self.typeGestComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.typeGestComboBox.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.typeGestComboBox.setFont(font)
        self.typeGestComboBox.setEditable(True)
        self.typeGestComboBox.setObjectName(_fromUtf8("typeGestComboBox"))
        self.gridLayout_2.addWidget(self.typeGestComboBox, 6, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 2)
        self.gridLayout.addWidget(self.frameGestionnaire, 0, 0, 2, 1)
        self.frameGestionnaireContact = QtGui.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.frameGestionnaireContact.setFont(font)
        self.frameGestionnaireContact.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameGestionnaireContact.setFrameShadow(QtGui.QFrame.Raised)
        self.frameGestionnaireContact.setObjectName(_fromUtf8("frameGestionnaireContact"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frameGestionnaireContact)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelTelBureau = QtGui.QLabel(self.frameGestionnaireContact)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.labelTelBureau.setFont(font)
        self.labelTelBureau.setObjectName(_fromUtf8("labelTelBureau"))
        self.gridLayout_3.addWidget(self.labelTelBureau, 0, 0, 1, 1)
        self.phoneWLineEdit = QtGui.QLineEdit(self.frameGestionnaireContact)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.phoneWLineEdit.setFont(font)
        self.phoneWLineEdit.setObjectName(_fromUtf8("phoneWLineEdit"))
        self.gridLayout_3.addWidget(self.phoneWLineEdit, 0, 1, 1, 1)
        self.labelTelPortable = QtGui.QLabel(self.frameGestionnaireContact)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.labelTelPortable.setFont(font)
        self.labelTelPortable.setObjectName(_fromUtf8("labelTelPortable"))
        self.gridLayout_3.addWidget(self.labelTelPortable, 1, 0, 1, 1)
        self.phoneHLineEdit = QtGui.QLineEdit(self.frameGestionnaireContact)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.phoneHLineEdit.setFont(font)
        self.phoneHLineEdit.setObjectName(_fromUtf8("phoneHLineEdit"))
        self.gridLayout_3.addWidget(self.phoneHLineEdit, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.labelFax = QtGui.QLabel(self.frameGestionnaireContact)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.labelFax.setFont(font)
        self.labelFax.setObjectName(_fromUtf8("labelFax"))
        self.gridLayout_4.addWidget(self.labelFax, 0, 0, 1, 1)
        self.faxLineEdit = QtGui.QLineEdit(self.frameGestionnaireContact)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.faxLineEdit.setFont(font)
        self.faxLineEdit.setObjectName(_fromUtf8("faxLineEdit"))
        self.gridLayout_4.addWidget(self.faxLineEdit, 0, 1, 1, 1)
        self.labelMail = QtGui.QLabel(self.frameGestionnaireContact)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.labelMail.setFont(font)
        self.labelMail.setObjectName(_fromUtf8("labelMail"))
        self.gridLayout_4.addWidget(self.labelMail, 1, 0, 1, 1)
        self.mailLineEdit = QtGui.QLineEdit(self.frameGestionnaireContact)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.mailLineEdit.setFont(font)
        self.mailLineEdit.setObjectName(_fromUtf8("mailLineEdit"))
        self.gridLayout_4.addWidget(self.mailLineEdit, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.gridLayout.addWidget(self.frameGestionnaireContact, 0, 1, 1, 1)
        self.frameDistributionGestionnaire = QtGui.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.frameDistributionGestionnaire.setFont(font)
        self.frameDistributionGestionnaire.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameDistributionGestionnaire.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDistributionGestionnaire.setObjectName(_fromUtf8("frameDistributionGestionnaire"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameDistributionGestionnaire)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableView = QtGui.QTableView(self.frameDistributionGestionnaire)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(11)
        self.tableView.setFont(font)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout.addWidget(self.tableView)
        self.gridLayout.addWidget(self.frameDistributionGestionnaire, 1, 1, 1, 1)
        GestionnairePortefeuille.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(GestionnairePortefeuille)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Fichier = QtGui.QMenu(self.menubar)
        self.menu_Fichier.setObjectName(_fromUtf8("menu_Fichier"))
        self.menu_Edition = QtGui.QMenu(self.menubar)
        self.menu_Edition.setObjectName(_fromUtf8("menu_Edition"))
        GestionnairePortefeuille.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(GestionnairePortefeuille)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        GestionnairePortefeuille.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(GestionnairePortefeuille)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        GestionnairePortefeuille.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fichierNouveau = QtGui.QAction(GestionnairePortefeuille)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-new.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierNouveau.setIcon(icon)
        self.fichierNouveau.setObjectName(_fromUtf8("fichierNouveau"))
        self.fichierEnregistrer = QtGui.QAction(GestionnairePortefeuille)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-save.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierEnregistrer.setIcon(icon1)
        self.fichierEnregistrer.setObjectName(_fromUtf8("fichierEnregistrer"))
        self.fichierFermer = QtGui.QAction(GestionnairePortefeuille)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/system-log-out.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierFermer.setIcon(icon2)
        self.fichierFermer.setObjectName(_fromUtf8("fichierFermer"))
        self.editionAnnuler = QtGui.QAction(GestionnairePortefeuille)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-undo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionAnnuler.setIcon(icon3)
        self.editionAnnuler.setObjectName(_fromUtf8("editionAnnuler"))
        self.editionPremier = QtGui.QAction(GestionnairePortefeuille)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-first.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPremier.setIcon(icon4)
        self.editionPremier.setObjectName(_fromUtf8("editionPremier"))
        self.editionPrecedent = QtGui.QAction(GestionnairePortefeuille)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-previous.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPrecedent.setIcon(icon5)
        self.editionPrecedent.setObjectName(_fromUtf8("editionPrecedent"))
        self.editionSuivant = QtGui.QAction(GestionnairePortefeuille)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-next.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionSuivant.setIcon(icon6)
        self.editionSuivant.setObjectName(_fromUtf8("editionSuivant"))
        self.editionDernier = QtGui.QAction(GestionnairePortefeuille)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-last.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionDernier.setIcon(icon7)
        self.editionDernier.setObjectName(_fromUtf8("editionDernier"))
        self.editionRefaire = QtGui.QAction(GestionnairePortefeuille)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-redo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionRefaire.setIcon(icon8)
        self.editionRefaire.setObjectName(_fromUtf8("editionRefaire"))
        self.fichierImprimer = QtGui.QAction(GestionnairePortefeuille)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Imprimer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierImprimer.setIcon(icon9)
        self.fichierImprimer.setObjectName(_fromUtf8("fichierImprimer"))
        self.menu_Fichier.addAction(self.fichierNouveau)
        self.menu_Fichier.addAction(self.fichierEnregistrer)
        self.menu_Fichier.addAction(self.fichierImprimer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.fichierFermer)
        self.menu_Edition.addAction(self.editionAnnuler)
        self.menu_Edition.addAction(self.editionRefaire)
        self.menu_Edition.addSeparator()
        self.menu_Edition.addAction(self.editionPremier)
        self.menu_Edition.addAction(self.editionPrecedent)
        self.menu_Edition.addAction(self.editionSuivant)
        self.menu_Edition.addAction(self.editionDernier)
        self.menubar.addAction(self.menu_Fichier.menuAction())
        self.menubar.addAction(self.menu_Edition.menuAction())
        self.toolBar.addAction(self.fichierNouveau)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionPremier)
        self.toolBar.addAction(self.editionPrecedent)
        self.toolBar.addAction(self.editionSuivant)
        self.toolBar.addAction(self.editionDernier)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionRefaire)
        self.toolBar.addAction(self.editionAnnuler)
        self.toolBar.addAction(self.fichierEnregistrer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierImprimer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierFermer)
        self.labelNumClient.setBuddy(self.numGestComboBox)
        self.labelPrenom.setBuddy(self.prenomComboBox)
        self.labelTypeGestionnaire.setBuddy(self.typeGestComboBox)
        self.labelNom.setBuddy(self.nomComboBox)

        self.retranslateUi(GestionnairePortefeuille)
        QtCore.QMetaObject.connectSlotsByName(GestionnairePortefeuille)
        GestionnairePortefeuille.setTabOrder(self.numGestComboBox, self.prenomComboBox)
        GestionnairePortefeuille.setTabOrder(self.prenomComboBox, self.nomComboBox)
        GestionnairePortefeuille.setTabOrder(self.nomComboBox, self.civiliteComboBox)
        GestionnairePortefeuille.setTabOrder(self.civiliteComboBox, self.adressLineEdit)
        GestionnairePortefeuille.setTabOrder(self.adressLineEdit, self.posteOccupeLineEdit)
        GestionnairePortefeuille.setTabOrder(self.posteOccupeLineEdit, self.typeGestComboBox)
        GestionnairePortefeuille.setTabOrder(self.typeGestComboBox, self.phoneWLineEdit)
        GestionnairePortefeuille.setTabOrder(self.phoneWLineEdit, self.phoneHLineEdit)
        GestionnairePortefeuille.setTabOrder(self.phoneHLineEdit, self.faxLineEdit)
        GestionnairePortefeuille.setTabOrder(self.faxLineEdit, self.mailLineEdit)

    def retranslateUi(self, GestionnairePortefeuille):
        GestionnairePortefeuille.setWindowTitle(_translate("GestionnairePortefeuille", "Gestionnaire de Portefeuille", None))
        self.labelNumClient.setText(_translate("GestionnairePortefeuille", "Numero &Gestionnaire", None))
        self.labelPrenom.setText(_translate("GestionnairePortefeuille", "&Prenom", None))
        self.numGestComboBox.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Numero Du Client.</p></body></html>", None))
        self.numGestComboBox.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Numero Du Client.</p></body></html>", None))
        self.labelCivilite.setText(_translate("GestionnairePortefeuille", "Civilite", None))
        self.labelAdresse.setText(_translate("GestionnairePortefeuille", "Adresse", None))
        self.adressLineEdit.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Adresse Du Client.</p></body></html>", None))
        self.adressLineEdit.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Adresse Du Client.</p></body></html>", None))
        self.labelTypeGestionnaire.setText(_translate("GestionnairePortefeuille", "&Type Gestionnaire", None))
        self.labelPosteOccupe.setText(_translate("GestionnairePortefeuille", "Poste occupe", None))
        self.civiliteComboBox.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Civilite Du Client.</p></body></html>", None))
        self.civiliteComboBox.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Civilite Du Client.</p></body></html>", None))
        self.prenomComboBox.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Prenom Du Client.</p></body></html>", None))
        self.prenomComboBox.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Prenom Du Client.</p></body></html>", None))
        self.labelNom.setText(_translate("GestionnairePortefeuille", "&Nom", None))
        self.nomComboBox.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Nom Du Client.</p></body></html>", None))
        self.nomComboBox.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Nom Du Client.</p></body></html>", None))
        self.posteOccupeLineEdit.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Poste Occupe actuellement par le Client.</p></body></html>", None))
        self.posteOccupeLineEdit.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Poste Occupe actuellement par le Client.</p></body></html>", None))
        self.typeGestComboBox.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Departement Du Client.</p></body></html>", None))
        self.typeGestComboBox.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Departement Du Client.</p></body></html>", None))
        self.labelTelBureau.setText(_translate("GestionnairePortefeuille", "Telephone Bureau", None))
        self.phoneWLineEdit.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Numero de Telephone du Bureau Du Client.</p></body></html>", None))
        self.phoneWLineEdit.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Numero de Telephone du Bureau Du Client.</p></body></html>", None))
        self.labelTelPortable.setText(_translate("GestionnairePortefeuille", "Telephone Portable", None))
        self.phoneHLineEdit.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Numero de Telephone Portable Du Client.</p></body></html>", None))
        self.phoneHLineEdit.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Numero de Telephone Portable Du Client.</p></body></html>", None))
        self.labelFax.setText(_translate("GestionnairePortefeuille", "N. Fax", None))
        self.faxLineEdit.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Numero de Fax Du Client.</p></body></html>", None))
        self.faxLineEdit.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Numero de Fax Du Client.</p></body></html>", None))
        self.labelMail.setText(_translate("GestionnairePortefeuille", "E-mail", None))
        self.mailLineEdit.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Adresse Electronique Du Client.</p></body></html>", None))
        self.mailLineEdit.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Adresse Electronique Du Client.</p></body></html>", None))
        self.tableView.setToolTip(_translate("GestionnairePortefeuille", "<html><head/><body><p>Tableau Gestionnaires.</p></body></html>", None))
        self.tableView.setWhatsThis(_translate("GestionnairePortefeuille", "<html><head/><body><p>Tableau Gestionnaires.</p></body></html>", None))
        self.menu_Fichier.setTitle(_translate("GestionnairePortefeuille", "&Fichier", None))
        self.menu_Edition.setTitle(_translate("GestionnairePortefeuille", "&Edition", None))
        self.toolBar.setWindowTitle(_translate("GestionnairePortefeuille", "toolBar", None))
        self.fichierNouveau.setText(_translate("GestionnairePortefeuille", "Nouveau", None))
        self.fichierEnregistrer.setText(_translate("GestionnairePortefeuille", "Enregistrer", None))
        self.fichierFermer.setText(_translate("GestionnairePortefeuille", "Fermer", None))
        self.editionAnnuler.setText(_translate("GestionnairePortefeuille", "Annuler", None))
        self.editionPremier.setText(_translate("GestionnairePortefeuille", "Premier", None))
        self.editionPrecedent.setText(_translate("GestionnairePortefeuille", "Precedent", None))
        self.editionSuivant.setText(_translate("GestionnairePortefeuille", "Suivant", None))
        self.editionDernier.setText(_translate("GestionnairePortefeuille", "Dernier", None))
        self.editionRefaire.setText(_translate("GestionnairePortefeuille", "Refaire", None))
        self.editionRefaire.setToolTip(_translate("GestionnairePortefeuille", "Action Redo", None))
        self.fichierImprimer.setText(_translate("GestionnairePortefeuille", "Imprimer", None))
        self.fichierImprimer.setToolTip(_translate("GestionnairePortefeuille", "Imprimer", None))

import ressources_rc
