# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impressionattestation.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImpressionAttestations(object):
    def setupUi(self, ImpressionAttestations):
        ImpressionAttestations.setObjectName(_fromUtf8("ImpressionAttestations"))
        ImpressionAttestations.setWindowModality(QtCore.Qt.ApplicationModal)
        ImpressionAttestations.resize(609, 608)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        ImpressionAttestations.setFont(font)
        self.centralwidget = QtGui.QWidget(ImpressionAttestations)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frameTypePreImprime = QtGui.QFrame(self.centralwidget)
        self.frameTypePreImprime.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTypePreImprime.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTypePreImprime.setObjectName(_fromUtf8("frameTypePreImprime"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frameTypePreImprime)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelDetailsGaranties = QtGui.QLabel(self.frameTypePreImprime)
        self.labelDetailsGaranties.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDetailsGaranties.setObjectName(_fromUtf8("labelDetailsGaranties"))
        self.verticalLayout_2.addWidget(self.labelDetailsGaranties)
        self.typePieceLabel = QtGui.QLabel(self.frameTypePreImprime)
        self.typePieceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.typePieceLabel.setObjectName(_fromUtf8("typePieceLabel"))
        self.verticalLayout_2.addWidget(self.typePieceLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelNumAff = QtGui.QLabel(self.frameTypePreImprime)
        self.labelNumAff.setObjectName(_fromUtf8("labelNumAff"))
        self.horizontalLayout_2.addWidget(self.labelNumAff)
        self.numAffLineEdit = QtGui.QLineEdit(self.frameTypePreImprime)
        self.numAffLineEdit.setText(_fromUtf8(""))
        self.numAffLineEdit.setObjectName(_fromUtf8("numAffLineEdit"))
        self.horizontalLayout_2.addWidget(self.numAffLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addWidget(self.frameTypePreImprime, 2, 1, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelTypeDoc = QtGui.QLabel(self.frame_2)
        self.labelTypeDoc.setObjectName(_fromUtf8("labelTypeDoc"))
        self.gridLayout_3.addWidget(self.labelTypeDoc, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.imprimAttestToolButton = QtGui.QToolButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.imprimAttestToolButton.setFont(font)
        self.imprimAttestToolButton.setCheckable(True)
        self.imprimAttestToolButton.setChecked(True)
        self.imprimAttestToolButton.setAutoExclusive(True)
        self.imprimAttestToolButton.setObjectName(_fromUtf8("imprimAttestToolButton"))
        self.verticalLayout.addWidget(self.imprimAttestToolButton)
        self.imprimCartRosToolButton = QtGui.QToolButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.imprimCartRosToolButton.setFont(font)
        self.imprimCartRosToolButton.setCheckable(True)
        self.imprimCartRosToolButton.setAutoExclusive(True)
        self.imprimCartRosToolButton.setObjectName(_fromUtf8("imprimCartRosToolButton"))
        self.verticalLayout.addWidget(self.imprimCartRosToolButton)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.genrLineEdit = QtGui.QLineEdit(self.frame)
        self.genrLineEdit.setObjectName(_fromUtf8("genrLineEdit"))
        self.gridLayout.addWidget(self.genrLineEdit, 5, 1, 1, 1)
        self.labelMarque = QtGui.QLabel(self.frame)
        self.labelMarque.setObjectName(_fromUtf8("labelMarque"))
        self.gridLayout.addWidget(self.labelMarque, 3, 0, 1, 1)
        self.adressLineEdit = QtGui.QLineEdit(self.frame)
        self.adressLineEdit.setObjectName(_fromUtf8("adressLineEdit"))
        self.gridLayout.addWidget(self.adressLineEdit, 2, 1, 1, 1)
        self.labelDateExp = QtGui.QLabel(self.frame)
        self.labelDateExp.setObjectName(_fromUtf8("labelDateExp"))
        self.gridLayout.addWidget(self.labelDateExp, 8, 0, 1, 1)
        self.labelAdresse = QtGui.QLabel(self.frame)
        self.labelAdresse.setObjectName(_fromUtf8("labelAdresse"))
        self.gridLayout.addWidget(self.labelAdresse, 2, 0, 1, 1)
        self.labelGenre = QtGui.QLabel(self.frame)
        self.labelGenre.setObjectName(_fromUtf8("labelGenre"))
        self.gridLayout.addWidget(self.labelGenre, 5, 0, 1, 1)
        self.numPoliceLineEdit = QtGui.QLineEdit(self.frame)
        self.numPoliceLineEdit.setObjectName(_fromUtf8("numPoliceLineEdit"))
        self.gridLayout.addWidget(self.numPoliceLineEdit, 0, 1, 1, 1)
        self.dateExpLineEdit = QtGui.QLineEdit(self.frame)
        self.dateExpLineEdit.setObjectName(_fromUtf8("dateExpLineEdit"))
        self.gridLayout.addWidget(self.dateExpLineEdit, 8, 1, 1, 1)
        self.labelNom = QtGui.QLabel(self.frame)
        self.labelNom.setObjectName(_fromUtf8("labelNom"))
        self.gridLayout.addWidget(self.labelNom, 1, 0, 1, 1)
        self.labelNumPolice = QtGui.QLabel(self.frame)
        self.labelNumPolice.setObjectName(_fromUtf8("labelNumPolice"))
        self.gridLayout.addWidget(self.labelNumPolice, 0, 0, 1, 1)
        self.markLineEdit = QtGui.QLineEdit(self.frame)
        self.markLineEdit.setObjectName(_fromUtf8("markLineEdit"))
        self.gridLayout.addWidget(self.markLineEdit, 3, 1, 1, 1)
        self.labelDateEffet = QtGui.QLabel(self.frame)
        self.labelDateEffet.setObjectName(_fromUtf8("labelDateEffet"))
        self.gridLayout.addWidget(self.labelDateEffet, 7, 0, 1, 1)
        self.labelCategorieUsage = QtGui.QLabel(self.frame)
        self.labelCategorieUsage.setObjectName(_fromUtf8("labelCategorieUsage"))
        self.gridLayout.addWidget(self.labelCategorieUsage, 6, 0, 1, 1)
        self.nomLineEdit = QtGui.QLineEdit(self.frame)
        self.nomLineEdit.setObjectName(_fromUtf8("nomLineEdit"))
        self.gridLayout.addWidget(self.nomLineEdit, 1, 1, 1, 1)
        self.labelImmatriculation = QtGui.QLabel(self.frame)
        self.labelImmatriculation.setObjectName(_fromUtf8("labelImmatriculation"))
        self.gridLayout.addWidget(self.labelImmatriculation, 4, 0, 1, 1)
        self.immatLineEdit = QtGui.QLineEdit(self.frame)
        self.immatLineEdit.setObjectName(_fromUtf8("immatLineEdit"))
        self.gridLayout.addWidget(self.immatLineEdit, 4, 1, 1, 1)
        self.catUsageLineEdit = QtGui.QLineEdit(self.frame)
        self.catUsageLineEdit.setObjectName(_fromUtf8("catUsageLineEdit"))
        self.gridLayout.addWidget(self.catUsageLineEdit, 6, 1, 1, 1)
        self.dateEffetLineEdit = QtGui.QLineEdit(self.frame)
        self.dateEffetLineEdit.setObjectName(_fromUtf8("dateEffetLineEdit"))
        self.gridLayout.addWidget(self.dateEffetLineEdit, 7, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 1, 1, 1)
        self.listView = QtGui.QListView(self.centralwidget)
        self.listView.setMinimumSize(QtCore.QSize(80, 300))
        self.listView.setMaximumSize(QtCore.QSize(100, 400))
        self.listView.setAlternatingRowColors(True)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.gridLayout_2.addWidget(self.listView, 0, 0, 3, 1)
        ImpressionAttestations.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ImpressionAttestations)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Fichier = QtGui.QMenu(self.menubar)
        self.menu_Fichier.setObjectName(_fromUtf8("menu_Fichier"))
        self.menu_Edition = QtGui.QMenu(self.menubar)
        self.menu_Edition.setObjectName(_fromUtf8("menu_Edition"))
        ImpressionAttestations.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ImpressionAttestations)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ImpressionAttestations.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(ImpressionAttestations)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        ImpressionAttestations.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fichierNouveau = QtGui.QAction(ImpressionAttestations)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-new.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierNouveau.setIcon(icon)
        self.fichierNouveau.setObjectName(_fromUtf8("fichierNouveau"))
        self.fichierEnregistrer = QtGui.QAction(ImpressionAttestations)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-save.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierEnregistrer.setIcon(icon1)
        self.fichierEnregistrer.setObjectName(_fromUtf8("fichierEnregistrer"))
        self.fichierImprimer = QtGui.QAction(ImpressionAttestations)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Imprimer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierImprimer.setIcon(icon2)
        self.fichierImprimer.setObjectName(_fromUtf8("fichierImprimer"))
        self.fichierFermer = QtGui.QAction(ImpressionAttestations)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/system-log-out.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierFermer.setIcon(icon3)
        self.fichierFermer.setObjectName(_fromUtf8("fichierFermer"))
        self.editionAnnuler = QtGui.QAction(ImpressionAttestations)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-undo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionAnnuler.setIcon(icon4)
        self.editionAnnuler.setObjectName(_fromUtf8("editionAnnuler"))
        self.editionRefaire = QtGui.QAction(ImpressionAttestations)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-redo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionRefaire.setIcon(icon5)
        self.editionRefaire.setObjectName(_fromUtf8("editionRefaire"))
        self.editionPremier = QtGui.QAction(ImpressionAttestations)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-first.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPremier.setIcon(icon6)
        self.editionPremier.setObjectName(_fromUtf8("editionPremier"))
        self.editionPrecedent = QtGui.QAction(ImpressionAttestations)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-previous.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPrecedent.setIcon(icon7)
        self.editionPrecedent.setObjectName(_fromUtf8("editionPrecedent"))
        self.editionSuivant = QtGui.QAction(ImpressionAttestations)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-next.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionSuivant.setIcon(icon8)
        self.editionSuivant.setObjectName(_fromUtf8("editionSuivant"))
        self.editionDernier = QtGui.QAction(ImpressionAttestations)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-last.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionDernier.setIcon(icon9)
        self.editionDernier.setObjectName(_fromUtf8("editionDernier"))
        self.menu_Fichier.addAction(self.fichierNouveau)
        self.menu_Fichier.addAction(self.fichierEnregistrer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.fichierImprimer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.fichierFermer)
        self.menu_Edition.addAction(self.editionAnnuler)
        self.menu_Edition.addAction(self.editionRefaire)
        self.menu_Edition.addSeparator()
        self.menu_Edition.addAction(self.editionPremier)
        self.menu_Edition.addAction(self.editionPrecedent)
        self.menu_Edition.addAction(self.editionSuivant)
        self.menu_Edition.addAction(self.editionDernier)
        self.menubar.addAction(self.menu_Fichier.menuAction())
        self.menubar.addAction(self.menu_Edition.menuAction())
        self.toolBar.addAction(self.fichierNouveau)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionPremier)
        self.toolBar.addAction(self.editionPrecedent)
        self.toolBar.addAction(self.editionSuivant)
        self.toolBar.addAction(self.editionDernier)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionRefaire)
        self.toolBar.addAction(self.editionAnnuler)
        self.toolBar.addAction(self.fichierEnregistrer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierImprimer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierFermer)

        self.retranslateUi(ImpressionAttestations)
        QtCore.QObject.connect(self.imprimAttestToolButton, QtCore.SIGNAL(_fromUtf8("pressed()")), self.frameTypePreImprime.repaint)
        QtCore.QObject.connect(self.imprimCartRosToolButton, QtCore.SIGNAL(_fromUtf8("pressed()")), self.frameTypePreImprime.repaint)
        QtCore.QObject.connect(self.imprimAttestToolButton, QtCore.SIGNAL(_fromUtf8("pressed()")), self.typePieceLabel.update)
        QtCore.QObject.connect(self.imprimCartRosToolButton, QtCore.SIGNAL(_fromUtf8("pressed()")), self.typePieceLabel.update)
        QtCore.QMetaObject.connectSlotsByName(ImpressionAttestations)
        ImpressionAttestations.setTabOrder(self.numPoliceLineEdit, self.nomLineEdit)
        ImpressionAttestations.setTabOrder(self.nomLineEdit, self.adressLineEdit)
        ImpressionAttestations.setTabOrder(self.adressLineEdit, self.markLineEdit)
        ImpressionAttestations.setTabOrder(self.markLineEdit, self.immatLineEdit)
        ImpressionAttestations.setTabOrder(self.immatLineEdit, self.genrLineEdit)
        ImpressionAttestations.setTabOrder(self.genrLineEdit, self.catUsageLineEdit)
        ImpressionAttestations.setTabOrder(self.catUsageLineEdit, self.dateEffetLineEdit)
        ImpressionAttestations.setTabOrder(self.dateEffetLineEdit, self.dateExpLineEdit)
        ImpressionAttestations.setTabOrder(self.dateExpLineEdit, self.numAffLineEdit)
        ImpressionAttestations.setTabOrder(self.numAffLineEdit, self.imprimAttestToolButton)
        ImpressionAttestations.setTabOrder(self.imprimAttestToolButton, self.imprimCartRosToolButton)
        ImpressionAttestations.setTabOrder(self.imprimCartRosToolButton, self.listView)

    def retranslateUi(self, ImpressionAttestations):
        ImpressionAttestations.setWindowTitle(_translate("ImpressionAttestations", "Impression Attestations", None))
        self.labelDetailsGaranties.setText(_translate("ImpressionAttestations", "Valider ou Modifier le Numero du Preimprime", None))
        self.typePieceLabel.setText(_translate("ImpressionAttestations", "ATTESTATION dans le cas echeant.", None))
        self.labelNumAff.setText(_translate("ImpressionAttestations", "Numero a Affecter", None))
        self.numAffLineEdit.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Numero a Affecter.</p></body></html>", None))
        self.numAffLineEdit.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Numero a Affecter.</p></body></html>", None))
        self.labelTypeDoc.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Type de Document a Imprimer.</p></body></html>", None))
        self.labelTypeDoc.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Selectionnez le Type de Document a Imprimer.</p></body></html>", None))
        self.labelTypeDoc.setText(_translate("ImpressionAttestations", "Type de \n"
"Document a \n"
"Imprimer", None))
        self.imprimAttestToolButton.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Imprimer Attestation.</p></body></html>", None))
        self.imprimAttestToolButton.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Imprimer Attestation.</p></body></html>", None))
        self.imprimAttestToolButton.setText(_translate("ImpressionAttestations", "ATTESTATION", None))
        self.imprimCartRosToolButton.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Imprimer Carte Rose.</p></body></html>", None))
        self.imprimCartRosToolButton.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Imprimer Carte Rose.</p></body></html>", None))
        self.imprimCartRosToolButton.setText(_translate("ImpressionAttestations", "CARTE ROSE", None))
        self.genrLineEdit.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Genre Vehicule de l\'Assure.</p></body></html>", None))
        self.genrLineEdit.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Genre Vehicule de l\'Assure.</p></body></html>", None))
        self.labelMarque.setText(_translate("ImpressionAttestations", "Marque", None))
        self.adressLineEdit.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Adresse de l\'Assure.</p></body></html>", None))
        self.adressLineEdit.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Adresse de l\'Assure.</p></body></html>", None))
        self.labelDateExp.setText(_translate("ImpressionAttestations", "Date d\'expiration", None))
        self.labelAdresse.setText(_translate("ImpressionAttestations", "Adresse Assure", None))
        self.labelGenre.setText(_translate("ImpressionAttestations", "Genre", None))
        self.numPoliceLineEdit.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Numero de la Police.</p></body></html>", None))
        self.numPoliceLineEdit.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Numero de la Police.</p></body></html>", None))
        self.dateExpLineEdit.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Date d\'Expiration.</p></body></html>", None))
        self.dateExpLineEdit.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Date d\'Expiration.</p></body></html>", None))
        self.labelNom.setText(_translate("ImpressionAttestations", "Nom Assure", None))
        self.labelNumPolice.setText(_translate("ImpressionAttestations", "Numero Police", None))
        self.markLineEdit.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Marque Vehicule de l\'Assure.</p></body></html>", None))
        self.markLineEdit.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Marque Vehicule de l\'Assure.</p></body></html>", None))
        self.labelDateEffet.setText(_translate("ImpressionAttestations", "Date d\'effet", None))
        self.labelCategorieUsage.setText(_translate("ImpressionAttestations", "Categorie usage", None))
        self.nomLineEdit.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Nom de l\'Assure.</p></body></html>", None))
        self.nomLineEdit.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Nom de l\'Assure.</p></body></html>", None))
        self.labelImmatriculation.setText(_translate("ImpressionAttestations", "Immatriculation", None))
        self.immatLineEdit.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Immatriculation Vehicule de l\'Assure.</p></body></html>", None))
        self.immatLineEdit.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Immatriculation Vehicule de l\'Assure.</p></body></html>", None))
        self.catUsageLineEdit.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Categorie usage.</p></body></html>", None))
        self.catUsageLineEdit.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Categorie usage.</p></body></html>", None))
        self.dateEffetLineEdit.setToolTip(_translate("ImpressionAttestations", "<html><head/><body><p>Date d\'Effet.</p></body></html>", None))
        self.dateEffetLineEdit.setWhatsThis(_translate("ImpressionAttestations", "<html><head/><body><p>Date d\'Effet.</p></body></html>", None))
        self.menu_Fichier.setTitle(_translate("ImpressionAttestations", "&Fichier", None))
        self.menu_Edition.setTitle(_translate("ImpressionAttestations", "&Edition", None))
        self.toolBar.setWindowTitle(_translate("ImpressionAttestations", "toolBar", None))
        self.fichierNouveau.setText(_translate("ImpressionAttestations", "Nouveau", None))
        self.fichierEnregistrer.setText(_translate("ImpressionAttestations", "Enregistrer", None))
        self.fichierImprimer.setText(_translate("ImpressionAttestations", "Imprimer les Details des Garanties souscrites", None))
        self.fichierFermer.setText(_translate("ImpressionAttestations", "Fermer", None))
        self.editionAnnuler.setText(_translate("ImpressionAttestations", "Annuler", None))
        self.editionRefaire.setText(_translate("ImpressionAttestations", "Refaire", None))
        self.editionPremier.setText(_translate("ImpressionAttestations", "Premier", None))
        self.editionPrecedent.setText(_translate("ImpressionAttestations", "Precedent", None))
        self.editionSuivant.setText(_translate("ImpressionAttestations", "Suivant", None))
        self.editionDernier.setText(_translate("ImpressionAttestations", "Dernier", None))

import ressources_rc
