# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificationparametrage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DemandeModificationParametrages(object):
    def setupUi(self, DemandeModificationParametrages):
        DemandeModificationParametrages.setObjectName(_fromUtf8("DemandeModificationParametrages"))
        DemandeModificationParametrages.setWindowModality(QtCore.Qt.ApplicationModal)
        DemandeModificationParametrages.resize(826, 1063)
        self.centralwidget = QtGui.QWidget(DemandeModificationParametrages)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBoxNatDemande = QtGui.QGroupBox(self.frame)
        self.groupBoxNatDemande.setObjectName(_fromUtf8("groupBoxNatDemande"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBoxNatDemande)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.correctValRadioButton = QtGui.QRadioButton(self.groupBoxNatDemande)
        self.correctValRadioButton.setChecked(True)
        self.correctValRadioButton.setObjectName(_fromUtf8("correctValRadioButton"))
        self.verticalLayout_3.addWidget(self.correctValRadioButton)
        self.priseEnComptNewValRadioButton = QtGui.QRadioButton(self.groupBoxNatDemande)
        self.priseEnComptNewValRadioButton.setObjectName(_fromUtf8("priseEnComptNewValRadioButton"))
        self.verticalLayout_3.addWidget(self.priseEnComptNewValRadioButton)
        self.verticalLayout_8.addWidget(self.groupBoxNatDemande)
        self.groupBoxDomaineIntervention = QtGui.QGroupBox(self.frame)
        self.groupBoxDomaineIntervention.setObjectName(_fromUtf8("groupBoxDomaineIntervention"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxDomaineIntervention)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.geneRadioButton = QtGui.QRadioButton(self.groupBoxDomaineIntervention)
        self.geneRadioButton.setChecked(True)
        self.geneRadioButton.setObjectName(_fromUtf8("geneRadioButton"))
        self.verticalLayout_4.addWidget(self.geneRadioButton)
        self.prodRadioButton = QtGui.QRadioButton(self.groupBoxDomaineIntervention)
        self.prodRadioButton.setObjectName(_fromUtf8("prodRadioButton"))
        self.verticalLayout_4.addWidget(self.prodRadioButton)
        self.sinistrRadioButton = QtGui.QRadioButton(self.groupBoxDomaineIntervention)
        self.sinistrRadioButton.setObjectName(_fromUtf8("sinistrRadioButton"))
        self.verticalLayout_4.addWidget(self.sinistrRadioButton)
        self.verticalLayout_8.addWidget(self.groupBoxDomaineIntervention)
        self.groupBoxEntiteGeneralite = QtGui.QGroupBox(self.frame)
        self.groupBoxEntiteGeneralite.setEnabled(True)
        self.groupBoxEntiteGeneralite.setObjectName(_fromUtf8("groupBoxEntiteGeneralite"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBoxEntiteGeneralite)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.paysRadioButton = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.paysRadioButton.setObjectName(_fromUtf8("paysRadioButton"))
        self.verticalLayout_5.addWidget(self.paysRadioButton)
        self.villesRadioButton = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.villesRadioButton.setObjectName(_fromUtf8("villesRadioButton"))
        self.verticalLayout_5.addWidget(self.villesRadioButton)
        self.markVehiculRadioButton = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.markVehiculRadioButton.setObjectName(_fromUtf8("markVehiculRadioButton"))
        self.verticalLayout_5.addWidget(self.markVehiculRadioButton)
        self.sourcEnergiRadioButton = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.sourcEnergiRadioButton.setObjectName(_fromUtf8("sourcEnergiRadioButton"))
        self.verticalLayout_5.addWidget(self.sourcEnergiRadioButton)
        self.puissRadioButton = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.puissRadioButton.setObjectName(_fromUtf8("puissRadioButton"))
        self.verticalLayout_5.addWidget(self.puissRadioButton)
        self.carrossRadioButton = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.carrossRadioButton.setObjectName(_fromUtf8("carrossRadioButton"))
        self.verticalLayout_5.addWidget(self.carrossRadioButton)
        self.classSocioproRadioButton = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.classSocioproRadioButton.setObjectName(_fromUtf8("classSocioproRadioButton"))
        self.verticalLayout_5.addWidget(self.classSocioproRadioButton)
        self.professionRadioButton = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.professionRadioButton.setObjectName(_fromUtf8("professionRadioButton"))
        self.verticalLayout_5.addWidget(self.professionRadioButton)
        self.typPermiRadioButton = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.typPermiRadioButton.setObjectName(_fromUtf8("typPermiRadioButton"))
        self.verticalLayout_5.addWidget(self.typPermiRadioButton)
        self.titreCivilitRadioButton = QtGui.QRadioButton(self.groupBoxEntiteGeneralite)
        self.titreCivilitRadioButton.setObjectName(_fromUtf8("titreCivilitRadioButton"))
        self.verticalLayout_5.addWidget(self.titreCivilitRadioButton)
        self.verticalLayout_8.addWidget(self.groupBoxEntiteGeneralite)
        self.groupBoxEntiteProduction = QtGui.QGroupBox(self.frame)
        self.groupBoxEntiteProduction.setObjectName(_fromUtf8("groupBoxEntiteProduction"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBoxEntiteProduction)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.cieRadioButton = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.cieRadioButton.setObjectName(_fromUtf8("cieRadioButton"))
        self.verticalLayout_6.addWidget(self.cieRadioButton)
        self.resRadioButton = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.resRadioButton.setObjectName(_fromUtf8("resRadioButton"))
        self.verticalLayout_6.addWidget(self.resRadioButton)
        self.gestRadioButton = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.gestRadioButton.setObjectName(_fromUtf8("gestRadioButton"))
        self.verticalLayout_6.addWidget(self.gestRadioButton)
        self.clientRadioButton = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.clientRadioButton.setObjectName(_fromUtf8("clientRadioButton"))
        self.verticalLayout_6.addWidget(self.clientRadioButton)
        self.policeRadioButton = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.policeRadioButton.setObjectName(_fromUtf8("policeRadioButton"))
        self.verticalLayout_6.addWidget(self.policeRadioButton)
        self.mouvRadioButton = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.mouvRadioButton.setObjectName(_fromUtf8("mouvRadioButton"))
        self.verticalLayout_6.addWidget(self.mouvRadioButton)
        self.riskRadioButton = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.riskRadioButton.setObjectName(_fromUtf8("riskRadioButton"))
        self.verticalLayout_6.addWidget(self.riskRadioButton)
        self.garantRadioButton = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.garantRadioButton.setObjectName(_fromUtf8("garantRadioButton"))
        self.verticalLayout_6.addWidget(self.garantRadioButton)
        self.zoneTarifRadioButton = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.zoneTarifRadioButton.setObjectName(_fromUtf8("zoneTarifRadioButton"))
        self.verticalLayout_6.addWidget(self.zoneTarifRadioButton)
        self.tarifRadioButton = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.tarifRadioButton.setObjectName(_fromUtf8("tarifRadioButton"))
        self.verticalLayout_6.addWidget(self.tarifRadioButton)
        self.autreRadioButton = QtGui.QRadioButton(self.groupBoxEntiteProduction)
        self.autreRadioButton.setObjectName(_fromUtf8("autreRadioButton"))
        self.verticalLayout_6.addWidget(self.autreRadioButton)
        self.verticalLayout_8.addWidget(self.groupBoxEntiteProduction)
        self.groupBoxEntiteSinistre = QtGui.QGroupBox(self.frame)
        self.groupBoxEntiteSinistre.setEnabled(True)
        self.groupBoxEntiteSinistre.setObjectName(_fromUtf8("groupBoxEntiteSinistre"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBoxEntiteSinistre)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.cieAdvRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.cieAdvRadioButton.setObjectName(_fromUtf8("cieAdvRadioButton"))
        self.verticalLayout_7.addWidget(self.cieAdvRadioButton)
        self.expOuIntRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.expOuIntRadioButton.setObjectName(_fromUtf8("expOuIntRadioButton"))
        self.verticalLayout_7.addWidget(self.expOuIntRadioButton)
        self.natSinistrRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.natSinistrRadioButton.setObjectName(_fromUtf8("natSinistrRadioButton"))
        self.verticalLayout_7.addWidget(self.natSinistrRadioButton)
        self.statuFourniPieceRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.statuFourniPieceRadioButton.setObjectName(_fromUtf8("statuFourniPieceRadioButton"))
        self.verticalLayout_7.addWidget(self.statuFourniPieceRadioButton)
        self.etatEvoDossierRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.etatEvoDossierRadioButton.setObjectName(_fromUtf8("etatEvoDossierRadioButton"))
        self.verticalLayout_7.addWidget(self.etatEvoDossierRadioButton)
        self.listPieceAFournirRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.listPieceAFournirRadioButton.setObjectName(_fromUtf8("listPieceAFournirRadioButton"))
        self.verticalLayout_7.addWidget(self.listPieceAFournirRadioButton)
        self.natEvalRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.natEvalRadioButton.setObjectName(_fromUtf8("natEvalRadioButton"))
        self.verticalLayout_7.addWidget(self.natEvalRadioButton)
        self.typRecourRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.typRecourRadioButton.setObjectName(_fromUtf8("typRecourRadioButton"))
        self.verticalLayout_7.addWidget(self.typRecourRadioButton)
        self.objMissionExpRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.objMissionExpRadioButton.setObjectName(_fromUtf8("objMissionExpRadioButton"))
        self.verticalLayout_7.addWidget(self.objMissionExpRadioButton)
        self.etapEvoExpRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.etapEvoExpRadioButton.setObjectName(_fromUtf8("etapEvoExpRadioButton"))
        self.verticalLayout_7.addWidget(self.etapEvoExpRadioButton)
        self.postPrejudiceRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.postPrejudiceRadioButton.setObjectName(_fromUtf8("postPrejudiceRadioButton"))
        self.verticalLayout_7.addWidget(self.postPrejudiceRadioButton)
        self.objContentieuxRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.objContentieuxRadioButton.setObjectName(_fromUtf8("objContentieuxRadioButton"))
        self.verticalLayout_7.addWidget(self.objContentieuxRadioButton)
        self.juriContentieuxRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.juriContentieuxRadioButton.setObjectName(_fromUtf8("juriContentieuxRadioButton"))
        self.verticalLayout_7.addWidget(self.juriContentieuxRadioButton)
        self.objCorrespRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.objCorrespRadioButton.setObjectName(_fromUtf8("objCorrespRadioButton"))
        self.verticalLayout_7.addWidget(self.objCorrespRadioButton)
        self.natRelanceRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.natRelanceRadioButton.setObjectName(_fromUtf8("natRelanceRadioButton"))
        self.verticalLayout_7.addWidget(self.natRelanceRadioButton)
        self.qualifVictimRadioButton = QtGui.QRadioButton(self.groupBoxEntiteSinistre)
        self.qualifVictimRadioButton.setObjectName(_fromUtf8("qualifVictimRadioButton"))
        self.verticalLayout_7.addWidget(self.qualifVictimRadioButton)
        self.verticalLayout_8.addWidget(self.groupBoxEntiteSinistre)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelValAModifier = QtGui.QLabel(self.frame_2)
        self.labelValAModifier.setObjectName(_fromUtf8("labelValAModifier"))
        self.gridLayout_2.addWidget(self.labelValAModifier, 0, 0, 1, 1)
        self.valAModifLineEdit = QtGui.QLineEdit(self.frame_2)
        self.valAModifLineEdit.setObjectName(_fromUtf8("valAModifLineEdit"))
        self.gridLayout_2.addWidget(self.valAModifLineEdit, 0, 1, 1, 1)
        self.labelValAPrendreEnCompte = QtGui.QLabel(self.frame_2)
        self.labelValAPrendreEnCompte.setObjectName(_fromUtf8("labelValAPrendreEnCompte"))
        self.gridLayout_2.addWidget(self.labelValAPrendreEnCompte, 1, 0, 1, 1)
        self.valAPrendrEnComptLineEdit = QtGui.QLineEdit(self.frame_2)
        self.valAPrendrEnComptLineEdit.setObjectName(_fromUtf8("valAPrendrEnComptLineEdit"))
        self.gridLayout_2.addWidget(self.valAPrendrEnComptLineEdit, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.groupBox = QtGui.QGroupBox(self.frame_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableView = QtGui.QTableView(self.groupBox)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout.addWidget(self.tableView)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        DemandeModificationParametrages.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DemandeModificationParametrages)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Fichier = QtGui.QMenu(self.menubar)
        self.menu_Fichier.setObjectName(_fromUtf8("menu_Fichier"))
        self.menu_Edition = QtGui.QMenu(self.menubar)
        self.menu_Edition.setObjectName(_fromUtf8("menu_Edition"))
        DemandeModificationParametrages.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DemandeModificationParametrages)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DemandeModificationParametrages.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(DemandeModificationParametrages)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        DemandeModificationParametrages.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fichierNouveau = QtGui.QAction(DemandeModificationParametrages)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-new.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierNouveau.setIcon(icon)
        self.fichierNouveau.setObjectName(_fromUtf8("fichierNouveau"))
        self.fichierEnregistrer = QtGui.QAction(DemandeModificationParametrages)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-save.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierEnregistrer.setIcon(icon1)
        self.fichierEnregistrer.setObjectName(_fromUtf8("fichierEnregistrer"))
        self.fichierImprimFicheMP = QtGui.QAction(DemandeModificationParametrages)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Imprimer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierImprimFicheMP.setIcon(icon2)
        self.fichierImprimFicheMP.setObjectName(_fromUtf8("fichierImprimFicheMP"))
        self.fichierFermer = QtGui.QAction(DemandeModificationParametrages)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/system-log-out.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierFermer.setIcon(icon3)
        self.fichierFermer.setObjectName(_fromUtf8("fichierFermer"))
        self.editionAnnuler = QtGui.QAction(DemandeModificationParametrages)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-undo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionAnnuler.setIcon(icon4)
        self.editionAnnuler.setObjectName(_fromUtf8("editionAnnuler"))
        self.editionRefaire = QtGui.QAction(DemandeModificationParametrages)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-redo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionRefaire.setIcon(icon5)
        self.editionRefaire.setObjectName(_fromUtf8("editionRefaire"))
        self.editionPremier = QtGui.QAction(DemandeModificationParametrages)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-first.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPremier.setIcon(icon6)
        self.editionPremier.setObjectName(_fromUtf8("editionPremier"))
        self.editionPrecedent = QtGui.QAction(DemandeModificationParametrages)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-previous.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPrecedent.setIcon(icon7)
        self.editionPrecedent.setObjectName(_fromUtf8("editionPrecedent"))
        self.editionSuivant = QtGui.QAction(DemandeModificationParametrages)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-next.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionSuivant.setIcon(icon8)
        self.editionSuivant.setObjectName(_fromUtf8("editionSuivant"))
        self.editionDernier = QtGui.QAction(DemandeModificationParametrages)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-last.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionDernier.setIcon(icon9)
        self.editionDernier.setObjectName(_fromUtf8("editionDernier"))
        self.menu_Fichier.addAction(self.fichierNouveau)
        self.menu_Fichier.addAction(self.fichierEnregistrer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.fichierImprimFicheMP)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.fichierFermer)
        self.menu_Edition.addAction(self.editionAnnuler)
        self.menu_Edition.addAction(self.editionRefaire)
        self.menu_Edition.addSeparator()
        self.menu_Edition.addAction(self.editionPremier)
        self.menu_Edition.addAction(self.editionPrecedent)
        self.menu_Edition.addAction(self.editionSuivant)
        self.menu_Edition.addAction(self.editionDernier)
        self.menubar.addAction(self.menu_Fichier.menuAction())
        self.menubar.addAction(self.menu_Edition.menuAction())
        self.toolBar.addAction(self.fichierNouveau)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionPremier)
        self.toolBar.addAction(self.editionPrecedent)
        self.toolBar.addAction(self.editionSuivant)
        self.toolBar.addAction(self.editionDernier)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionRefaire)
        self.toolBar.addAction(self.editionAnnuler)
        self.toolBar.addAction(self.fichierEnregistrer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierImprimFicheMP)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierFermer)
        self.labelValAModifier.setBuddy(self.valAModifLineEdit)
        self.labelValAPrendreEnCompte.setBuddy(self.valAPrendrEnComptLineEdit)

        self.retranslateUi(DemandeModificationParametrages)
        QtCore.QObject.connect(self.geneRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBoxEntiteGeneralite.setVisible)
        QtCore.QObject.connect(self.prodRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBoxEntiteProduction.setVisible)
        QtCore.QObject.connect(self.sinistrRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBoxEntiteSinistre.setVisible)
        QtCore.QObject.connect(self.geneRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteProduction.hide)
        QtCore.QObject.connect(self.geneRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteSinistre.hide)
        QtCore.QObject.connect(self.prodRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteGeneralite.hide)
        QtCore.QObject.connect(self.prodRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteSinistre.hide)
        QtCore.QObject.connect(self.sinistrRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteGeneralite.hide)
        QtCore.QObject.connect(self.sinistrRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBoxEntiteProduction.hide)
        QtCore.QMetaObject.connectSlotsByName(DemandeModificationParametrages)

    def retranslateUi(self, DemandeModificationParametrages):
        DemandeModificationParametrages.setWindowTitle(_translate("DemandeModificationParametrages", "Demande De Modification De Parametrages", None))
        self.groupBoxNatDemande.setTitle(_translate("DemandeModificationParametrages", "Nature de la Demande", None))
        self.correctValRadioButton.setText(_translate("DemandeModificationParametrages", "Correction d\'une valeur erronee", None))
        self.priseEnComptNewValRadioButton.setText(_translate("DemandeModificationParametrages", "Prise en compte d\'une Nouvelle Valeur", None))
        self.groupBoxDomaineIntervention.setTitle(_translate("DemandeModificationParametrages", "Domaine d\'Intervention", None))
        self.geneRadioButton.setText(_translate("DemandeModificationParametrages", "Generalite", None))
        self.prodRadioButton.setText(_translate("DemandeModificationParametrages", "Production", None))
        self.sinistrRadioButton.setText(_translate("DemandeModificationParametrages", "Sinistre", None))
        self.groupBoxEntiteGeneralite.setTitle(_translate("DemandeModificationParametrages", "Entite des Generalites a Modifier", None))
        self.paysRadioButton.setText(_translate("DemandeModificationParametrages", "Pays", None))
        self.villesRadioButton.setText(_translate("DemandeModificationParametrages", "Villes", None))
        self.markVehiculRadioButton.setText(_translate("DemandeModificationParametrages", "Marques de Vehicule", None))
        self.sourcEnergiRadioButton.setText(_translate("DemandeModificationParametrages", "Source d\'energie", None))
        self.puissRadioButton.setText(_translate("DemandeModificationParametrages", "Puissance", None))
        self.carrossRadioButton.setText(_translate("DemandeModificationParametrages", "Carrosserie", None))
        self.classSocioproRadioButton.setText(_translate("DemandeModificationParametrages", "Classes Socioprofessionnelles", None))
        self.professionRadioButton.setText(_translate("DemandeModificationParametrages", "Professions", None))
        self.typPermiRadioButton.setText(_translate("DemandeModificationParametrages", "Types de Permis de Conduire", None))
        self.titreCivilitRadioButton.setText(_translate("DemandeModificationParametrages", "Titres de Civilite", None))
        self.groupBoxEntiteProduction.setTitle(_translate("DemandeModificationParametrages", "Entite de la Production a Modifier", None))
        self.cieRadioButton.setText(_translate("DemandeModificationParametrages", "Compagnie", None))
        self.resRadioButton.setText(_translate("DemandeModificationParametrages", "Reseau", None))
        self.gestRadioButton.setText(_translate("DemandeModificationParametrages", "Gestionnaire", None))
        self.clientRadioButton.setText(_translate("DemandeModificationParametrages", "Client", None))
        self.policeRadioButton.setText(_translate("DemandeModificationParametrages", "Police", None))
        self.mouvRadioButton.setText(_translate("DemandeModificationParametrages", "Mouvement", None))
        self.riskRadioButton.setText(_translate("DemandeModificationParametrages", "Risques", None))
        self.garantRadioButton.setText(_translate("DemandeModificationParametrages", "Garanties", None))
        self.zoneTarifRadioButton.setText(_translate("DemandeModificationParametrages", "Zone de Tarification", None))
        self.tarifRadioButton.setText(_translate("DemandeModificationParametrages", "Tarifs", None))
        self.autreRadioButton.setText(_translate("DemandeModificationParametrages", "Autres", None))
        self.groupBoxEntiteSinistre.setTitle(_translate("DemandeModificationParametrages", "Entite des Sinistres a Modifier", None))
        self.cieAdvRadioButton.setText(_translate("DemandeModificationParametrages", "Compagnies Adverses", None))
        self.expOuIntRadioButton.setText(_translate("DemandeModificationParametrages", "Expert ou Intervenant", None))
        self.natSinistrRadioButton.setText(_translate("DemandeModificationParametrages", "Nature du Sinistre", None))
        self.statuFourniPieceRadioButton.setText(_translate("DemandeModificationParametrages", "Statuts fourniture Pieces", None))
        self.etatEvoDossierRadioButton.setText(_translate("DemandeModificationParametrages", "Etats d\'Evolution des Dossiers", None))
        self.listPieceAFournirRadioButton.setText(_translate("DemandeModificationParametrages", "Liste des Pieces a fournir", None))
        self.natEvalRadioButton.setText(_translate("DemandeModificationParametrages", "Natures des Evaluations", None))
        self.typRecourRadioButton.setText(_translate("DemandeModificationParametrages", "Type de Recours", None))
        self.objMissionExpRadioButton.setText(_translate("DemandeModificationParametrages", "Objet des Missions d\'Expertise", None))
        self.etapEvoExpRadioButton.setText(_translate("DemandeModificationParametrages", "Etapes d\'Evolution des Expertises", None))
        self.postPrejudiceRadioButton.setText(_translate("DemandeModificationParametrages", "Postes de Prejudice", None))
        self.objContentieuxRadioButton.setText(_translate("DemandeModificationParametrages", "Objets de Contentieux", None))
        self.juriContentieuxRadioButton.setText(_translate("DemandeModificationParametrages", "Juridictions Contentieux", None))
        self.objCorrespRadioButton.setText(_translate("DemandeModificationParametrages", "Objets des Correspondances", None))
        self.natRelanceRadioButton.setText(_translate("DemandeModificationParametrages", "Nature des Relances", None))
        self.qualifVictimRadioButton.setText(_translate("DemandeModificationParametrages", "Qualification des Victimes", None))
        self.labelValAModifier.setText(_translate("DemandeModificationParametrages", "&Ancienne Valeur a Modifier", None))
        self.valAModifLineEdit.setToolTip(_translate("DemandeModificationParametrages", "<html><head/><body><p>Ancienne Valeur a Modifier.</p></body></html>", None))
        self.valAModifLineEdit.setWhatsThis(_translate("DemandeModificationParametrages", "<html><head/><body><p>Ancienne Valeur a Modifier.</p></body></html>", None))
        self.labelValAPrendreEnCompte.setText(_translate("DemandeModificationParametrages", "&Nouvelle Valeur a prendre en compte", None))
        self.valAPrendrEnComptLineEdit.setToolTip(_translate("DemandeModificationParametrages", "<html><head/><body><p>Nouvelle Valeur a prendre en Compte.</p></body></html>", None))
        self.valAPrendrEnComptLineEdit.setWhatsThis(_translate("DemandeModificationParametrages", "<html><head/><body><p>Nouvelle Valeur a prendre en Compte.</p></body></html>", None))
        self.groupBox.setTitle(_translate("DemandeModificationParametrages", "Liste des Valeurs Actuelles avant Modifications", None))
        self.tableView.setToolTip(_translate("DemandeModificationParametrages", "<html><head/><body><p>Liste des Valeurs Actuelles avant Modifications.</p></body></html>", None))
        self.tableView.setWhatsThis(_translate("DemandeModificationParametrages", "<html><head/><body><p>Liste des Valeurs Actuelles avant Modifications.</p></body></html>", None))
        self.menu_Fichier.setTitle(_translate("DemandeModificationParametrages", "&Fichier", None))
        self.menu_Edition.setTitle(_translate("DemandeModificationParametrages", "&Edition", None))
        self.toolBar.setWindowTitle(_translate("DemandeModificationParametrages", "toolBar", None))
        self.fichierNouveau.setText(_translate("DemandeModificationParametrages", "Nouveau", None))
        self.fichierEnregistrer.setText(_translate("DemandeModificationParametrages", "Enregistrer", None))
        self.fichierImprimFicheMP.setText(_translate("DemandeModificationParametrages", "Imprimer Fiche Modification Parametrages", None))
        self.fichierFermer.setText(_translate("DemandeModificationParametrages", "Fermer", None))
        self.editionAnnuler.setText(_translate("DemandeModificationParametrages", "Annuler", None))
        self.editionRefaire.setText(_translate("DemandeModificationParametrages", "Refaire", None))
        self.editionPremier.setText(_translate("DemandeModificationParametrages", "Premier", None))
        self.editionPrecedent.setText(_translate("DemandeModificationParametrages", "Precedent", None))
        self.editionSuivant.setText(_translate("DemandeModificationParametrages", "Suivant", None))
        self.editionDernier.setText(_translate("DemandeModificationParametrages", "Dernier", None))

import ressources_rc
