# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suivitsinistres.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SuivitSinistre(object):
    def setupUi(self, SuivitSinistre):
        SuivitSinistre.setObjectName(_fromUtf8("SuivitSinistre"))
        SuivitSinistre.setWindowModality(QtCore.Qt.ApplicationModal)
        SuivitSinistre.resize(1207, 532)
        self.centralwidget = QtGui.QWidget(SuivitSinistre)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelNumClient = QtGui.QLabel(self.frame)
        self.labelNumClient.setObjectName(_fromUtf8("labelNumClient"))
        self.gridLayout_2.addWidget(self.labelNumClient, 0, 0, 1, 1)
        self.numClientComboBox = QtGui.QComboBox(self.frame)
        self.numClientComboBox.setEditable(True)
        self.numClientComboBox.setObjectName(_fromUtf8("numClientComboBox"))
        self.gridLayout_2.addWidget(self.numClientComboBox, 0, 1, 1, 1)
        self.labelPrenom = QtGui.QLabel(self.frame)
        self.labelPrenom.setObjectName(_fromUtf8("labelPrenom"))
        self.gridLayout_2.addWidget(self.labelPrenom, 1, 0, 1, 1)
        self.prenomComboBox = QtGui.QComboBox(self.frame)
        self.prenomComboBox.setEditable(True)
        self.prenomComboBox.setObjectName(_fromUtf8("prenomComboBox"))
        self.gridLayout_2.addWidget(self.prenomComboBox, 1, 1, 1, 1)
        self.labelNom = QtGui.QLabel(self.frame)
        self.labelNom.setObjectName(_fromUtf8("labelNom"))
        self.gridLayout_2.addWidget(self.labelNom, 2, 0, 1, 1)
        self.nomComboBox = QtGui.QComboBox(self.frame)
        self.nomComboBox.setEditable(True)
        self.nomComboBox.setObjectName(_fromUtf8("nomComboBox"))
        self.gridLayout_2.addWidget(self.nomComboBox, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.frame_2)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.infoGeneTab = QtGui.QWidget()
        self.infoGeneTab.setObjectName(_fromUtf8("infoGeneTab"))
        self.tabWidget.addTab(self.infoGeneTab, _fromUtf8(""))
        self.dossiersTab = QtGui.QWidget()
        self.dossiersTab.setObjectName(_fromUtf8("dossiersTab"))
        self.tabWidget.addTab(self.dossiersTab, _fromUtf8(""))
        self.evolutionTab = QtGui.QWidget()
        self.evolutionTab.setObjectName(_fromUtf8("evolutionTab"))
        self.tabWidget.addTab(self.evolutionTab, _fromUtf8(""))
        self.piecesTab = QtGui.QWidget()
        self.piecesTab.setObjectName(_fromUtf8("piecesTab"))
        self.tabWidget.addTab(self.piecesTab, _fromUtf8(""))
        self.evaluationsTab = QtGui.QWidget()
        self.evaluationsTab.setObjectName(_fromUtf8("evaluationsTab"))
        self.tabWidget.addTab(self.evaluationsTab, _fromUtf8(""))
        self.recoursTab = QtGui.QWidget()
        self.recoursTab.setObjectName(_fromUtf8("recoursTab"))
        self.tabWidget.addTab(self.recoursTab, _fromUtf8(""))
        self.expertisesTab = QtGui.QWidget()
        self.expertisesTab.setObjectName(_fromUtf8("expertisesTab"))
        self.tabWidget.addTab(self.expertisesTab, _fromUtf8(""))
        self.contentieuxTab = QtGui.QWidget()
        self.contentieuxTab.setObjectName(_fromUtf8("contentieuxTab"))
        self.tabWidget.addTab(self.contentieuxTab, _fromUtf8(""))
        self.correspondancesTab = QtGui.QWidget()
        self.correspondancesTab.setObjectName(_fromUtf8("correspondancesTab"))
        self.tabWidget.addTab(self.correspondancesTab, _fromUtf8(""))
        self.relancesTab = QtGui.QWidget()
        self.relancesTab.setObjectName(_fromUtf8("relancesTab"))
        self.tabWidget.addTab(self.relancesTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 2, 1)
        spacerItem = QtGui.QSpacerItem(20, 365, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        SuivitSinistre.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SuivitSinistre)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1207, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Fichier = QtGui.QMenu(self.menubar)
        self.menu_Fichier.setObjectName(_fromUtf8("menu_Fichier"))
        self.menu_Edition = QtGui.QMenu(self.menubar)
        self.menu_Edition.setObjectName(_fromUtf8("menu_Edition"))
        SuivitSinistre.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SuivitSinistre)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SuivitSinistre.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(SuivitSinistre)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        SuivitSinistre.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fichierNouveau = QtGui.QAction(SuivitSinistre)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-new.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierNouveau.setIcon(icon)
        self.fichierNouveau.setObjectName(_fromUtf8("fichierNouveau"))
        self.fichierEnregistrer = QtGui.QAction(SuivitSinistre)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-save.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierEnregistrer.setIcon(icon1)
        self.fichierEnregistrer.setObjectName(_fromUtf8("fichierEnregistrer"))
        self.fichierImprimer = QtGui.QAction(SuivitSinistre)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Imprimer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierImprimer.setIcon(icon2)
        self.fichierImprimer.setObjectName(_fromUtf8("fichierImprimer"))
        self.fichierFermer = QtGui.QAction(SuivitSinistre)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/system-log-out.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierFermer.setIcon(icon3)
        self.fichierFermer.setObjectName(_fromUtf8("fichierFermer"))
        self.editionAnnuler = QtGui.QAction(SuivitSinistre)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-undo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionAnnuler.setIcon(icon4)
        self.editionAnnuler.setObjectName(_fromUtf8("editionAnnuler"))
        self.editionRefaire = QtGui.QAction(SuivitSinistre)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-redo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionRefaire.setIcon(icon5)
        self.editionRefaire.setObjectName(_fromUtf8("editionRefaire"))
        self.editionPremier = QtGui.QAction(SuivitSinistre)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-first.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPremier.setIcon(icon6)
        self.editionPremier.setObjectName(_fromUtf8("editionPremier"))
        self.editionPrecedent = QtGui.QAction(SuivitSinistre)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-previous.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPrecedent.setIcon(icon7)
        self.editionPrecedent.setObjectName(_fromUtf8("editionPrecedent"))
        self.editionSuivant = QtGui.QAction(SuivitSinistre)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-next.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionSuivant.setIcon(icon8)
        self.editionSuivant.setObjectName(_fromUtf8("editionSuivant"))
        self.editionDernier = QtGui.QAction(SuivitSinistre)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-last.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionDernier.setIcon(icon9)
        self.editionDernier.setObjectName(_fromUtf8("editionDernier"))
        self.menu_Fichier.addAction(self.fichierNouveau)
        self.menu_Fichier.addAction(self.fichierEnregistrer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.fichierImprimer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.fichierFermer)
        self.menu_Edition.addAction(self.editionAnnuler)
        self.menu_Edition.addAction(self.editionRefaire)
        self.menu_Edition.addSeparator()
        self.menu_Edition.addAction(self.editionPremier)
        self.menu_Edition.addAction(self.editionPrecedent)
        self.menu_Edition.addAction(self.editionSuivant)
        self.menu_Edition.addAction(self.editionDernier)
        self.menubar.addAction(self.menu_Fichier.menuAction())
        self.menubar.addAction(self.menu_Edition.menuAction())
        self.toolBar.addAction(self.fichierNouveau)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionPremier)
        self.toolBar.addAction(self.editionPrecedent)
        self.toolBar.addAction(self.editionSuivant)
        self.toolBar.addAction(self.editionDernier)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionRefaire)
        self.toolBar.addAction(self.editionAnnuler)
        self.toolBar.addAction(self.fichierEnregistrer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierImprimer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierFermer)
        self.labelNumClient.setBuddy(self.numClientComboBox)
        self.labelPrenom.setBuddy(self.prenomComboBox)
        self.labelNom.setBuddy(self.nomComboBox)

        self.retranslateUi(SuivitSinistre)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SuivitSinistre)
        SuivitSinistre.setTabOrder(self.numClientComboBox, self.prenomComboBox)
        SuivitSinistre.setTabOrder(self.prenomComboBox, self.nomComboBox)
        SuivitSinistre.setTabOrder(self.nomComboBox, self.tabWidget)

    def retranslateUi(self, SuivitSinistre):
        SuivitSinistre.setWindowTitle(_translate("SuivitSinistre", "Suivit Sinistre", None))
        self.labelNumClient.setText(_translate("SuivitSinistre", "Numero &Client", None))
        self.numClientComboBox.setToolTip(_translate("SuivitSinistre", "<html><head/><body><p>Numero Client.</p></body></html>", None))
        self.numClientComboBox.setWhatsThis(_translate("SuivitSinistre", "<html><head/><body><p>Numero Client.</p></body></html>", None))
        self.labelPrenom.setText(_translate("SuivitSinistre", "&Prenom", None))
        self.prenomComboBox.setToolTip(_translate("SuivitSinistre", "<html><head/><body><p>Prenom Client.</p></body></html>", None))
        self.prenomComboBox.setWhatsThis(_translate("SuivitSinistre", "<html><head/><body><p>Prenom Client.</p></body></html>", None))
        self.labelNom.setText(_translate("SuivitSinistre", "&Nom", None))
        self.nomComboBox.setToolTip(_translate("SuivitSinistre", "<html><head/><body><p>Nom Client.</p></body></html>", None))
        self.nomComboBox.setWhatsThis(_translate("SuivitSinistre", "<html><head/><body><p>Nom Client.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoGeneTab), _translate("SuivitSinistre", "Informations Generales", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dossiersTab), _translate("SuivitSinistre", "Dossiers", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.evolutionTab), _translate("SuivitSinistre", "Evolution", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.piecesTab), _translate("SuivitSinistre", "Pieces", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.evaluationsTab), _translate("SuivitSinistre", "Evaluations", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recoursTab), _translate("SuivitSinistre", "Recours", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.expertisesTab), _translate("SuivitSinistre", "Expertises", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contentieuxTab), _translate("SuivitSinistre", "Contentieux", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.correspondancesTab), _translate("SuivitSinistre", "Correspondances", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.relancesTab), _translate("SuivitSinistre", "Relances", None))
        self.menu_Fichier.setTitle(_translate("SuivitSinistre", "&Fichier", None))
        self.menu_Edition.setTitle(_translate("SuivitSinistre", "&Edition", None))
        self.toolBar.setWindowTitle(_translate("SuivitSinistre", "toolBar", None))
        self.fichierNouveau.setText(_translate("SuivitSinistre", "Nouveau", None))
        self.fichierEnregistrer.setText(_translate("SuivitSinistre", "Enregistrer", None))
        self.fichierImprimer.setText(_translate("SuivitSinistre", "Imprimer Fiche Suivit des Sinistres", None))
        self.fichierFermer.setText(_translate("SuivitSinistre", "Fermer", None))
        self.editionAnnuler.setText(_translate("SuivitSinistre", "Annuler", None))
        self.editionRefaire.setText(_translate("SuivitSinistre", "Refaire", None))
        self.editionPremier.setText(_translate("SuivitSinistre", "Premier", None))
        self.editionPrecedent.setText(_translate("SuivitSinistre", "Precedent", None))
        self.editionSuivant.setText(_translate("SuivitSinistre", "Suivant", None))
        self.editionDernier.setText(_translate("SuivitSinistre", "Dernier", None))

import ressources_rc
