# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suivitvictimesinistre.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_VictimesSinistre(object):
    def setupUi(self, VictimesSinistre):
        VictimesSinistre.setObjectName(_fromUtf8("VictimesSinistre"))
        VictimesSinistre.setWindowModality(QtCore.Qt.ApplicationModal)
        VictimesSinistre.resize(1088, 736)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        VictimesSinistre.setFont(font)
        VictimesSinistre.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(VictimesSinistre)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelVictimesEnregistrees = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelVictimesEnregistrees.setFont(font)
        self.labelVictimesEnregistrees.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVictimesEnregistrees.setObjectName(_fromUtf8("labelVictimesEnregistrees"))
        self.verticalLayout.addWidget(self.labelVictimesEnregistrees)
        self.victimesEnregistreesListView = QtGui.QListView(self.centralwidget)
        self.victimesEnregistreesListView.setMinimumSize(QtCore.QSize(200, 550))
        self.victimesEnregistreesListView.setMaximumSize(QtCore.QSize(250, 600))
        self.victimesEnregistreesListView.setAlternatingRowColors(True)
        self.victimesEnregistreesListView.setObjectName(_fromUtf8("victimesEnregistreesListView"))
        self.verticalLayout.addWidget(self.victimesEnregistreesListView)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_id_victime = QtGui.QWidget()
        self.tab_id_victime.setObjectName(_fromUtf8("tab_id_victime"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_id_victime)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame_8 = QtGui.QFrame(self.tab_id_victime)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.labelNumId = QtGui.QLabel(self.frame_8)
        self.labelNumId.setObjectName(_fromUtf8("labelNumId"))
        self.gridLayout_5.addWidget(self.labelNumId, 0, 0, 1, 1)
        self.numIdComboBox = QtGui.QComboBox(self.frame_8)
        self.numIdComboBox.setObjectName(_fromUtf8("numIdComboBox"))
        self.gridLayout_5.addWidget(self.numIdComboBox, 0, 1, 1, 1)
        self.labelPrenom = QtGui.QLabel(self.frame_8)
        self.labelPrenom.setObjectName(_fromUtf8("labelPrenom"))
        self.gridLayout_5.addWidget(self.labelPrenom, 1, 0, 1, 1)
        self.prenomComboBox = QtGui.QComboBox(self.frame_8)
        self.prenomComboBox.setObjectName(_fromUtf8("prenomComboBox"))
        self.gridLayout_5.addWidget(self.prenomComboBox, 1, 1, 1, 1)
        self.labelNom = QtGui.QLabel(self.frame_8)
        self.labelNom.setObjectName(_fromUtf8("labelNom"))
        self.gridLayout_5.addWidget(self.labelNom, 2, 0, 1, 1)
        self.nomComboBox = QtGui.QComboBox(self.frame_8)
        self.nomComboBox.setObjectName(_fromUtf8("nomComboBox"))
        self.gridLayout_5.addWidget(self.nomComboBox, 2, 1, 1, 1)
        self.labelProfession = QtGui.QLabel(self.frame_8)
        self.labelProfession.setObjectName(_fromUtf8("labelProfession"))
        self.gridLayout_5.addWidget(self.labelProfession, 3, 0, 1, 1)
        self.professionComboBox = QtGui.QComboBox(self.frame_8)
        self.professionComboBox.setObjectName(_fromUtf8("professionComboBox"))
        self.gridLayout_5.addWidget(self.professionComboBox, 3, 1, 1, 1)
        self.labelCivilite = QtGui.QLabel(self.frame_8)
        self.labelCivilite.setObjectName(_fromUtf8("labelCivilite"))
        self.gridLayout_5.addWidget(self.labelCivilite, 4, 0, 1, 1)
        self.civiliteComboBox = QtGui.QComboBox(self.frame_8)
        self.civiliteComboBox.setObjectName(_fromUtf8("civiliteComboBox"))
        self.gridLayout_5.addWidget(self.civiliteComboBox, 4, 1, 1, 1)
        self.labelLocalisation = QtGui.QLabel(self.frame_8)
        self.labelLocalisation.setObjectName(_fromUtf8("labelLocalisation"))
        self.gridLayout_5.addWidget(self.labelLocalisation, 5, 0, 1, 1)
        self.localisationComboBox = QtGui.QComboBox(self.frame_8)
        self.localisationComboBox.setObjectName(_fromUtf8("localisationComboBox"))
        self.gridLayout_5.addWidget(self.localisationComboBox, 5, 1, 1, 1)
        self.labelBP = QtGui.QLabel(self.frame_8)
        self.labelBP.setObjectName(_fromUtf8("labelBP"))
        self.gridLayout_5.addWidget(self.labelBP, 6, 0, 1, 1)
        self.bpLineEdit = QtGui.QLineEdit(self.frame_8)
        self.bpLineEdit.setObjectName(_fromUtf8("bpLineEdit"))
        self.gridLayout_5.addWidget(self.bpLineEdit, 6, 1, 1, 1)
        self.labelVille = QtGui.QLabel(self.frame_8)
        self.labelVille.setObjectName(_fromUtf8("labelVille"))
        self.gridLayout_5.addWidget(self.labelVille, 7, 0, 1, 1)
        self.villeComboBox = QtGui.QComboBox(self.frame_8)
        self.villeComboBox.setObjectName(_fromUtf8("villeComboBox"))
        self.gridLayout_5.addWidget(self.villeComboBox, 7, 1, 1, 1)
        self.labelAdresse = QtGui.QLabel(self.frame_8)
        self.labelAdresse.setObjectName(_fromUtf8("labelAdresse"))
        self.gridLayout_5.addWidget(self.labelAdresse, 8, 0, 1, 1)
        self.adressLineEdit = QtGui.QLineEdit(self.frame_8)
        self.adressLineEdit.setObjectName(_fromUtf8("adressLineEdit"))
        self.gridLayout_5.addWidget(self.adressLineEdit, 8, 1, 1, 1)
        self.labelSociete = QtGui.QLabel(self.frame_8)
        self.labelSociete.setObjectName(_fromUtf8("labelSociete"))
        self.gridLayout_5.addWidget(self.labelSociete, 9, 0, 1, 1)
        self.steLineEdit = QtGui.QLineEdit(self.frame_8)
        self.steLineEdit.setObjectName(_fromUtf8("steLineEdit"))
        self.gridLayout_5.addWidget(self.steLineEdit, 9, 1, 1, 1)
        self.labelPoste = QtGui.QLabel(self.frame_8)
        self.labelPoste.setObjectName(_fromUtf8("labelPoste"))
        self.gridLayout_5.addWidget(self.labelPoste, 10, 0, 1, 1)
        self.posteLineEdit = QtGui.QLineEdit(self.frame_8)
        self.posteLineEdit.setObjectName(_fromUtf8("posteLineEdit"))
        self.gridLayout_5.addWidget(self.posteLineEdit, 10, 1, 1, 1)
        self.labelDepartement = QtGui.QLabel(self.frame_8)
        self.labelDepartement.setObjectName(_fromUtf8("labelDepartement"))
        self.gridLayout_5.addWidget(self.labelDepartement, 11, 0, 1, 1)
        self.deptComboBox = QtGui.QComboBox(self.frame_8)
        self.deptComboBox.setObjectName(_fromUtf8("deptComboBox"))
        self.gridLayout_5.addWidget(self.deptComboBox, 11, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_8, 0, 0, 2, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame_7 = QtGui.QFrame(self.tab_id_victime)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.labelPhoneBureau = QtGui.QLabel(self.frame_7)
        self.labelPhoneBureau.setObjectName(_fromUtf8("labelPhoneBureau"))
        self.gridLayout_9.addWidget(self.labelPhoneBureau, 0, 0, 1, 1)
        self.PhoneWLineEdit = QtGui.QLineEdit(self.frame_7)
        self.PhoneWLineEdit.setObjectName(_fromUtf8("PhoneWLineEdit"))
        self.gridLayout_9.addWidget(self.PhoneWLineEdit, 0, 1, 1, 1)
        self.labelPhonePortable = QtGui.QLabel(self.frame_7)
        self.labelPhonePortable.setObjectName(_fromUtf8("labelPhonePortable"))
        self.gridLayout_9.addWidget(self.labelPhonePortable, 1, 0, 1, 1)
        self.PhoneHLineEdit = QtGui.QLineEdit(self.frame_7)
        self.PhoneHLineEdit.setObjectName(_fromUtf8("PhoneHLineEdit"))
        self.gridLayout_9.addWidget(self.PhoneHLineEdit, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_9)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.labelFax = QtGui.QLabel(self.frame_7)
        self.labelFax.setObjectName(_fromUtf8("labelFax"))
        self.gridLayout_10.addWidget(self.labelFax, 0, 0, 1, 1)
        self.faxLineEdit = QtGui.QLineEdit(self.frame_7)
        self.faxLineEdit.setObjectName(_fromUtf8("faxLineEdit"))
        self.gridLayout_10.addWidget(self.faxLineEdit, 0, 1, 1, 1)
        self.labelMail = QtGui.QLabel(self.frame_7)
        self.labelMail.setObjectName(_fromUtf8("labelMail"))
        self.gridLayout_10.addWidget(self.labelMail, 1, 0, 1, 1)
        self.mailLineEdit = QtGui.QLineEdit(self.frame_7)
        self.mailLineEdit.setObjectName(_fromUtf8("mailLineEdit"))
        self.gridLayout_10.addWidget(self.mailLineEdit, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_10)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.frame_7)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.frame = QtGui.QFrame(self.tab_id_victime)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelEtatCivilVictime = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelEtatCivilVictime.setFont(font)
        self.labelEtatCivilVictime.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEtatCivilVictime.setObjectName(_fromUtf8("labelEtatCivilVictime"))
        self.gridLayout_2.addWidget(self.labelEtatCivilVictime, 0, 0, 1, 2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelPieceIdOfficielle = QtGui.QLabel(self.frame)
        self.labelPieceIdOfficielle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPieceIdOfficielle.setObjectName(_fromUtf8("labelPieceIdOfficielle"))
        self.gridLayout.addWidget(self.labelPieceIdOfficielle, 0, 0, 1, 2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelNumCni = QtGui.QLabel(self.frame)
        self.labelNumCni.setObjectName(_fromUtf8("labelNumCni"))
        self.gridLayout_6.addWidget(self.labelNumCni, 0, 0, 1, 1)
        self.numCniLineEdit = QtGui.QLineEdit(self.frame)
        self.numCniLineEdit.setObjectName(_fromUtf8("numCniLineEdit"))
        self.gridLayout_6.addWidget(self.numCniLineEdit, 0, 1, 1, 1)
        self.labelValidite = QtGui.QLabel(self.frame)
        self.labelValidite.setObjectName(_fromUtf8("labelValidite"))
        self.gridLayout_6.addWidget(self.labelValidite, 1, 0, 1, 1)
        self.validiteDateEdit = QtGui.QDateEdit(self.frame)
        self.validiteDateEdit.setObjectName(_fromUtf8("validiteDateEdit"))
        self.gridLayout_6.addWidget(self.validiteDateEdit, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labelDateDelivrance = QtGui.QLabel(self.frame)
        self.labelDateDelivrance.setObjectName(_fromUtf8("labelDateDelivrance"))
        self.gridLayout_7.addWidget(self.labelDateDelivrance, 0, 0, 1, 1)
        self.dateDelivranceDateEdit = QtGui.QDateEdit(self.frame)
        self.dateDelivranceDateEdit.setObjectName(_fromUtf8("dateDelivranceDateEdit"))
        self.gridLayout_7.addWidget(self.dateDelivranceDateEdit, 0, 1, 1, 1)
        self.labelLieuDelivrance = QtGui.QLabel(self.frame)
        self.labelLieuDelivrance.setObjectName(_fromUtf8("labelLieuDelivrance"))
        self.gridLayout_7.addWidget(self.labelLieuDelivrance, 1, 0, 1, 1)
        self.lieuDelivranceLineEdit = QtGui.QLineEdit(self.frame)
        self.lieuDelivranceLineEdit.setObjectName(_fromUtf8("lieuDelivranceLineEdit"))
        self.gridLayout_7.addWidget(self.lieuDelivranceLineEdit, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.statutMatComboBox = QtGui.QComboBox(self.frame)
        self.statutMatComboBox.setObjectName(_fromUtf8("statutMatComboBox"))
        self.gridLayout_11.addWidget(self.statutMatComboBox, 0, 1, 1, 1)
        self.labelStatutMat = QtGui.QLabel(self.frame)
        self.labelStatutMat.setObjectName(_fromUtf8("labelStatutMat"))
        self.gridLayout_11.addWidget(self.labelStatutMat, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.labelLieuNaiss = QtGui.QLabel(self.frame)
        self.labelLieuNaiss.setObjectName(_fromUtf8("labelLieuNaiss"))
        self.gridLayout_8.addWidget(self.labelLieuNaiss, 0, 0, 1, 1)
        self.lieuNaissLineEdit = QtGui.QLineEdit(self.frame)
        self.lieuNaissLineEdit.setObjectName(_fromUtf8("lieuNaissLineEdit"))
        self.gridLayout_8.addWidget(self.lieuNaissLineEdit, 0, 1, 1, 1)
        self.labelDateNaiss = QtGui.QLabel(self.frame)
        self.labelDateNaiss.setObjectName(_fromUtf8("labelDateNaiss"))
        self.gridLayout_8.addWidget(self.labelDateNaiss, 1, 0, 1, 1)
        self.dateNaissDateEdit = QtGui.QDateEdit(self.frame)
        self.dateNaissDateEdit.setObjectName(_fromUtf8("dateNaissDateEdit"))
        self.gridLayout_8.addWidget(self.dateNaissDateEdit, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame_2 = QtGui.QFrame(self.tab_id_victime)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelListeSinistresVictime = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelListeSinistresVictime.setFont(font)
        self.labelListeSinistresVictime.setAlignment(QtCore.Qt.AlignCenter)
        self.labelListeSinistresVictime.setObjectName(_fromUtf8("labelListeSinistresVictime"))
        self.verticalLayout_4.addWidget(self.labelListeSinistresVictime)
        self.listeSinistresVictimeTableView = QtGui.QTableView(self.frame_2)
        self.listeSinistresVictimeTableView.setAlternatingRowColors(True)
        self.listeSinistresVictimeTableView.setObjectName(_fromUtf8("listeSinistresVictimeTableView"))
        self.verticalLayout_4.addWidget(self.listeSinistresVictimeTableView)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.tab_id_victime)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.labelAssureurVictimesSinistre = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelAssureurVictimesSinistre.setFont(font)
        self.labelAssureurVictimesSinistre.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAssureurVictimesSinistre.setObjectName(_fromUtf8("labelAssureurVictimesSinistre"))
        self.verticalLayout_3.addWidget(self.labelAssureurVictimesSinistre)
        self.assureurVictimeSinistreTableView = QtGui.QTableView(self.frame_3)
        self.assureurVictimeSinistreTableView.setAlternatingRowColors(True)
        self.assureurVictimeSinistreTableView.setObjectName(_fromUtf8("assureurVictimeSinistreTableView"))
        self.verticalLayout_3.addWidget(self.assureurVictimeSinistreTableView)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_id_victime, _fromUtf8(""))
        self.tab_traitementdoc = QtGui.QWidget()
        self.tab_traitementdoc.setObjectName(_fromUtf8("tab_traitementdoc"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_traitementdoc)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame_5 = QtGui.QFrame(self.tab_traitementdoc)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.labelEtatActuelVictime = QtGui.QLabel(self.frame_5)
        self.labelEtatActuelVictime.setObjectName(_fromUtf8("labelEtatActuelVictime"))
        self.gridLayout_13.addWidget(self.labelEtatActuelVictime, 0, 0, 1, 1)
        self.etatActuelVictimComboBox = QtGui.QComboBox(self.frame_5)
        self.etatActuelVictimComboBox.setObjectName(_fromUtf8("etatActuelVictimComboBox"))
        self.gridLayout_13.addWidget(self.etatActuelVictimComboBox, 0, 1, 1, 1)
        self.labelProfessionVictime = QtGui.QLabel(self.frame_5)
        self.labelProfessionVictime.setObjectName(_fromUtf8("labelProfessionVictime"))
        self.gridLayout_13.addWidget(self.labelProfessionVictime, 1, 0, 1, 1)
        self.professionVictimComboBox = QtGui.QComboBox(self.frame_5)
        self.professionVictimComboBox.setObjectName(_fromUtf8("professionVictimComboBox"))
        self.gridLayout_13.addWidget(self.professionVictimComboBox, 1, 1, 1, 1)
        self.labelDescDommages = QtGui.QLabel(self.frame_5)
        self.labelDescDommages.setObjectName(_fromUtf8("labelDescDommages"))
        self.gridLayout_13.addWidget(self.labelDescDommages, 2, 0, 1, 1)
        self.descDommageComboBox = QtGui.QComboBox(self.frame_5)
        self.descDommageComboBox.setObjectName(_fromUtf8("descDommageComboBox"))
        self.gridLayout_13.addWidget(self.descDommageComboBox, 2, 1, 1, 1)
        self.labelNatDommages = QtGui.QLabel(self.frame_5)
        self.labelNatDommages.setObjectName(_fromUtf8("labelNatDommages"))
        self.gridLayout_13.addWidget(self.labelNatDommages, 3, 0, 1, 1)
        self.natDommageComboBox = QtGui.QComboBox(self.frame_5)
        self.natDommageComboBox.setObjectName(_fromUtf8("natDommageComboBox"))
        self.gridLayout_13.addWidget(self.natDommageComboBox, 3, 1, 1, 1)
        self.labelDescPrejudices = QtGui.QLabel(self.frame_5)
        self.labelDescPrejudices.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelDescPrejudices.setObjectName(_fromUtf8("labelDescPrejudices"))
        self.gridLayout_13.addWidget(self.labelDescPrejudices, 4, 0, 1, 1)
        self.DescPrejudiceVictimTextEdit = QtGui.QTextEdit(self.frame_5)
        self.DescPrejudiceVictimTextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.DescPrejudiceVictimTextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.DescPrejudiceVictimTextEdit.setObjectName(_fromUtf8("DescPrejudiceVictimTextEdit"))
        self.gridLayout_13.addWidget(self.DescPrejudiceVictimTextEdit, 4, 1, 1, 1)
        self.labelNatLesions = QtGui.QLabel(self.frame_5)
        self.labelNatLesions.setObjectName(_fromUtf8("labelNatLesions"))
        self.gridLayout_13.addWidget(self.labelNatLesions, 5, 0, 1, 1)
        self.natLesionComboBox = QtGui.QComboBox(self.frame_5)
        self.natLesionComboBox.setObjectName(_fromUtf8("natLesionComboBox"))
        self.gridLayout_13.addWidget(self.natLesionComboBox, 5, 1, 1, 1)
        self.labelAgeVictime = QtGui.QLabel(self.frame_5)
        self.labelAgeVictime.setObjectName(_fromUtf8("labelAgeVictime"))
        self.gridLayout_13.addWidget(self.labelAgeVictime, 6, 0, 1, 1)
        self.ageVictimSpinBox = QtGui.QSpinBox(self.frame_5)
        self.ageVictimSpinBox.setObjectName(_fromUtf8("ageVictimSpinBox"))
        self.gridLayout_13.addWidget(self.ageVictimSpinBox, 6, 1, 1, 1)
        self.labelDureeProbHosp = QtGui.QLabel(self.frame_5)
        self.labelDureeProbHosp.setObjectName(_fromUtf8("labelDureeProbHosp"))
        self.gridLayout_13.addWidget(self.labelDureeProbHosp, 7, 0, 1, 1)
        self.dureeProbHospSpinBox = QtGui.QSpinBox(self.frame_5)
        self.dureeProbHospSpinBox.setObjectName(_fromUtf8("dureeProbHospSpinBox"))
        self.gridLayout_13.addWidget(self.dureeProbHospSpinBox, 7, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_6 = QtGui.QFrame(self.tab_traitementdoc)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.labelStatutMatVictime = QtGui.QLabel(self.frame_6)
        self.labelStatutMatVictime.setObjectName(_fromUtf8("labelStatutMatVictime"))
        self.gridLayout_12.addWidget(self.labelStatutMatVictime, 0, 0, 1, 1)
        self.statutMatVictimComboBox = QtGui.QComboBox(self.frame_6)
        self.statutMatVictimComboBox.setObjectName(_fromUtf8("statutMatVictimComboBox"))
        self.gridLayout_12.addWidget(self.statutMatVictimComboBox, 0, 1, 1, 1)
        self.labelParenteAvecAssure = QtGui.QLabel(self.frame_6)
        self.labelParenteAvecAssure.setObjectName(_fromUtf8("labelParenteAvecAssure"))
        self.gridLayout_12.addWidget(self.labelParenteAvecAssure, 1, 0, 1, 1)
        self.parenteAvecAssureComboBox = QtGui.QComboBox(self.frame_6)
        self.parenteAvecAssureComboBox.setObjectName(_fromUtf8("parenteAvecAssureComboBox"))
        self.gridLayout_12.addWidget(self.parenteAvecAssureComboBox, 1, 1, 1, 1)
        self.labelParenteAvecConducteur = QtGui.QLabel(self.frame_6)
        self.labelParenteAvecConducteur.setObjectName(_fromUtf8("labelParenteAvecConducteur"))
        self.gridLayout_12.addWidget(self.labelParenteAvecConducteur, 2, 0, 1, 1)
        self.parenteAvecConducteurComboBox = QtGui.QComboBox(self.frame_6)
        self.parenteAvecConducteurComboBox.setObjectName(_fromUtf8("parenteAvecConducteurComboBox"))
        self.gridLayout_12.addWidget(self.parenteAvecConducteurComboBox, 2, 1, 1, 1)
        self.labelEmplacementVictimeAuSinistre = QtGui.QLabel(self.frame_6)
        self.labelEmplacementVictimeAuSinistre.setObjectName(_fromUtf8("labelEmplacementVictimeAuSinistre"))
        self.gridLayout_12.addWidget(self.labelEmplacementVictimeAuSinistre, 3, 0, 1, 1)
        self.emplacementVictimAuSinistrComboBox = QtGui.QComboBox(self.frame_6)
        self.emplacementVictimAuSinistrComboBox.setObjectName(_fromUtf8("emplacementVictimAuSinistrComboBox"))
        self.gridLayout_12.addWidget(self.emplacementVictimAuSinistrComboBox, 3, 1, 1, 1)
        self.labelDestinationVictimeApresSinistre = QtGui.QLabel(self.frame_6)
        self.labelDestinationVictimeApresSinistre.setObjectName(_fromUtf8("labelDestinationVictimeApresSinistre"))
        self.gridLayout_12.addWidget(self.labelDestinationVictimeApresSinistre, 4, 0, 1, 1)
        self.destVictimApresSinistrComboBox = QtGui.QComboBox(self.frame_6)
        self.destVictimApresSinistrComboBox.setObjectName(_fromUtf8("destVictimApresSinistrComboBox"))
        self.gridLayout_12.addWidget(self.destVictimApresSinistrComboBox, 4, 1, 1, 1)
        self.labelConclusionsCertificatMedical = QtGui.QLabel(self.frame_6)
        self.labelConclusionsCertificatMedical.setObjectName(_fromUtf8("labelConclusionsCertificatMedical"))
        self.gridLayout_12.addWidget(self.labelConclusionsCertificatMedical, 5, 0, 1, 1)
        self.conclusionCertificatMedicalComboBox = QtGui.QComboBox(self.frame_6)
        self.conclusionCertificatMedicalComboBox.setObjectName(_fromUtf8("conclusionCertificatMedicalComboBox"))
        self.gridLayout_12.addWidget(self.conclusionCertificatMedicalComboBox, 5, 1, 1, 1)
        self.labelObsSurVictime = QtGui.QLabel(self.frame_6)
        self.labelObsSurVictime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelObsSurVictime.setObjectName(_fromUtf8("labelObsSurVictime"))
        self.gridLayout_12.addWidget(self.labelObsSurVictime, 6, 0, 1, 1)
        self.ObsSurVictimTextEdit = QtGui.QTextEdit(self.frame_6)
        self.ObsSurVictimTextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.ObsSurVictimTextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ObsSurVictimTextEdit.setObjectName(_fromUtf8("ObsSurVictimTextEdit"))
        self.gridLayout_12.addWidget(self.ObsSurVictimTextEdit, 6, 1, 1, 1)
        self.labelMontantEstime = QtGui.QLabel(self.frame_6)
        self.labelMontantEstime.setObjectName(_fromUtf8("labelMontantEstime"))
        self.gridLayout_12.addWidget(self.labelMontantEstime, 7, 0, 1, 1)
        self.montantEstimeLineEdit = QtGui.QLineEdit(self.frame_6)
        self.montantEstimeLineEdit.setObjectName(_fromUtf8("montantEstimeLineEdit"))
        self.gridLayout_12.addWidget(self.montantEstimeLineEdit, 7, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_6, 0, 1, 1, 1)
        self.frame_4 = QtGui.QFrame(self.tab_traitementdoc)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.labelAnalysePrejudices = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelAnalysePrejudices.setFont(font)
        self.labelAnalysePrejudices.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAnalysePrejudices.setObjectName(_fromUtf8("labelAnalysePrejudices"))
        self.verticalLayout_6.addWidget(self.labelAnalysePrejudices)
        self.analysePrejudicesVictimeTableView = QtGui.QTableView(self.frame_4)
        self.analysePrejudicesVictimeTableView.setMinimumSize(QtCore.QSize(0, 200))
        self.analysePrejudicesVictimeTableView.setMaximumSize(QtCore.QSize(16777215, 250))
        self.analysePrejudicesVictimeTableView.setAlternatingRowColors(True)
        self.analysePrejudicesVictimeTableView.setObjectName(_fromUtf8("analysePrejudicesVictimeTableView"))
        self.verticalLayout_6.addWidget(self.analysePrejudicesVictimeTableView)
        self.gridLayout_4.addWidget(self.frame_4, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_traitementdoc, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.tabWidget)
        VictimesSinistre.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(VictimesSinistre)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Fichier = QtGui.QMenu(self.menubar)
        self.menu_Fichier.setObjectName(_fromUtf8("menu_Fichier"))
        self.menu_Edition = QtGui.QMenu(self.menubar)
        self.menu_Edition.setObjectName(_fromUtf8("menu_Edition"))
        VictimesSinistre.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(VictimesSinistre)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        VictimesSinistre.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(VictimesSinistre)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        VictimesSinistre.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fichierNouveau = QtGui.QAction(VictimesSinistre)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-new.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierNouveau.setIcon(icon)
        self.fichierNouveau.setObjectName(_fromUtf8("fichierNouveau"))
        self.fichierEnregistrer = QtGui.QAction(VictimesSinistre)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-save.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierEnregistrer.setIcon(icon1)
        self.fichierEnregistrer.setObjectName(_fromUtf8("fichierEnregistrer"))
        self.fichierImprimer = QtGui.QAction(VictimesSinistre)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Imprimer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierImprimer.setIcon(icon2)
        self.fichierImprimer.setObjectName(_fromUtf8("fichierImprimer"))
        self.fichierFermer = QtGui.QAction(VictimesSinistre)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/system-log-out.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fichierFermer.setIcon(icon3)
        self.fichierFermer.setObjectName(_fromUtf8("fichierFermer"))
        self.editionAnnuler = QtGui.QAction(VictimesSinistre)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-undo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionAnnuler.setIcon(icon4)
        self.editionAnnuler.setObjectName(_fromUtf8("editionAnnuler"))
        self.editionRefaire = QtGui.QAction(VictimesSinistre)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-redo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionRefaire.setIcon(icon5)
        self.editionRefaire.setObjectName(_fromUtf8("editionRefaire"))
        self.editionPremier = QtGui.QAction(VictimesSinistre)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-first.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPremier.setIcon(icon6)
        self.editionPremier.setObjectName(_fromUtf8("editionPremier"))
        self.editionPrecedent = QtGui.QAction(VictimesSinistre)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-previous.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionPrecedent.setIcon(icon7)
        self.editionPrecedent.setObjectName(_fromUtf8("editionPrecedent"))
        self.editionSuivant = QtGui.QAction(VictimesSinistre)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-next.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionSuivant.setIcon(icon8)
        self.editionSuivant.setObjectName(_fromUtf8("editionSuivant"))
        self.editionDernier = QtGui.QAction(VictimesSinistre)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-last.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editionDernier.setIcon(icon9)
        self.editionDernier.setObjectName(_fromUtf8("editionDernier"))
        self.menu_Fichier.addAction(self.fichierNouveau)
        self.menu_Fichier.addAction(self.fichierEnregistrer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.fichierImprimer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.fichierFermer)
        self.menu_Edition.addAction(self.editionAnnuler)
        self.menu_Edition.addAction(self.editionRefaire)
        self.menu_Edition.addSeparator()
        self.menu_Edition.addAction(self.editionPremier)
        self.menu_Edition.addAction(self.editionPrecedent)
        self.menu_Edition.addAction(self.editionSuivant)
        self.menu_Edition.addAction(self.editionDernier)
        self.menubar.addAction(self.menu_Fichier.menuAction())
        self.menubar.addAction(self.menu_Edition.menuAction())
        self.toolBar.addAction(self.fichierNouveau)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionPremier)
        self.toolBar.addAction(self.editionPrecedent)
        self.toolBar.addAction(self.editionSuivant)
        self.toolBar.addAction(self.editionDernier)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editionRefaire)
        self.toolBar.addAction(self.editionAnnuler)
        self.toolBar.addAction(self.fichierEnregistrer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierImprimer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.fichierFermer)

        self.retranslateUi(VictimesSinistre)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VictimesSinistre)
        VictimesSinistre.setTabOrder(self.numIdComboBox, self.prenomComboBox)
        VictimesSinistre.setTabOrder(self.prenomComboBox, self.nomComboBox)
        VictimesSinistre.setTabOrder(self.nomComboBox, self.professionComboBox)
        VictimesSinistre.setTabOrder(self.professionComboBox, self.civiliteComboBox)
        VictimesSinistre.setTabOrder(self.civiliteComboBox, self.localisationComboBox)
        VictimesSinistre.setTabOrder(self.localisationComboBox, self.bpLineEdit)
        VictimesSinistre.setTabOrder(self.bpLineEdit, self.villeComboBox)
        VictimesSinistre.setTabOrder(self.villeComboBox, self.adressLineEdit)
        VictimesSinistre.setTabOrder(self.adressLineEdit, self.steLineEdit)
        VictimesSinistre.setTabOrder(self.steLineEdit, self.posteLineEdit)
        VictimesSinistre.setTabOrder(self.posteLineEdit, self.deptComboBox)
        VictimesSinistre.setTabOrder(self.deptComboBox, self.PhoneWLineEdit)
        VictimesSinistre.setTabOrder(self.PhoneWLineEdit, self.PhoneHLineEdit)
        VictimesSinistre.setTabOrder(self.PhoneHLineEdit, self.faxLineEdit)
        VictimesSinistre.setTabOrder(self.faxLineEdit, self.mailLineEdit)
        VictimesSinistre.setTabOrder(self.mailLineEdit, self.statutMatComboBox)
        VictimesSinistre.setTabOrder(self.statutMatComboBox, self.lieuNaissLineEdit)
        VictimesSinistre.setTabOrder(self.lieuNaissLineEdit, self.numCniLineEdit)
        VictimesSinistre.setTabOrder(self.numCniLineEdit, self.dateDelivranceDateEdit)
        VictimesSinistre.setTabOrder(self.dateDelivranceDateEdit, self.dateNaissDateEdit)
        VictimesSinistre.setTabOrder(self.dateNaissDateEdit, self.validiteDateEdit)
        VictimesSinistre.setTabOrder(self.validiteDateEdit, self.lieuDelivranceLineEdit)
        VictimesSinistre.setTabOrder(self.lieuDelivranceLineEdit, self.victimesEnregistreesListView)
        VictimesSinistre.setTabOrder(self.victimesEnregistreesListView, self.listeSinistresVictimeTableView)
        VictimesSinistre.setTabOrder(self.listeSinistresVictimeTableView, self.assureurVictimeSinistreTableView)
        VictimesSinistre.setTabOrder(self.assureurVictimeSinistreTableView, self.tabWidget)
        VictimesSinistre.setTabOrder(self.tabWidget, self.etatActuelVictimComboBox)
        VictimesSinistre.setTabOrder(self.etatActuelVictimComboBox, self.professionVictimComboBox)
        VictimesSinistre.setTabOrder(self.professionVictimComboBox, self.descDommageComboBox)
        VictimesSinistre.setTabOrder(self.descDommageComboBox, self.natDommageComboBox)
        VictimesSinistre.setTabOrder(self.natDommageComboBox, self.DescPrejudiceVictimTextEdit)
        VictimesSinistre.setTabOrder(self.DescPrejudiceVictimTextEdit, self.natLesionComboBox)
        VictimesSinistre.setTabOrder(self.natLesionComboBox, self.ageVictimSpinBox)
        VictimesSinistre.setTabOrder(self.ageVictimSpinBox, self.dureeProbHospSpinBox)
        VictimesSinistre.setTabOrder(self.dureeProbHospSpinBox, self.statutMatVictimComboBox)
        VictimesSinistre.setTabOrder(self.statutMatVictimComboBox, self.parenteAvecAssureComboBox)
        VictimesSinistre.setTabOrder(self.parenteAvecAssureComboBox, self.parenteAvecConducteurComboBox)
        VictimesSinistre.setTabOrder(self.parenteAvecConducteurComboBox, self.emplacementVictimAuSinistrComboBox)
        VictimesSinistre.setTabOrder(self.emplacementVictimAuSinistrComboBox, self.destVictimApresSinistrComboBox)
        VictimesSinistre.setTabOrder(self.destVictimApresSinistrComboBox, self.conclusionCertificatMedicalComboBox)
        VictimesSinistre.setTabOrder(self.conclusionCertificatMedicalComboBox, self.ObsSurVictimTextEdit)
        VictimesSinistre.setTabOrder(self.ObsSurVictimTextEdit, self.montantEstimeLineEdit)
        VictimesSinistre.setTabOrder(self.montantEstimeLineEdit, self.analysePrejudicesVictimeTableView)

    def retranslateUi(self, VictimesSinistre):
        VictimesSinistre.setWindowTitle(_translate("VictimesSinistre", "Victimes Sinistre", None))
        self.labelVictimesEnregistrees.setText(_translate("VictimesSinistre", "Victimes Enregistrees", None))
        self.victimesEnregistreesListView.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Liste des Victimes Enregistrees.</p></body></html>", None))
        self.victimesEnregistreesListView.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Liste des Victimes Enregistrees.</p></body></html>", None))
        self.labelNumId.setText(_translate("VictimesSinistre", "Numero Identifiant", None))
        self.numIdComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Numero Identifiant.</p></body></html>", None))
        self.numIdComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Numero Identifiant.</p></body></html>", None))
        self.labelPrenom.setText(_translate("VictimesSinistre", "Prenom", None))
        self.prenomComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Prenom.</p></body></html>", None))
        self.prenomComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Prenom.</p></body></html>", None))
        self.labelNom.setText(_translate("VictimesSinistre", "Nom", None))
        self.nomComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Nom.</p></body></html>", None))
        self.nomComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Nom.</p></body></html>", None))
        self.labelProfession.setText(_translate("VictimesSinistre", "Profession", None))
        self.professionComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Profession.</p></body></html>", None))
        self.professionComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Profession.</p></body></html>", None))
        self.labelCivilite.setText(_translate("VictimesSinistre", "Civilite", None))
        self.civiliteComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Civilite.</p></body></html>", None))
        self.civiliteComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Civilite.</p></body></html>", None))
        self.labelLocalisation.setText(_translate("VictimesSinistre", "Localisation", None))
        self.localisationComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Localisation.</p></body></html>", None))
        self.localisationComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Localisation.</p></body></html>", None))
        self.labelBP.setText(_translate("VictimesSinistre", "Boite Postale", None))
        self.bpLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Boite Postale.</p></body></html>", None))
        self.bpLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Boite Postale.</p></body></html>", None))
        self.labelVille.setText(_translate("VictimesSinistre", "Ville", None))
        self.villeComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Ville.</p></body></html>", None))
        self.villeComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Ville.</p></body></html>", None))
        self.labelAdresse.setText(_translate("VictimesSinistre", "Adresse", None))
        self.adressLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Adresse.</p></body></html>", None))
        self.adressLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Adresse.</p></body></html>", None))
        self.labelSociete.setText(_translate("VictimesSinistre", "Societe", None))
        self.steLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Societe.</p></body></html>", None))
        self.steLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Societe.</p></body></html>", None))
        self.labelPoste.setText(_translate("VictimesSinistre", "Poste occupe", None))
        self.posteLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Poste Occupe.</p></body></html>", None))
        self.posteLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Poste Occupe.</p></body></html>", None))
        self.labelDepartement.setText(_translate("VictimesSinistre", "Departement", None))
        self.deptComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Departement.</p></body></html>", None))
        self.deptComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Departement.</p></body></html>", None))
        self.labelPhoneBureau.setText(_translate("VictimesSinistre", "Telephone Bureau", None))
        self.PhoneWLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Numero du Telephone du Bureau.</p></body></html>", None))
        self.PhoneWLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Numero du Telephone du Bureau.</p></body></html>", None))
        self.labelPhonePortable.setText(_translate("VictimesSinistre", "Telephone Portable", None))
        self.PhoneHLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Numero du Telephone Portable.</p></body></html>", None))
        self.PhoneHLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Numero du Telephone Portable.</p></body></html>", None))
        self.labelFax.setText(_translate("VictimesSinistre", "Numero Fax", None))
        self.faxLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Numero de Fax.</p></body></html>", None))
        self.faxLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Numero de Fax.</p></body></html>", None))
        self.labelMail.setText(_translate("VictimesSinistre", "Adresse E-mail", None))
        self.mailLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Adresse E-mail.</p></body></html>", None))
        self.mailLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Adresse E-mail.</p></body></html>", None))
        self.labelEtatCivilVictime.setText(_translate("VictimesSinistre", "Etat-civil de la Victime", None))
        self.labelPieceIdOfficielle.setText(_translate("VictimesSinistre", "Piece d\'identite Officielle", None))
        self.labelNumCni.setText(_translate("VictimesSinistre", "Numero", None))
        self.numCniLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Numero de la CNI de la Victime.</p></body></html>", None))
        self.numCniLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Numero de la CNI de la Victime.</p></body></html>", None))
        self.labelValidite.setText(_translate("VictimesSinistre", "Validite", None))
        self.validiteDateEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Validite de la CNI de la Victime.</p></body></html>", None))
        self.validiteDateEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Validite de la CNI de la Victime.</p></body></html>", None))
        self.labelDateDelivrance.setText(_translate("VictimesSinistre", "Date delivrance", None))
        self.dateDelivranceDateEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Date Delivrance de la CNI de la Victime.</p></body></html>", None))
        self.dateDelivranceDateEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Date Delivrance de la CNI de la Victime.</p></body></html>", None))
        self.labelLieuDelivrance.setText(_translate("VictimesSinistre", "Lieu delivrance", None))
        self.lieuDelivranceLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Lieu de Delivrance de la CNI de la Victime.</p></body></html>", None))
        self.lieuDelivranceLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Lieu de Delivrance de la CNI de la Victime.</p></body></html>", None))
        self.statutMatComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Statut Matrimonial de la Victime.</p></body></html>", None))
        self.statutMatComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Statut Matrimonial de la Victime.</p></body></html>", None))
        self.labelStatutMat.setText(_translate("VictimesSinistre", "Statut matrimonial", None))
        self.labelLieuNaiss.setText(_translate("VictimesSinistre", "Lieu de Naissance", None))
        self.lieuNaissLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Lieu de Naissance de la Victime.</p></body></html>", None))
        self.lieuNaissLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Lieu de Naissance de la Victime.</p></body></html>", None))
        self.labelDateNaiss.setText(_translate("VictimesSinistre", "Date de Naissance", None))
        self.dateNaissDateEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Date de Naissance de la Victime.</p></body></html>", None))
        self.dateNaissDateEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Date de Naissance de la Victime.</p></body></html>", None))
        self.labelListeSinistresVictime.setText(_translate("VictimesSinistre", "Liste de tous les Sinistres de la Victime", None))
        self.listeSinistresVictimeTableView.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Liste de tous les Sinistres de la Victime.</p></body></html>", None))
        self.listeSinistresVictimeTableView.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Liste de tous les Sinistres de la Victime.</p></body></html>", None))
        self.labelAssureurVictimesSinistre.setText(_translate("VictimesSinistre", "Assureur Victimes Sinistre", None))
        self.assureurVictimeSinistreTableView.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Assureur de la Victime du Sinistre.</p></body></html>", None))
        self.assureurVictimeSinistreTableView.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Assureur de la Victime du Sinistre.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_id_victime), _translate("VictimesSinistre", "Identification de la Victime", None))
        self.labelEtatActuelVictime.setText(_translate("VictimesSinistre", "Etat actuel Victime", None))
        self.etatActuelVictimComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Etat actuel de la Victime.</p></body></html>", None))
        self.etatActuelVictimComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Etat actuel de la Victime.</p></body></html>", None))
        self.labelProfessionVictime.setText(_translate("VictimesSinistre", "Profession Victime", None))
        self.professionVictimComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Profession de la Victime.</p></body></html>", None))
        self.professionVictimComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Profession de la Victime.</p></body></html>", None))
        self.labelDescDommages.setText(_translate("VictimesSinistre", "Description des dommages", None))
        self.descDommageComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Description des dommages de la Victime.</p></body></html>", None))
        self.descDommageComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Description des dommages de la Victime.</p></body></html>", None))
        self.labelNatDommages.setText(_translate("VictimesSinistre", "Nature des dommages", None))
        self.natDommageComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Natures des dommages de la Victime.</p></body></html>", None))
        self.natDommageComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Natures des dommages de la Victime.</p></body></html>", None))
        self.labelDescPrejudices.setText(_translate("VictimesSinistre", "Description Prejudices Victime", None))
        self.DescPrejudiceVictimTextEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Description des Prejudices de la Victime.</p></body></html>", None))
        self.DescPrejudiceVictimTextEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Description des Prejudices de la Victime.</p></body></html>", None))
        self.labelNatLesions.setText(_translate("VictimesSinistre", "Nature des Lesions", None))
        self.natLesionComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Nature des Lesions de la Victime.</p></body></html>", None))
        self.natLesionComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Nature des Lesions de la Victime.</p></body></html>", None))
        self.labelAgeVictime.setText(_translate("VictimesSinistre", "Age Victime", None))
        self.ageVictimSpinBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Age de la Victime.</p></body></html>", None))
        self.ageVictimSpinBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Age de la Victime.</p></body></html>", None))
        self.labelDureeProbHosp.setText(_translate("VictimesSinistre", "Duree probable hospitalisation", None))
        self.dureeProbHospSpinBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Duree Probable d\'hopitalisation de la Victime.</p></body></html>", None))
        self.dureeProbHospSpinBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Duree Probable d\'hopitalisation de la Victime.</p></body></html>", None))
        self.labelStatutMatVictime.setText(_translate("VictimesSinistre", "Statut matrimonial Victime", None))
        self.statutMatVictimComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Statut Matrimonial de la Victime.</p></body></html>", None))
        self.statutMatVictimComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Statut Matrimonial de la Victime.</p></body></html>", None))
        self.labelParenteAvecAssure.setText(_translate("VictimesSinistre", "Parente avec Assure", None))
        self.parenteAvecAssureComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Parente avec l\'Assure.</p></body></html>", None))
        self.parenteAvecAssureComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Parente avec l\'Assure.</p></body></html>", None))
        self.labelParenteAvecConducteur.setText(_translate("VictimesSinistre", "Parente avec Conducteur", None))
        self.parenteAvecConducteurComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Parente avec le Conducteur.</p></body></html>", None))
        self.parenteAvecConducteurComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Parente avec le Conducteur.</p></body></html>", None))
        self.labelEmplacementVictimeAuSinistre.setText(_translate("VictimesSinistre", "Emplacement Victime au Sinistre", None))
        self.emplacementVictimAuSinistrComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Emplacement de la Victime au Sinistre.</p></body></html>", None))
        self.emplacementVictimAuSinistrComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Emplacement de la Victime au Sinistre.</p></body></html>", None))
        self.labelDestinationVictimeApresSinistre.setText(_translate("VictimesSinistre", "Destination Victime apres Sinistre", None))
        self.destVictimApresSinistrComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Destination de la Victime apres le Sinistre.</p></body></html>", None))
        self.destVictimApresSinistrComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Destination de la Victime apres le Sinistre.</p></body></html>", None))
        self.labelConclusionsCertificatMedical.setText(_translate("VictimesSinistre", "Conclusions Certificat Medical", None))
        self.conclusionCertificatMedicalComboBox.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Conclusions du Certificat Medical.</p></body></html>", None))
        self.conclusionCertificatMedicalComboBox.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Conclusions du Certificat Medical.</p></body></html>", None))
        self.labelObsSurVictime.setText(_translate("VictimesSinistre", "Observation sur la Victime", None))
        self.ObsSurVictimTextEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Observations faites sur la Victime du Sinistre.</p></body></html>", None))
        self.ObsSurVictimTextEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Observations faites sur la Victime du Sinistre.</p></body></html>", None))
        self.labelMontantEstime.setText(_translate("VictimesSinistre", "Montant estime", None))
        self.montantEstimeLineEdit.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Montant Estime.</p></body></html>", None))
        self.montantEstimeLineEdit.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Montant Estime.</p></body></html>", None))
        self.labelAnalysePrejudices.setText(_translate("VictimesSinistre", "Analyse des prejudices subis par la Victime", None))
        self.analysePrejudicesVictimeTableView.setToolTip(_translate("VictimesSinistre", "<html><head/><body><p>Analyse des Prejudices subis par la Victime du Sinistre.</p></body></html>", None))
        self.analysePrejudicesVictimeTableView.setWhatsThis(_translate("VictimesSinistre", "<html><head/><body><p>Analyse des Prejudices subis par la Victime du Sinistre.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_traitementdoc), _translate("VictimesSinistre", "Traitement dossier de la Victime", None))
        self.menu_Fichier.setTitle(_translate("VictimesSinistre", "&Fichier", None))
        self.menu_Edition.setTitle(_translate("VictimesSinistre", "&Edition", None))
        self.toolBar.setWindowTitle(_translate("VictimesSinistre", "toolBar", None))
        self.fichierNouveau.setText(_translate("VictimesSinistre", " Nouveau", None))
        self.fichierEnregistrer.setText(_translate("VictimesSinistre", "Enregistrer", None))
        self.fichierImprimer.setText(_translate("VictimesSinistre", "Imprimer Fiche de Suivit Victime", None))
        self.fichierFermer.setText(_translate("VictimesSinistre", "Fermer", None))
        self.editionAnnuler.setText(_translate("VictimesSinistre", "Annuler", None))
        self.editionRefaire.setText(_translate("VictimesSinistre", "Refaire", None))
        self.editionPremier.setText(_translate("VictimesSinistre", "Premier", None))
        self.editionPrecedent.setText(_translate("VictimesSinistre", "Precedent", None))
        self.editionSuivant.setText(_translate("VictimesSinistre", "Suivant", None))
        self.editionDernier.setText(_translate("VictimesSinistre", "Dernier", None))

import ressources_rc
