# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'validation_reversements.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ValidationReversements(object):
    def setupUi(self, ValidationReversements):
        ValidationReversements.setObjectName(_fromUtf8("ValidationReversements"))
        ValidationReversements.resize(1195, 593)
        self.centralwidget = QtGui.QWidget(ValidationReversements)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelNumBordereau = QtGui.QLabel(self.frame)
        self.labelNumBordereau.setObjectName(_fromUtf8("labelNumBordereau"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelNumBordereau)
        self.lineEditNumBordereau = QtGui.QLineEdit(self.frame)
        self.lineEditNumBordereau.setObjectName(_fromUtf8("lineEditNumBordereau"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditNumBordereau)
        self.labelCompagnie = QtGui.QLabel(self.frame)
        self.labelCompagnie.setObjectName(_fromUtf8("labelCompagnie"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelCompagnie)
        self.lineEditCompagnie = QtGui.QLineEdit(self.frame)
        self.lineEditCompagnie.setObjectName(_fromUtf8("lineEditCompagnie"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditCompagnie)
        self.labelAgence = QtGui.QLabel(self.frame)
        self.labelAgence.setObjectName(_fromUtf8("labelAgence"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelAgence)
        self.lineEditAgence = QtGui.QLineEdit(self.frame)
        self.lineEditAgence.setObjectName(_fromUtf8("lineEditAgence"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditAgence)
        self.labelOperateur = QtGui.QLabel(self.frame)
        self.labelOperateur.setObjectName(_fromUtf8("labelOperateur"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelOperateur)
        self.lineEditOperateur = QtGui.QLineEdit(self.frame)
        self.lineEditOperateur.setObjectName(_fromUtf8("lineEditOperateur"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditOperateur)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelDateVersement = QtGui.QLabel(self.frame)
        self.labelDateVersement.setObjectName(_fromUtf8("labelDateVersement"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelDateVersement)
        self.labelMontantAReverser = QtGui.QLabel(self.frame)
        self.labelMontantAReverser.setObjectName(_fromUtf8("labelMontantAReverser"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelMontantAReverser)
        self.lineEditMontantAReverser = QtGui.QLineEdit(self.frame)
        self.lineEditMontantAReverser.setObjectName(_fromUtf8("lineEditMontantAReverser"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditMontantAReverser)
        self.labelMontantReverse = QtGui.QLabel(self.frame)
        self.labelMontantReverse.setObjectName(_fromUtf8("labelMontantReverse"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelMontantReverse)
        self.lineEditMontantReverse = QtGui.QLineEdit(self.frame)
        self.lineEditMontantReverse.setObjectName(_fromUtf8("lineEditMontantReverse"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditMontantReverse)
        self.labelSoldeCourant = QtGui.QLabel(self.frame)
        self.labelSoldeCourant.setObjectName(_fromUtf8("labelSoldeCourant"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelSoldeCourant)
        self.lineEditSoldeCourant = QtGui.QLineEdit(self.frame)
        self.lineEditSoldeCourant.setObjectName(_fromUtf8("lineEditSoldeCourant"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditSoldeCourant)
        self.dateEditDateVersement = QtGui.QDateEdit(self.frame)
        self.dateEditDateVersement.setObjectName(_fromUtf8("dateEditDateVersement"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.dateEditDateVersement)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.labelDesignation = QtGui.QLabel(self.frame)
        self.labelDesignation.setObjectName(_fromUtf8("labelDesignation"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelDesignation)
        self.lineEditDesignation = QtGui.QLineEdit(self.frame)
        self.lineEditDesignation.setObjectName(_fromUtf8("lineEditDesignation"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditDesignation)
        self.labelCommentaires = QtGui.QLabel(self.frame)
        self.labelCommentaires.setObjectName(_fromUtf8("labelCommentaires"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelCommentaires)
        self.textEditCommentaires = QtGui.QTextEdit(self.frame)
        self.textEditCommentaires.setObjectName(_fromUtf8("textEditCommentaires"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.textEditCommentaires)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBoxRevSurEncaissements = QtGui.QCheckBox(self.frame)
        self.checkBoxRevSurEncaissements.setObjectName(_fromUtf8("checkBoxRevSurEncaissements"))
        self.verticalLayout.addWidget(self.checkBoxRevSurEncaissements)
        self.checkBoxRevNetCommissions = QtGui.QCheckBox(self.frame)
        self.checkBoxRevNetCommissions.setObjectName(_fromUtf8("checkBoxRevNetCommissions"))
        self.verticalLayout.addWidget(self.checkBoxRevNetCommissions)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.labelSoldeGeneral = QtGui.QLabel(self.frame)
        self.labelSoldeGeneral.setObjectName(_fromUtf8("labelSoldeGeneral"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelSoldeGeneral)
        self.lineEditSoldeGeneral = QtGui.QLineEdit(self.frame)
        self.lineEditSoldeGeneral.setObjectName(_fromUtf8("lineEditSoldeGeneral"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditSoldeGeneral)
        self.labelTotalReverse = QtGui.QLabel(self.frame)
        self.labelTotalReverse.setObjectName(_fromUtf8("labelTotalReverse"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelTotalReverse)
        self.lineEditTotalReverse = QtGui.QLineEdit(self.frame)
        self.lineEditTotalReverse.setObjectName(_fromUtf8("lineEditTotalReverse"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditTotalReverse)
        self.verticalLayout.addLayout(self.formLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.frame_2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableWidget_2 = QtGui.QTableWidget(self.frame_3)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.progressBar_2 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.horizontalLayout_2.addWidget(self.progressBar_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        ValidationReversements.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ValidationReversements)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1195, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Fichier = QtGui.QMenu(self.menubar)
        self.menu_Fichier.setObjectName(_fromUtf8("menu_Fichier"))
        self.menu_Edition = QtGui.QMenu(self.menubar)
        self.menu_Edition.setObjectName(_fromUtf8("menu_Edition"))
        ValidationReversements.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ValidationReversements)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ValidationReversements.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(ValidationReversements)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        ValidationReversements.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNouveau = QtGui.QAction(ValidationReversements)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-new.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNouveau.setIcon(icon)
        self.actionNouveau.setObjectName(_fromUtf8("actionNouveau"))
        self.actionEnregistrer = QtGui.QAction(ValidationReversements)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/document-save.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnregistrer.setIcon(icon1)
        self.actionEnregistrer.setObjectName(_fromUtf8("actionEnregistrer"))
        self.actionImprimer_le_bordereau_de_Reversement = QtGui.QAction(ValidationReversements)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Imprimer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImprimer_le_bordereau_de_Reversement.setIcon(icon2)
        self.actionImprimer_le_bordereau_de_Reversement.setObjectName(_fromUtf8("actionImprimer_le_bordereau_de_Reversement"))
        self.actionFermer = QtGui.QAction(ValidationReversements)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/system-log-out.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFermer.setIcon(icon3)
        self.actionFermer.setObjectName(_fromUtf8("actionFermer"))
        self.actionAnnuler = QtGui.QAction(ValidationReversements)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-undo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnnuler.setIcon(icon4)
        self.actionAnnuler.setObjectName(_fromUtf8("actionAnnuler"))
        self.actionRefaire = QtGui.QAction(ValidationReversements)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/edit-redo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefaire.setIcon(icon5)
        self.actionRefaire.setObjectName(_fromUtf8("actionRefaire"))
        self.actionPremier = QtGui.QAction(ValidationReversements)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-first.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPremier.setIcon(icon6)
        self.actionPremier.setObjectName(_fromUtf8("actionPremier"))
        self.actionPrecedent = QtGui.QAction(ValidationReversements)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-previous.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrecedent.setIcon(icon7)
        self.actionPrecedent.setObjectName(_fromUtf8("actionPrecedent"))
        self.actionSuivant = QtGui.QAction(ValidationReversements)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-next.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSuivant.setIcon(icon8)
        self.actionSuivant.setObjectName(_fromUtf8("actionSuivant"))
        self.actionDernier = QtGui.QAction(ValidationReversements)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/go-last.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDernier.setIcon(icon9)
        self.actionDernier.setObjectName(_fromUtf8("actionDernier"))
        self.menu_Fichier.addAction(self.actionNouveau)
        self.menu_Fichier.addAction(self.actionEnregistrer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.actionImprimer_le_bordereau_de_Reversement)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.actionFermer)
        self.menu_Edition.addAction(self.actionAnnuler)
        self.menu_Edition.addAction(self.actionRefaire)
        self.menu_Edition.addSeparator()
        self.menu_Edition.addAction(self.actionPremier)
        self.menu_Edition.addAction(self.actionPrecedent)
        self.menu_Edition.addAction(self.actionSuivant)
        self.menu_Edition.addAction(self.actionDernier)
        self.menubar.addAction(self.menu_Fichier.menuAction())
        self.menubar.addAction(self.menu_Edition.menuAction())
        self.toolBar.addAction(self.actionNouveau)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPremier)
        self.toolBar.addAction(self.actionPrecedent)
        self.toolBar.addAction(self.actionSuivant)
        self.toolBar.addAction(self.actionDernier)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRefaire)
        self.toolBar.addAction(self.actionAnnuler)
        self.toolBar.addAction(self.actionEnregistrer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionImprimer_le_bordereau_de_Reversement)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFermer)

        self.retranslateUi(ValidationReversements)
        QtCore.QMetaObject.connectSlotsByName(ValidationReversements)
        ValidationReversements.setTabOrder(self.lineEditNumBordereau, self.lineEditCompagnie)
        ValidationReversements.setTabOrder(self.lineEditCompagnie, self.lineEditAgence)
        ValidationReversements.setTabOrder(self.lineEditAgence, self.lineEditOperateur)
        ValidationReversements.setTabOrder(self.lineEditOperateur, self.dateEditDateVersement)
        ValidationReversements.setTabOrder(self.dateEditDateVersement, self.lineEditMontantAReverser)
        ValidationReversements.setTabOrder(self.lineEditMontantAReverser, self.lineEditMontantReverse)
        ValidationReversements.setTabOrder(self.lineEditMontantReverse, self.lineEditSoldeCourant)
        ValidationReversements.setTabOrder(self.lineEditSoldeCourant, self.lineEditDesignation)
        ValidationReversements.setTabOrder(self.lineEditDesignation, self.textEditCommentaires)
        ValidationReversements.setTabOrder(self.textEditCommentaires, self.checkBoxRevSurEncaissements)
        ValidationReversements.setTabOrder(self.checkBoxRevSurEncaissements, self.checkBoxRevNetCommissions)
        ValidationReversements.setTabOrder(self.checkBoxRevNetCommissions, self.lineEditSoldeGeneral)
        ValidationReversements.setTabOrder(self.lineEditSoldeGeneral, self.lineEditTotalReverse)
        ValidationReversements.setTabOrder(self.lineEditTotalReverse, self.tableWidget)
        ValidationReversements.setTabOrder(self.tableWidget, self.tableWidget_2)

    def retranslateUi(self, ValidationReversements):
        ValidationReversements.setWindowTitle(_translate("ValidationReversements", "Validation Reversements", None))
        self.labelNumBordereau.setText(_translate("ValidationReversements", "Numero Bordereau", None))
        self.labelCompagnie.setText(_translate("ValidationReversements", "Compagnie", None))
        self.labelAgence.setText(_translate("ValidationReversements", "Reseau/Agence", None))
        self.labelOperateur.setText(_translate("ValidationReversements", "Operateur", None))
        self.labelDateVersement.setText(_translate("ValidationReversements", "Date de Versement", None))
        self.labelMontantAReverser.setText(_translate("ValidationReversements", "Montant a reverser", None))
        self.labelMontantReverse.setText(_translate("ValidationReversements", "Montant reverse", None))
        self.labelSoldeCourant.setText(_translate("ValidationReversements", "Solde courant", None))
        self.labelDesignation.setText(_translate("ValidationReversements", "Designation", None))
        self.labelCommentaires.setText(_translate("ValidationReversements", "Commentaires", None))
        self.checkBoxRevSurEncaissements.setText(_translate("ValidationReversements", "Reversements sur Encaissements ?", None))
        self.checkBoxRevNetCommissions.setText(_translate("ValidationReversements", "Reversements net de Commissions ?", None))
        self.labelSoldeGeneral.setText(_translate("ValidationReversements", "Solde General", None))
        self.labelTotalReverse.setText(_translate("ValidationReversements", "Total reverse", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("ValidationReversements", "Line1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("ValidationReversements", "Line2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("ValidationReversements", "Line3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("ValidationReversements", "Line4", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ValidationReversements", "Col1", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ValidationReversements", "Col2", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ValidationReversements", "Col3", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ValidationReversements", "Col4", None))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("ValidationReversements", "Line1", None))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("ValidationReversements", "Line2", None))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("ValidationReversements", "Line3", None))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("ValidationReversements", "Line4", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("ValidationReversements", "Col1", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("ValidationReversements", "Col2", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("ValidationReversements", "Col3", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("ValidationReversements", "Col4", None))
        self.menu_Fichier.setTitle(_translate("ValidationReversements", "&Fichier", None))
        self.menu_Edition.setTitle(_translate("ValidationReversements", "&Edition", None))
        self.toolBar.setWindowTitle(_translate("ValidationReversements", "toolBar", None))
        self.actionNouveau.setText(_translate("ValidationReversements", "Nouveau", None))
        self.actionEnregistrer.setText(_translate("ValidationReversements", "Enregistrer", None))
        self.actionImprimer_le_bordereau_de_Reversement.setText(_translate("ValidationReversements", "Imprimer le bordereau de Reversement", None))
        self.actionFermer.setText(_translate("ValidationReversements", "Fermer", None))
        self.actionAnnuler.setText(_translate("ValidationReversements", "Annuler", None))
        self.actionRefaire.setText(_translate("ValidationReversements", "Refaire", None))
        self.actionPremier.setText(_translate("ValidationReversements", "Premier", None))
        self.actionPrecedent.setText(_translate("ValidationReversements", "Precedent", None))
        self.actionSuivant.setText(_translate("ValidationReversements", "Suivant", None))
        self.actionDernier.setText(_translate("ValidationReversements", "Dernier", None))

import ressources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ValidationReversements = QtGui.QMainWindow()
    ui = Ui_ValidationReversements()
    ui.setupUi(ValidationReversements)
    ValidationReversements.show()
    sys.exit(app.exec_())

