#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'Luc Mathurin Waffo Modjom'
__version__ = '1.0.0'

from PyQt4 import QtCore, QtGui, QtSql

class Sinistre(QtSql.QSqlRelationalTableModel):
    # Constantes
    ID_SINISTRE, NUMERO_DOSSIER, POLICE_ID, ASSUREUR_ID, SOCIETAIRE_DECLARANT, REFERENCES_FICHIER, NATURE_SINISTRE_ID, \
    DATE_DECLARATION, MIS_EN_CAUSE_PAR_TIERS, UTILISATEUR_ID, DATE_OUVERTURE, OBJET_ASSURE_ID, VEHICULE_MIS_EN_CAUSE, \
    DATE_SINISTRE, LIEU_SINISTRE, GARANTIE_EN_COURS, CIRCONSTANCES, DOMMAGE_VEHICULE_ASSURE, USAGE_LORS_DU_SINISTRE, \
    APPROBATION_INITIALE_ASSURE, PASSAGERS_PENDANT_SINISTRE, CONSTAT_AMIABLE, COMPTE_RENDU_CONSTAT, OBSERVATION, \
    REGLEMENT, DOSSIER_COMPLET, PIECE_FOURNIE, DOSSIER_TRANSMIS_A_ASSUREUR, DATE_TRANSMISSION, ACCUSE_RECEPTION_ASSUREUR, \
    DATE_ACCUSE_ASSUREUR, EXPERT_SOLLICITE, DATE_SOLLICITATION_EXPERT, EXPERTISE_EFFECTUEE, DATE_REPONSE_EXPERTISE, \
    MONTANT_CONCLUSIONS_EXPERT, CONCLUSIONS_EXPERT_ACCEPTEES, DATE_ACCORD_CONCLUSION, MONTANT_PROPOSITION_ASSUREUR, \
    MONTANT_REGLEMENT, DATE_REGLEMENT, EXERCICE, NUMERO_ORDRE, NUMERO_POLICE, GARANTIE, USAGE, RESEAU, PSAP_OUVERTURE, \
    PAIEMENT_PRINCIPAL, PAIEMENT_ACCESSOIRES, TERMINE, CLASSE, EN_COURS, STAND_BY, RISQUE_ADVERSE, ASSUREUR_ADVERSE_ID, \
    LIBELLE_ASSUREUR_ADVERSE, POLICE_ADVERSAIRE, EFFET_POLICE_ADVERSAIRE, TERME_POLICE_ADVERSAIRE, POLICE_CONNEXE, \
    PROPRIETAIRE_VEHICULE_ADVERSE, ADRESSE_PROPRIETAIRE_VEHICULE_ADVERSE, ASSURE_ADVERSE, ADRESSE_ASSURE_ADVERSE, \
    CONDUCTEUR_ADVERSAIRE, DOMMAGE_ADVERSAIRES, DECLARATION_ADVERSAIRE, DATE_DECLARATION_ADVERSAIRE, ADVERSAIRE, \
    REFERENCE_ADVERSAIRE, PERSONNE_ID, DATE_CREATION, REF_IMPORTATION, DATE_IMPORTATION = range(75)

    def __init__(self, parent=None):
        super(Sinistre, self).__init__(parent)

        self.setTable("sinistre")
        self.setRelation(self.ASSUREUR_ID, QtSql.QSqlRelation("assureur", "id_assureur", "libelle_assureur"))
        self.setRelation(self.NATURE_SINISTRE_ID, QtSql.QSqlRelation("nature_sinistre", "id_nature_sinistre", "libelle_nature_sinistre"))
        self.setRelation(self.OBJET_ASSURE_ID, QtSql.QSqlRelation("objet_assure", "id_objet_assure", "libelle_objet_assure"))
        self.setRelation(self.PERSONNE_ID, QtSql.QSqlRelation("personne", "id_personne", "numero_personne"))
        self.setRelation(self.POLICE_ID, QtSql.QSqlRelation("police", "id_police", "numero_police"))
        self.setRelation(self.UTILISATEUR_ID, QtSql.QSqlRelation("utilisateur", "id_utilisateur", "numero_utilisateur"))

        self.select()